version: 2
sources:
- name: sv_blocks
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_absentee_ballot_request_forms
  - name: _airbyte_raw_activism_options_configs
  - name: _airbyte_raw_activist_code_counts
  - name: _airbyte_raw_activist_codes
  - name: _airbyte_raw_activities
  - name: _airbyte_raw_address_districts
  - name: _airbyte_raw_addresses
  - name: _airbyte_raw_age_to_bin
  - name: _airbyte_raw_announcements
  - name: _airbyte_raw_announcements_views
  - name: _airbyte_raw_ar_internal_metadata
  - name: _airbyte_raw_campaigns
  - name: _airbyte_raw_campaigns_people
  - name: _airbyte_raw_campaigns_teams
  - name: _airbyte_raw_canvassers
  - name: _airbyte_raw_captricity_batches
  - name: _airbyte_raw_catalist_uploads
  - name: _airbyte_raw_catalist_uploads_registration_forms
  - name: _airbyte_raw_check_in_answers
  - name: _airbyte_raw_check_in_questions
  - name: _airbyte_raw_check_ins
  - name: _airbyte_raw_collections
  - name: _airbyte_raw_collections_roles
  - name: _airbyte_raw_contact_methods
  - name: _airbyte_raw_coorganizations
  - name: _airbyte_raw_counties
  - name: _airbyte_raw_dashboard_layouts
  - name: _airbyte_raw_dashboard_widgets
  - name: _airbyte_raw_delayed_jobs
  - name: _airbyte_raw_deliveries
  - name: _airbyte_raw_delivery_forms_exclusions
  - name: _airbyte_raw_denominations
  - name: _airbyte_raw_denominations_organizations
  - name: _airbyte_raw_denominations_people
  - name: _airbyte_raw_district_types
  - name: _airbyte_raw_districts
  - name: _airbyte_raw_documents
  - name: _airbyte_raw_elections
  - name: _airbyte_raw_email_templates
  - name: _airbyte_raw_email_templates_events
  - name: _airbyte_raw_event_attendees
  - name: _airbyte_raw_event_documents
  - name: _airbyte_raw_event_shifts
  - name: _airbyte_raw_event_types
  - name: _airbyte_raw_events
  - name: _airbyte_raw_events_teams
  - name: _airbyte_raw_field_management_goals
  - name: _airbyte_raw_field_management_projections
  - name: _airbyte_raw_filter_rules
  - name: _airbyte_raw_filter_views
  - name: _airbyte_raw_folders
  - name: _airbyte_raw_friendly_id_slugs
  - name: _airbyte_raw_grouping_measurements
  - name: _airbyte_raw_groupings
  - name: _airbyte_raw_import_files
  - name: _airbyte_raw_imports
  - name: _airbyte_raw_imports_error_rows
  - name: _airbyte_raw_landing_page_signups
  - name: _airbyte_raw_list_folders
  - name: _airbyte_raw_list_folders_users
  - name: _airbyte_raw_lists
  - name: _airbyte_raw_lists_people
  - name: _airbyte_raw_locations
  - name: _airbyte_raw_locations_organizations
  - name: _airbyte_raw_meetings
  - name: _airbyte_raw_metrics
  - name: _airbyte_raw_notes
  - name: _airbyte_raw_organization_memberships
  - name: _airbyte_raw_organizations
  - name: _airbyte_raw_organizations_teams
  - name: _airbyte_raw_parties
  - name: _airbyte_raw_people
  - name: _airbyte_raw_petitions_books
  - name: _airbyte_raw_petitions_canvasser_pages
  - name: _airbyte_raw_petitions_pages
  - name: _airbyte_raw_petitions_signatures
  - name: _airbyte_raw_phone_banking_answer_options
  - name: _airbyte_raw_phone_banking_calls
  - name: _airbyte_raw_phone_banking_phone_banks
  - name: _airbyte_raw_phone_banking_questions
  - name: _airbyte_raw_phone_banking_responses
  - name: _airbyte_raw_phone_banking_script_objects
  - name: _airbyte_raw_phone_banking_script_texts
  - name: _airbyte_raw_phone_banking_scripts
  - name: _airbyte_raw_phone_banking_sessions
  - name: _airbyte_raw_phone_verification_questions
  - name: _airbyte_raw_phone_verification_responses
  - name: _airbyte_raw_projections
  - name: _airbyte_raw_public_event_links
  - name: _airbyte_raw_quality_control_comments
  - name: _airbyte_raw_quality_control_comments_users
  - name: _airbyte_raw_quality_control_flag_triggers
  - name: _airbyte_raw_quality_control_flags
  - name: _airbyte_raw_quality_control_flags_views
  - name: _airbyte_raw_quality_control_flags_voter_registration_scans
  - name: _airbyte_raw_quality_control_phone_verification_calls
  - name: _airbyte_raw_quality_control_phone_verification_question_translations
  - name: _airbyte_raw_quality_control_phone_verification_scripts
  - name: _airbyte_raw_quality_control_schedules
  - name: _airbyte_raw_quick_links
  - name: _airbyte_raw_registrant_matches
  - name: _airbyte_raw_registration_forms
  - name: _airbyte_raw_relationship_types
  - name: _airbyte_raw_relationships
  - name: _airbyte_raw_reports
  - name: _airbyte_raw_responsibilities
  - name: _airbyte_raw_roles
  - name: _airbyte_raw_scheduled_exports
  - name: _airbyte_raw_scheduled_exports_turfs
  - name: _airbyte_raw_schedules
  - name: _airbyte_raw_schema_migrations
  - name: _airbyte_raw_searches
  - name: _airbyte_raw_shifts
  - name: _airbyte_raw_state_party_codes
  - name: _airbyte_raw_states
  - name: _airbyte_raw_taggings
  - name: _airbyte_raw_tags
  - name: _airbyte_raw_tasks
  - name: _airbyte_raw_teachers
  - name: _airbyte_raw_team_memberships
  - name: _airbyte_raw_teams
  - name: _airbyte_raw_tenant_quick_links
  - name: _airbyte_raw_turf_levels
  - name: _airbyte_raw_turfs
  - name: _airbyte_raw_twilio_calls
  - name: _airbyte_raw_user_profiles
  - name: _airbyte_raw_users
  - name: _airbyte_raw_venues
  - name: _airbyte_raw_versions
  - name: _airbyte_raw_visual_review_responses
  - name: _airbyte_raw_volunteerships
  - name: _airbyte_raw_voted_labels
  - name: _airbyte_raw_voter_histories
  - name: _airbyte_raw_voter_registration_scan_batch_cover_sheets
  - name: _airbyte_raw_voter_registration_scan_batches
  - name: _airbyte_raw_voter_registration_scan_visual_review_responses
  - name: _airbyte_raw_voter_registration_scans
  - name: _airbyte_raw_voter_sources
  - name: _airbyte_raw_votes
  - name: _airbyte_raw_vr_zips_lookup
