version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_absentee_ballot_request_forms
  - name: _airbyte_raw_activism_options_configs
  - name: _airbyte_raw_activist_code_counts
  - name: _airbyte_raw_activist_codes
  - name: _airbyte_raw_activities
  - name: _airbyte_raw_address_districts
  - name: _airbyte_raw_addresses
  - name: _airbyte_raw_age_to_bin
  - name: _airbyte_raw_announcements
  - name: _airbyte_raw_announcements_views
  - name: _airbyte_raw_ar_internal_metadata
  - name: _airbyte_raw_campaigns
  - name: _airbyte_raw_campaigns_people
  - name: _airbyte_raw_campaigns_teams
  - name: _airbyte_raw_canvassers
  - name: _airbyte_raw_captricity_batches
  - name: _airbyte_raw_catalist_uploads
  - name: _airbyte_raw_catalist_uploads_registration_forms
  - name: _airbyte_raw_check_in_answers
  - name: _airbyte_raw_check_in_questions
  - name: _airbyte_raw_check_ins
  - name: _airbyte_raw_collections
  - name: _airbyte_raw_collections_roles
  - name: _airbyte_raw_contact_methods
  - name: _airbyte_raw_coorganizations
  - name: _airbyte_raw_counties
  - name: _airbyte_raw_dashboard_layouts
  - name: _airbyte_raw_dashboard_widgets
  - name: _airbyte_raw_delayed_jobs
  - name: _airbyte_raw_deliveries
  - name: _airbyte_raw_delivery_forms_exclusions
  - name: _airbyte_raw_denominations
  - name: _airbyte_raw_denominations_organizations
  - name: _airbyte_raw_denominations_people
  - name: _airbyte_raw_district_types
  - name: _airbyte_raw_districts
  - name: _airbyte_raw_documents
  - name: _airbyte_raw_elections
  - name: _airbyte_raw_email_templates
  - name: _airbyte_raw_email_templates_events
  - name: _airbyte_raw_event_attendees
  - name: _airbyte_raw_event_documents
  - name: _airbyte_raw_event_shifts
  - name: _airbyte_raw_event_types
  - name: _airbyte_raw_events
  - name: _airbyte_raw_events_teams
  - name: _airbyte_raw_field_management_goals
  - name: _airbyte_raw_field_management_projections
  - name: _airbyte_raw_filter_rules
  - name: _airbyte_raw_filter_views
  - name: _airbyte_raw_folders
  - name: _airbyte_raw_friendly_id_slugs
  - name: _airbyte_raw_grouping_measurements
  - name: _airbyte_raw_groupings
  - name: _airbyte_raw_import_files
  - name: _airbyte_raw_imports
  - name: _airbyte_raw_imports_error_rows
  - name: _airbyte_raw_landing_page_signups
  - name: _airbyte_raw_list_folders
  - name: _airbyte_raw_list_folders_users
  - name: _airbyte_raw_lists
  - name: _airbyte_raw_lists_people
  - name: _airbyte_raw_locations
  - name: _airbyte_raw_locations_organizations
  - name: _airbyte_raw_meetings
  - name: _airbyte_raw_metrics
  - name: _airbyte_raw_notes
  - name: _airbyte_raw_organization_memberships
  - name: _airbyte_raw_organizations
  - name: _airbyte_raw_organizations_teams
  - name: _airbyte_raw_parties
  - name: _airbyte_raw_people
  - name: _airbyte_raw_petitions_books
  - name: _airbyte_raw_petitions_canvasser_pages
  - name: _airbyte_raw_petitions_pages
  - name: _airbyte_raw_petitions_signatures
  - name: _airbyte_raw_phone_banking_answer_options
  - name: _airbyte_raw_phone_banking_calls
  - name: _airbyte_raw_phone_banking_phone_banks
  - name: _airbyte_raw_phone_banking_questions
  - name: _airbyte_raw_phone_banking_responses
  - name: _airbyte_raw_phone_banking_script_objects
  - name: _airbyte_raw_phone_banking_script_texts
  - name: _airbyte_raw_phone_banking_scripts
  - name: _airbyte_raw_phone_banking_sessions
  - name: _airbyte_raw_phone_verification_questions
  - name: _airbyte_raw_phone_verification_responses
  - name: _airbyte_raw_projections
  - name: _airbyte_raw_public_event_links
  - name: _airbyte_raw_quality_control_comments
  - name: _airbyte_raw_quality_control_comments_users
  - name: _airbyte_raw_quality_control_flag_triggers
  - name: _airbyte_raw_quality_control_flags
  - name: _airbyte_raw_quality_control_flags_views
  - name: _airbyte_raw_quality_control_flags_voter_registration_scans
  - name: _airbyte_raw_quality_control_phone_verification_calls
  - name: _airbyte_raw_quality_control_phone_verification_question_translations
  - name: _airbyte_raw_quality_control_phone_verification_scripts
  - name: _airbyte_raw_quality_control_schedules
  - name: _airbyte_raw_quick_links
  - name: _airbyte_raw_registrant_matches
  - name: _airbyte_raw_registration_forms
  - name: _airbyte_raw_relationship_types
  - name: _airbyte_raw_relationships
  - name: _airbyte_raw_reports
  - name: _airbyte_raw_responsibilities
  - name: _airbyte_raw_roles
  - name: _airbyte_raw_scheduled_exports
  - name: _airbyte_raw_scheduled_exports_turfs
  - name: _airbyte_raw_schedules
  - name: _airbyte_raw_schema_migrations
  - name: _airbyte_raw_searches
  - name: _airbyte_raw_shifts
  - name: _airbyte_raw_state_party_codes
  - name: _airbyte_raw_states
  - name: _airbyte_raw_taggings
  - name: _airbyte_raw_tags
  - name: _airbyte_raw_tasks
  - name: _airbyte_raw_teachers
  - name: _airbyte_raw_team_memberships
  - name: _airbyte_raw_teams
  - name: _airbyte_raw_tenant_quick_links
  - name: _airbyte_raw_turf_levels
  - name: _airbyte_raw_turfs
  - name: _airbyte_raw_twilio_calls
  - name: _airbyte_raw_user_profiles
  - name: _airbyte_raw_users
  - name: _airbyte_raw_venues
  - name: _airbyte_raw_versions
  - name: _airbyte_raw_visual_review_responses
  - name: _airbyte_raw_volunteerships
  - name: _airbyte_raw_voted_labels
  - name: _airbyte_raw_voter_histories
  - name: _airbyte_raw_voter_registration_scan_batch_cover_sheets
  - name: _airbyte_raw_voter_registration_scan_batches
  - name: _airbyte_raw_voter_registration_scan_visual_review_responses
  - name: _airbyte_raw_voter_registration_scans
  - name: _airbyte_raw_voter_sources
  - name: _airbyte_raw_votes
  - name: _airbyte_raw_vr_zips_lookup
  - name: _airbyte_raw_actions
  - name: _airbyte_raw_admin_users
  - name: _airbyte_raw_blocks
  - name: _airbyte_raw_districts_inbound
  - name: _airbyte_raw_documents_phone_banking_phone_banks
  - name: _airbyte_raw_import_lcv
  - name: _airbyte_raw_petition_packets
  - name: _airbyte_raw_search_documents
  - name: _airbyte_raw_sent_emails
  - name: _airbyte_raw_tenant_blocks
  - name: _airbyte_raw_tenants
  - name: _airbyte_raw_widgets
  - name: absentee_ballot_request_forms_base
  - name: activism_options_configs_base
  - name: activist_code_counts_base
  - name: activist_codes_base
  - name: activities_base
  - name: address_districts_base
  - name: addresses_base
  - name: age_to_bin_base
  - name: announcements_base
  - name: announcements_views_base
  - name: ar_internal_metadata_base
  - name: campaigns_base
  - name: campaigns_people_base
  - name: campaigns_teams_base
  - name: canvassers_base
  - name: captricity_batches_base
  - name: catalist_uploads_base
  - name: catalist_uploads_registration_forms_base
  - name: check_in_answers_base
  - name: check_in_questions_base
  - name: check_ins_base
  - name: collections_base
  - name: collections_roles_base
  - name: contact_methods_base
  - name: coorganizations_base
  - name: counties_base
  - name: dashboard_layouts_base
  - name: dashboard_widgets_base
  - name: delayed_jobs_base
  - name: deliveries_base
  - name: delivery_forms_exclusions_base
  - name: denominations_base
  - name: denominations_organizations_base
  - name: denominations_people_base
  - name: district_types_base
  - name: districts_base
  - name: documents_base
  - name: elections_base
  - name: email_templates_base
  - name: email_templates_events_base
  - name: event_attendees_base
  - name: event_documents_base
  - name: event_shifts_base
  - name: event_types_base
  - name: events_base
  - name: events_teams_base
  - name: field_management_goals_base
  - name: field_management_projections_base
  - name: filter_rules_base
  - name: filter_views_base
  - name: folders_base
  - name: friendly_id_slugs_base
  - name: grouping_measurements_base
  - name: groupings_base
  - name: import_files_base
  - name: imports_base
  - name: imports_error_rows_base
  - name: landing_page_signups_base
  - name: list_folders_base
  - name: list_folders_users_base
  - name: lists_base
  - name: lists_people_base
  - name: locations_base
  - name: locations_organizations_base
  - name: meetings_base
  - name: metrics_base
  - name: notes_base
  - name: organization_memberships_base
  - name: organizations_base
  - name: organizations_teams_base
  - name: parties_base
  - name: people_base
  - name: petitions_books_base
  - name: petitions_canvasser_pages_base
  - name: petitions_pages_base
  - name: petitions_signatures_base
  - name: phone_banking_answer_options_base
  - name: phone_banking_calls_base
  - name: phone_banking_phone_banks_base
  - name: phone_banking_questions_base
  - name: phone_banking_responses_base
  - name: phone_banking_script_objects_base
  - name: phone_banking_script_texts_base
  - name: phone_banking_scripts_base
  - name: phone_banking_sessions_base
  - name: phone_verification_questions_base
  - name: phone_verification_responses_base
  - name: projections_base
  - name: public_event_links_base
  - name: quality_control_comments_base
  - name: quality_control_comments_users_base
  - name: quality_control_flag_triggers_base
  - name: quality_control_flags_base
  - name: quality_control_flags_views_base
  - name: quality_control_flags_voter_registration_scans_base
  - name: quality_control_phone_verification_calls_base
  - name: quality_control_phone_verification_question_translations_base
  - name: quality_control_phone_verification_scripts_base
  - name: quality_control_schedules_base
  - name: quick_links_base
  - name: registrant_matches_base
  - name: registration_forms_base
  - name: relationship_types_base
  - name: relationships_base
  - name: reports_base
  - name: responsibilities_base
  - name: roles_base
  - name: scheduled_exports_base
  - name: scheduled_exports_turfs_base
  - name: schedules_base
  - name: schema_migrations_base
  - name: searches_base
  - name: shifts_base
  - name: state_party_codes_base
  - name: states_base
  - name: taggings_base
  - name: tags_base
  - name: tasks_base
  - name: teachers_base
  - name: team_memberships_base
  - name: teams_base
  - name: tenant_quick_links_base
  - name: turf_levels_base
  - name: turfs_base
  - name: twilio_calls_base
  - name: user_profiles_base
  - name: users_base
  - name: venues_base
  - name: versions_base
  - name: visual_review_responses_base
  - name: volunteerships_base
  - name: voted_labels_base
  - name: voter_histories_base
  - name: voter_registration_scan_batch_cover_sheets_base
  - name: voter_registration_scan_batches_base
  - name: voter_registration_scan_visual_review_responses_base
  - name: voter_registration_scans_base
  - name: voter_sources_base
  - name: votes_base
  - name: vr_zips_lookup_base
  - name: actions_base
  - name: admin_users_base
  - name: blocks_base
  - name: districts_inbound_base
  - name: documents_phone_banking_phone_banks_base
  - name: import_lcv_base
  - name: petition_packets_base
  - name: search_documents_base
  - name: sent_emails_base
  - name: tenant_blocks_base
  - name: tenants_base
  - name: widgets_base