{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'email_events') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    _airbyte_generation_id,
    cc,
    id,
    bcc,
    url,
    `from`,
    hmid,
    type,
    appId,
    linkId,
    sentBy,
    smtpId,
    `source`,
    status,
    appName,
    attempt,
    bounced,
    browser,
    created,
    referer,
    replyTo,
    subject,
    category,
    causedBy,
    duration,
    location,
    portalId,
    response,
    sourceId,
    ipAddress,
    recipient,
    userAgent,
    deviceType,
    dropReason,
    dropMessage,
    obsoletedBy,
    requestedBy,
    filteredEvent,
    subscriptions,
    emailCampaignId,
    requestedByUserId,
    emailCampaignGroupId,
    portalSubscriptionStatus,
   {{ dbt_utils.surrogate_key([
     'id',
    'url',
    'hmid',
    'type',
    'appId',
    'linkId',
    'smtpId',
    'status',
    'appName',
    'attempt',
    'bounced',
    'created',
    'referer',
    'subject',
    'category',
    'duration',
    'portalId',
    'response',
    'sourceId',
    'ipAddress',
    'recipient',
    'userAgent',
    'deviceType',
    'dropReason',
    'dropMessage',
    'requestedBy',
    'filteredEvent',
    'emailCampaignId',
    'requestedByUserId',
    'emailCampaignGroupId',
    'portalSubscriptionStatus'
    ]) }} as _airbyte_email_events_hashid
from {{ source('cta', 'email_events') }}
