
{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'forms') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   _airbyte_generation_id,
   id,
   name,
   archived,
   formType,
   createdAt,
   deletedAt,
   updatedAt,
   properties,
   fieldGroups,
   configuration,
   displayOptions,
   properties_hs_name,
   legalConsentOptions,
   properties_hs_status,
   properties_hs_form_id,
   properties_hs_editable,
   properties_hs_cloneable,
   properties_hs_deletable,
   properties_hs_folder_id,
   properties_hs_form_type,
   properties_hs_object_id,
   properties_hs_read_only,
   properties_hs_created_at,
   properties_hs_createdate,
   properties_hs_form_views,
   properties_hs_page_views,
   properties_hs_updated_at,
   properties_hs_all_team_ids,
   properties_hs_was_imported,
   properties_hubspot_team_id,
   properties_hs_all_owner_ids,
   properties_hs_embed_version,
   properties_hs_object_source,
   properties_hubspot_owner_id,
   properties_hs_shared_team_ids,
   properties_hs_shared_user_ids,
   properties_hs_form_submissions,
   properties_hs_lastmodifieddate,
   properties_hs_object_source_id,
   properties_hs_pop_up_cta_views,
   properties_hs_spam_submissions,
   properties_hs_form_interactions,
   properties_hs_merged_object_ids,
   properties_hs_created_by_user_id,
   properties_hs_updated_by_user_id,
   properties_hs_object_source_label,
   properties_hs_unique_creation_key,
   properties_hs_object_source_user_id,
   properties_hs_object_source_detail_1,
   properties_hs_object_source_detail_2,
   properties_hs_object_source_detail_3,
   properties_hs_user_ids_of_all_owners,
   properties_hs_all_accessible_team_ids,
   properties_hs_marketing_campaign_guid,
   properties_hubspot_owner_assigneddate,
   properties_hs_all_assigned_business_unit_ids,
   properties_hs_form_submissions_per_form_view,
   properties_hs_form_submissions_per_page_view,
   properties_hs_form_submissions_per_pop_up_cta_view,
   properties_hs_form_submissions_per_form_interaction,
   properties_hs_user_ids_of_all_notification_followers,
   properties_hs_user_ids_of_all_notification_unfollowers,
   {{ dbt_utils.surrogate_key([
     'id',
    'name',
    'archived',
    'formType',
    'createdAt',
    'deletedAt',
    'updatedAt',
    'properties_hs_name',
    'properties_hs_status',
    'properties_hs_form_id',
    'properties_hs_editable',
    'properties_hs_cloneable',
    'properties_hs_deletable',
    'properties_hs_form_type',
    'properties_hs_read_only',
    'properties_hs_created_at',
    'properties_hs_createdate',
    'properties_hs_updated_at',
    'properties_hs_all_team_ids',
    'properties_hs_was_imported',
    'properties_hubspot_team_id',
    'properties_hs_all_owner_ids',
    'properties_hs_embed_version',
    'properties_hs_object_source',
    'properties_hubspot_owner_id',
    'properties_hs_shared_team_ids',
    'properties_hs_shared_user_ids',
    'properties_hs_lastmodifieddate',
    'properties_hs_object_source_id',
    'properties_hs_merged_object_ids',
    'properties_hs_object_source_label',
    'properties_hs_unique_creation_key',
    'properties_hs_object_source_detail_1',
    'properties_hs_object_source_detail_2',
    'properties_hs_object_source_detail_3',
    'properties_hs_user_ids_of_all_owners',
    'properties_hs_all_accessible_team_ids',
    'properties_hs_marketing_campaign_guid',
    'properties_hubspot_owner_assigneddate',
    'properties_hs_all_assigned_business_unit_ids',
    'properties_hs_user_ids_of_all_notification_followers',
    'properties_hs_user_ids_of_all_notification_unfollowers'
    ]) }} as _airbyte_forms_hashid
from {{ source('cta', 'forms') }}