{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'products') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    _airbyte_generation_id,
    id,
    archived,
    createdAt,
    updatedAt,
    properties,
    properties_tax,
    properties_name,
    properties_price,
    properties_amount,
    properties_hs_sku,
    properties_hs_url,
    properties_discount,
    properties_quantity,
    properties_hs_folder,
    properties_hs_images,
    properties_createdate,
    properties_description,
    properties_hs_folder_id,
    properties_hs_object_id,
    properties_hs_read_only,
    properties_hs_createdate,
    properties_hs_folder_name,
    properties_hs_all_team_ids,
    properties_hs_product_type,
    properties_hs_was_imported,
    properties_hubspot_team_id,
    properties_hs_all_owner_ids,
    properties_hs_object_source,
    properties_hubspot_owner_id,
    properties_hs_shared_team_ids,
    properties_hs_shared_user_ids,
    properties_hs_lastmodifieddate,
    properties_hs_object_source_id,
    properties_hs_merged_object_ids,
    properties_hs_cost_of_goods_sold,
    properties_hs_created_by_user_id,
    properties_hs_updated_by_user_id,
    properties_hs_discount_percentage,
    properties_hs_object_source_label,
    properties_hs_unique_creation_key,
    properties_hs_object_source_user_id,
    properties_hs_avatar_filemanager_key,
    properties_hs_object_source_detail_1,
    properties_hs_object_source_detail_2,
    properties_hs_object_source_detail_3,
    properties_hs_user_ids_of_all_owners,
    properties_recurringbillingfrequency,
    properties_hs_all_accessible_team_ids,
    properties_hubspot_owner_assigneddate,
    properties_hs_recurring_billing_period,
    properties_hs_recurring_billing_start_date,
    properties_hs_all_assigned_business_unit_ids,
    properties_hs_user_ids_of_all_notification_followers,
    properties_hs_user_ids_of_all_notification_unfollowers,
   {{ dbt_utils.surrogate_key([
     'id',
    'archived',
    'createdAt',
    'updatedAt',
    'properties_name',
    'properties_hs_sku',
    'properties_hs_url',
    'properties_hs_folder',
    'properties_hs_images',
    'properties_createdate',
    'properties_description',
    'properties_hs_read_only',
    'properties_hs_createdate',
    'properties_hs_folder_name',
    'properties_hs_all_team_ids',
    'properties_hs_product_type',
    'properties_hs_was_imported',
    'properties_hubspot_team_id',
    'properties_hs_all_owner_ids',
    'properties_hs_object_source',
    'properties_hubspot_owner_id',
    'properties_hs_shared_team_ids',
    'properties_hs_shared_user_ids',
    'properties_hs_lastmodifieddate',
    'properties_hs_object_source_id',
    'properties_hs_merged_object_ids',
    'properties_hs_object_source_label',
    'properties_hs_unique_creation_key',
    'properties_hs_avatar_filemanager_key',
    'properties_hs_object_source_detail_1',
    'properties_hs_object_source_detail_2',
    'properties_hs_object_source_detail_3',
    'properties_hs_user_ids_of_all_owners',
    'properties_recurringbillingfrequency',
    'properties_hs_all_accessible_team_ids',
    'properties_hubspot_owner_assigneddate',
    'properties_hs_recurring_billing_period',
    'properties_hs_recurring_billing_start_date',
    'properties_hs_all_assigned_business_unit_ids',
    'properties_hs_user_ids_of_all_notification_followers',
    'properties_hs_user_ids_of_all_notification_unfollowers'
    ]) }} as _airbyte_products_hashid
from {{ source('cta', 'products') }}
