version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables: 
    - name: content_group_report
    - name: conversions_report
    - name: daily_active_users
    - name: demographic_age_report
    - name: demographic_city_report
    - name: demographic_country_report
    - name: demographic_gender_report
    - name: demographic_interest_report
    - name: demographic_language_report
    - name: demographic_region_report
    - name: devices
    - name: ecommerce_purchases_item_brand_report
    - name: ecommerce_purchases_item_category_2_report
    - name: ecommerce_purchases_item_category_3_report
    - name: ecommerce_purchases_item_category_4_report
    - name: ecommerce_purchases_item_category_5_report
    - name: ecommerce_purchases_item_category_report
    - name: ecommerce_purchases_item_category_report_combined
    - name: ecommerce_purchases_item_id_report
    - name: ecommerce_purchases_item_name_report
    - name: events_report
    - name: four_weekly_active_users
    - name: locations
    - name: pages
    - name: pages_path_report
    - name: pages_title_and_screen_class_report
    - name: pages_title_and_screen_name_report
    - name: publisher_ads_ad_format_report
    - name: publisher_ads_ad_source_report
    - name: publisher_ads_ad_unit_report
    - name: publisher_ads_page_path_report
    - name: tech_app_version_report
    - name: tech_browser_report
    - name: tech_device_category_report
    - name: tech_device_model_report
    - name: tech_operating_system_report
    - name: tech_os_with_version_report
    - name: tech_platform_device_category_report
    - name: tech_platform_report
    - name: tech_screen_resolution_report
    - name: traffic_acquisition_session_campaign_report
    - name: traffic_acquisition_session_default_channel_grouping_report
    - name: traffic_acquisition_session_medium_report
    - name: traffic_acquisition_session_source_medium_report
    - name: traffic_acquisition_session_source_platform_report
    - name: traffic_acquisition_session_source_report
    - name: traffic_sources
    - name: user_acquisition_first_user_campaign_report
    - name: user_acquisition_first_user_google_ads_ad_group_name_report
    - name: user_acquisition_first_user_google_ads_ad_network_type_report
    - name: user_acquisition_first_user_medium_report
    - name: user_acquisition_first_user_source_medium_report
    - name: user_acquisition_first_user_source_platform_report
    - name: user_acquisition_first_user_source_report
    - name: website_overview
    - name: weekly_active_users
    - name: weekly_events_report
  
    - name: content_group_report_base
    - name: conversions_report_base
    - name: daily_active_users_base
    - name: demographic_age_report_base
    - name: demographic_city_report_base
    - name: demographic_country_report_base
    - name: demographic_gender_report_base
    - name: demographic_interest_report_base
    - name: demographic_language_report_base
    - name: demographic_region_report_base
    - name: devices_base
    - name: ecommerce_purchases_item_brand_report_base
    - name: ecommerce_purchases_item_category_2_report_base
    - name: ecommerce_purchases_item_category_3_report_base
    - name: ecommerce_purchases_item_category_4_report_base
    - name: ecommerce_purchases_item_category_5_report_base
    - name: ecommerce_purchases_item_category_report_base
    - name: ecommerce_purchases_item_category_report_combined_base
    - name: ecommerce_purchases_item_id_report_base
    - name: ecommerce_purchases_item_name_report_base
    - name: events_report_base
    - name: four_weekly_active_users_base
    - name: locations_base
    - name: pages_base
    - name: pages_path_report_base
    - name: pages_title_and_screen_class_report_base
    - name: pages_title_and_screen_name_report_base
    - name: publisher_ads_ad_format_report_base
    - name: publisher_ads_ad_source_report_base
    - name: publisher_ads_ad_unit_report_base
    - name: publisher_ads_page_path_report_base
    - name: tech_app_version_report_base
    - name: tech_browser_report_base
    - name: tech_device_category_report_base
    - name: tech_device_model_report_base
    - name: tech_operating_system_report_base
    - name: tech_os_with_version_report_base
    - name: tech_platform_device_category_report_base
    - name: tech_platform_report_base
    - name: tech_screen_resolution_report_base
    - name: traffic_acquisition_session_campaign_report_base
    - name: traffic_acquisition_session_default_channel_grouping_report_base
    - name: traffic_acquisition_session_medium_report_base
    - name: traffic_acquisition_session_source_medium_report_base
    - name: traffic_acquisition_session_source_platform_report_base
    - name: traffic_acquisition_session_source_report_base
    - name: traffic_sources_base
    - name: user_acquisition_first_user_campaign_report_base
    - name: user_acquisition_first_user_google_ads_ad_group_name_report_base
    - name: user_acquisition_first_user_google_ads_ad_network_type_report_base
    - name: user_acquisition_first_user_medium_report_base
    - name: user_acquisition_first_user_source_medium_report_base
    - name: user_acquisition_first_user_source_platform_report_base
    - name: user_acquisition_first_user_source_report_base
    - name: website_overview_base
    - name: weekly_active_users_base
    - name: weekly_events_report_base