---
version: 2
sources:
  - name: cta
    database: "{{ env_var('CTA_PROJECT_ID') }}"
    schema: "{{ env_var('CTA_DATASET_ID') }}"
    tables:
      - name: campaign_insights
      - name: campaigns
      - name: campaign_insights_base
      - name: campaigns_base
