{% set raw_table = env_var("CTA_DATASET_ID") ~ "_airbyte_raw_event_campaigns" %}

{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = "_airbyte_raw_id"
) }}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ source('cta_raw', raw_table) }}
select
    {{ json_extract_scalar('_airbyte_data', ['id'], ['id']) }} as id,
    {{ json_extract_scalar('_airbyte_data', ['uuid'], ['uuid']) }} as uuid,
    {{ json_extract_scalar('_airbyte_data', ['stats'], ['stats']) }} as stats,
    {{ json_extract_scalar('_airbyte_data', ['title'], ['title']) }} as title,
    {{ json_extract_scalar('_airbyte_data', ['hidden'], ['hidden']) }} as hidden,
    {{ json_extract_scalar('_airbyte_data', ['status'], ['status']) }} as status,
    {{ json_extract_scalar('_airbyte_data', ['user_id'], ['user_id']) }} as user_id,
    {{ json_extract_scalar('_airbyte_data', ['group_id'], ['group_id']) }} as group_id,
    {{ json_extract_scalar('_airbyte_data', ['language'], ['language']) }} as language,
    {{ json_extract_scalar('_airbyte_data', ['tag_list'], ['tag_list']) }} as tag_list,
    {{ json_extract_scalar('_airbyte_data', ['permalink'], ['permalink']) }} as permalink,
    {{ json_extract_scalar('_airbyte_data', ['show_goal'], ['show_goal']) }} as show_goal,
    {{ json_extract_scalar('_airbyte_data', ['created_at'], ['created_at']) }} as created_at,
    {{ json_extract_scalar('_airbyte_data', ['discussion'], ['discussion']) }} as discussion,
    {{ json_extract_scalar('_airbyte_data', ['events_csv'], ['events_csv']) }} as events_csv,
    {{ json_extract_scalar('_airbyte_data', ['host_pitch'], ['host_pitch']) }} as host_pitch,
    {{ json_extract_scalar('_airbyte_data', ['updated_at'], ['updated_at']) }} as updated_at,
    {{ json_extract_scalar('_airbyte_data', ['browser_url'], ['browser_url']) }} as browser_url,
    {{ json_extract_scalar('_airbyte_data', ['custom_html'], ['custom_html']) }} as custom_html,
    {{ json_extract_scalar('_airbyte_data', ['default_from'], ['default_from']) }} as default_from,
    {{ json_extract_scalar('_airbyte_data', ['csv_file_name'], ['csv_file_name']) }} as csv_file_name,
    {{ json_extract_scalar('_airbyte_data', ['csv_file_size'], ['csv_file_size']) }} as csv_file_size,
    {{ json_extract_scalar('_airbyte_data', ['default_email'], ['default_email']) }} as default_email,
    {{ json_extract_scalar('_airbyte_data', ['first_publish'], ['first_publish']) }} as first_publish,
    {{ json_extract_scalar('_airbyte_data', ['notifications'], ['notifications']) }} as notifications,
    {{ json_extract_scalar('_airbyte_data', ['attendee_pitch'], ['attendee_pitch']) }} as attendee_pitch,
    {{ json_extract_scalar('_airbyte_data', ['csv_updated_at'], ['csv_updated_at']) }} as csv_updated_at,
    {{ json_extract_scalar('_airbyte_data', ['default_message'], ['default_message']) }} as default_message,
    {{ json_extract_scalar('_airbyte_data', ['default_subject'], ['default_subject']) }} as default_subject,
    {{ json_extract_scalar('_airbyte_data', ['first_permalink'], ['first_permalink']) }} as first_permalink,
    {{ json_extract_scalar('_airbyte_data', ['hosting_options'], ['hosting_options']) }} as hosting_options,
    {{ json_extract_scalar('_airbyte_data', ['photo_file_name'], ['photo_file_name']) }} as photo_file_name,
    {{ json_extract_scalar('_airbyte_data', ['photo_file_size'], ['photo_file_size']) }} as photo_file_size,
    {{ json_extract_scalar('_airbyte_data', ['csv_content_type'], ['csv_content_type']) }} as csv_content_type,
    {{ json_extract_scalar('_airbyte_data', ['default_reply_to'], ['default_reply_to']) }} as default_reply_to,
    {{ json_extract_scalar('_airbyte_data', ['host_page_status'], ['host_page_status']) }} as host_page_status,
    {{ json_extract_scalar('_airbyte_data', ['event_description'], ['event_description']) }} as event_description,
    {{ json_extract_scalar('_airbyte_data', ['host_instructions'], ['host_instructions']) }} as host_instructions,
    {{ json_extract_scalar('_airbyte_data', ['image_attribution'], ['image_attribution']) }} as image_attribution,
    {{ json_extract_scalar('_airbyte_data', ['thank_you_subhead'], ['thank_you_subhead']) }} as thank_you_subhead,
    {{ json_extract_scalar('_airbyte_data', ['originating_system'], ['originating_system']) }} as originating_system,
    {{ json_extract_scalar('_airbyte_data', ['photo_content_type'], ['photo_content_type']) }} as photo_content_type,
    {{ json_extract_scalar('_airbyte_data', ['thank_you_headline'], ['thank_you_headline']) }} as thank_you_headline,
    {{ json_extract_scalar('_airbyte_data', ['default_direct_link'], ['default_direct_link']) }} as default_direct_link,
    {{ json_extract_scalar('_airbyte_data', ['default_email_share'], ['default_email_share']) }} as default_email_share,
    {{ json_extract_scalar('_airbyte_data', ['form_builder_output'], ['form_builder_output']) }} as form_builder_output,
    {{ json_extract_scalar('_airbyte_data', ['administrative_title'], ['administrative_title']) }} as administrative_title,
    {{ json_extract_scalar('_airbyte_data', ['attendee_page_status'], ['attendee_page_status']) }} as attendee_page_status,
    {{ json_extract_scalar('_airbyte_data', ['default_redirect_url'], ['default_redirect_url']) }} as default_redirect_url,
    {{ json_extract_scalar('_airbyte_data', ['events_csv_file_name'], ['events_csv_file_name']) }} as events_csv_file_name,
    {{ json_extract_scalar('_airbyte_data', ['events_csv_file_size'], ['events_csv_file_size']) }} as events_csv_file_size,
    {{ json_extract_scalar('_airbyte_data', ['attendee_instructions'], ['attendee_instructions']) }} as attendee_instructions,
    {{ json_extract_scalar('_airbyte_data', ['default_facebook_link'], ['default_facebook_link']) }} as default_facebook_link,
    {{ json_extract_scalar('_airbyte_data', ['default_reminder_from'], ['default_reminder_from']) }} as default_reminder_from,
    {{ json_extract_scalar('_airbyte_data', ['default_twitter_share'], ['default_twitter_share']) }} as default_twitter_share,
    {{ json_extract_scalar('_airbyte_data', ['events_csv_updated_at'], ['events_csv_updated_at']) }} as events_csv_updated_at,
    {{ json_extract_scalar('_airbyte_data', ['default_email_response'], ['default_email_response']) }} as default_email_response,
    {{ json_extract_scalar('_airbyte_data', ['default_facebook_share'], ['default_facebook_share']) }} as default_facebook_share,
    {{ json_extract_scalar('_airbyte_data', ['default_facebook_title'], ['default_facebook_title']) }} as default_facebook_title,
    {{ json_extract_scalar('_airbyte_data', ['events_csv_content_type'], ['events_csv_content_type']) }} as events_csv_content_type,
    {{ json_extract_scalar('_airbyte_data', ['default_reminder_message'], ['default_reminder_message']) }} as default_reminder_message,
    {{ json_extract_scalar('_airbyte_data', ['default_reminder_subject'], ['default_reminder_subject']) }} as default_reminder_subject,
    {{ json_extract_scalar('_airbyte_data', ['form_builder_output_json'], ['form_builder_output_json']) }} as form_builder_output_json,
    {{ json_extract_scalar('_airbyte_data', ['default_email_template_id'], ['default_email_template_id']) }} as default_email_template_id,
    {{ json_extract_scalar('_airbyte_data', ['default_reminder_reply_to'], ['default_reminder_reply_to']) }} as default_reminder_reply_to,
    {{ json_extract_scalar('_airbyte_data', ['default_auto_response_email'], ['default_auto_response_email']) }} as default_auto_response_email,
    {{ json_extract_scalar('_airbyte_data', ['default_unpublished_redirect'], ['default_unpublished_redirect']) }} as default_unpublished_redirect,
    {{ json_extract_scalar('_airbyte_data', ['default_automatic_notifications'], ['default_automatic_notifications']) }} as default_automatic_notifications,
    {{ json_extract_scalar('_airbyte_data', ['default_facebook_image_file_name'], ['default_facebook_image_file_name']) }} as default_facebook_image_file_name,
    {{ json_extract_scalar('_airbyte_data', ['default_facebook_image_file_size'], ['default_facebook_image_file_size']) }} as default_facebook_image_file_size,
    {{ json_extract_scalar('_airbyte_data', ['default_facebook_image_content_type'], ['default_facebook_image_content_type']) }} as default_facebook_image_content_type,
    {{ json_extract_scalar('_airbyte_data', ['default_auto_response_email_template_id'], ['default_auto_response_email_template_id']) }} as default_auto_response_email_template_id,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ source('cta_raw', raw_table) }}
-- event_campaigns
where 1 = 1
