{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = "_airbyte_ab_id"
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('event_campaigns_ab1') }}
select
    cast(id as {{ dbt_utils.type_bigint() }}) as id,
    cast(uuid as {{ dbt_utils.type_string() }}) as uuid,
    cast(stats as {{ dbt_utils.type_string() }}) as stats,
    cast(title as {{ dbt_utils.type_string() }}) as title,
    cast(hidden as {{ dbt_utils.type_bigint() }}) as hidden,
    cast(status as {{ dbt_utils.type_bigint() }}) as status,
    cast(user_id as {{ dbt_utils.type_bigint() }}) as user_id,
    cast(group_id as {{ dbt_utils.type_bigint() }}) as group_id,
    cast(language as {{ dbt_utils.type_string() }}) as language,
    cast(tag_list as {{ dbt_utils.type_string() }}) as tag_list,
    cast(permalink as {{ dbt_utils.type_string() }}) as permalink,
    cast(show_goal as {{ dbt_utils.type_bigint() }}) as show_goal,
    cast(created_at as {{ dbt_utils.type_string() }}) as created_at,
    cast(discussion as {{ dbt_utils.type_bigint() }}) as discussion,
    cast(events_csv as {{ dbt_utils.type_string() }}) as events_csv,
    cast(host_pitch as {{ dbt_utils.type_string() }}) as host_pitch,
    cast(updated_at as {{ dbt_utils.type_string() }}) as updated_at,
    cast(browser_url as {{ dbt_utils.type_string() }}) as browser_url,
    cast(custom_html as {{ dbt_utils.type_string() }}) as custom_html,
    cast(default_from as {{ dbt_utils.type_string() }}) as default_from,
    cast(csv_file_name as {{ dbt_utils.type_string() }}) as csv_file_name,
    cast(csv_file_size as {{ dbt_utils.type_bigint() }}) as csv_file_size,
    cast(default_email as {{ dbt_utils.type_string() }}) as default_email,
    cast(first_publish as {{ dbt_utils.type_bigint() }}) as first_publish,
    cast(notifications as {{ dbt_utils.type_bigint() }}) as notifications,
    cast(attendee_pitch as {{ dbt_utils.type_string() }}) as attendee_pitch,
    cast(csv_updated_at as {{ dbt_utils.type_string() }}) as csv_updated_at,
    cast(default_message as {{ dbt_utils.type_string() }}) as default_message,
    cast(default_subject as {{ dbt_utils.type_string() }}) as default_subject,
    cast(first_permalink as {{ dbt_utils.type_string() }}) as first_permalink,
    cast(hosting_options as {{ dbt_utils.type_string() }}) as hosting_options,
    cast(photo_file_name as {{ dbt_utils.type_string() }}) as photo_file_name,
    cast(photo_file_size as {{ dbt_utils.type_bigint() }}) as photo_file_size,
    cast(csv_content_type as {{ dbt_utils.type_string() }}) as csv_content_type,
    cast(default_reply_to as {{ dbt_utils.type_string() }}) as default_reply_to,
    cast(host_page_status as {{ dbt_utils.type_bigint() }}) as host_page_status,
    cast(event_description as {{ dbt_utils.type_string() }}) as event_description,
    cast(host_instructions as {{ dbt_utils.type_string() }}) as host_instructions,
    cast(image_attribution as {{ dbt_utils.type_string() }}) as image_attribution,
    cast(thank_you_subhead as {{ dbt_utils.type_string() }}) as thank_you_subhead,
    cast(originating_system as {{ dbt_utils.type_string() }}) as originating_system,
    cast(photo_content_type as {{ dbt_utils.type_string() }}) as photo_content_type,
    cast(thank_you_headline as {{ dbt_utils.type_string() }}) as thank_you_headline,
    cast(default_direct_link as {{ dbt_utils.type_string() }}) as default_direct_link,
    cast(default_email_share as {{ dbt_utils.type_string() }}) as default_email_share,
    cast(form_builder_output as {{ dbt_utils.type_string() }}) as form_builder_output,
    cast(administrative_title as {{ dbt_utils.type_string() }}) as administrative_title,
    cast(attendee_page_status as {{ dbt_utils.type_string() }}) as attendee_page_status,
    cast(default_redirect_url as {{ dbt_utils.type_string() }}) as default_redirect_url,
    cast(events_csv_file_name as {{ dbt_utils.type_string() }}) as events_csv_file_name,
    cast(events_csv_file_size as {{ dbt_utils.type_string() }}) as events_csv_file_size,
    cast(attendee_instructions as {{ dbt_utils.type_string() }}) as attendee_instructions,
    cast(default_facebook_link as {{ dbt_utils.type_string() }}) as default_facebook_link,
    cast(default_reminder_from as {{ dbt_utils.type_string() }}) as default_reminder_from,
    cast(default_twitter_share as {{ dbt_utils.type_string() }}) as default_twitter_share,
    cast(events_csv_updated_at as {{ dbt_utils.type_string() }}) as events_csv_updated_at,
    cast(default_email_response as {{ dbt_utils.type_bigint() }}) as default_email_response,
    cast(default_facebook_share as {{ dbt_utils.type_string() }}) as default_facebook_share,
    cast(default_facebook_title as {{ dbt_utils.type_string() }}) as default_facebook_title,
    cast(events_csv_content_type as {{ dbt_utils.type_string() }}) as events_csv_content_type,
    cast(default_reminder_message as {{ dbt_utils.type_string() }}) as default_reminder_message,
    cast(default_reminder_subject as {{ dbt_utils.type_string() }}) as default_reminder_subject,
    cast(form_builder_output_json as {{ dbt_utils.type_string() }}) as form_builder_output_json,
    cast(default_email_template_id as {{ dbt_utils.type_bigint() }}) as default_email_template_id,
    cast(default_reminder_reply_to as {{ dbt_utils.type_string() }}) as default_reminder_reply_to,
    cast(default_auto_response_email as {{ dbt_utils.type_string() }}) as default_auto_response_email,
    cast(default_unpublished_redirect as {{ dbt_utils.type_string() }}) as default_unpublished_redirect,
    cast(default_automatic_notifications as {{ dbt_utils.type_bigint() }}) as default_automatic_notifications,
    cast(default_facebook_image_file_name as {{ dbt_utils.type_string() }}) as default_facebook_image_file_name,
    cast(default_facebook_image_file_size as {{ dbt_utils.type_bigint() }}) as default_facebook_image_file_size,
    cast(default_facebook_image_content_type as {{ dbt_utils.type_string() }}) as default_facebook_image_content_type,
    cast(default_auto_response_email_template_id as {{ dbt_utils.type_bigint() }}) as default_auto_response_email_template_id,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('event_campaigns_ab1') }}
-- event_campaigns
where 1 = 1
