{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = "_airbyte_raw_id"
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('groups_ab1') }}
select
    cast(id as {{ dbt_utils.type_bigint() }}) as id,
    cast(city as {{ dbt_utils.type_string() }}) as city,
    cast(name as {{ dbt_utils.type_string() }}) as name,
    cast(email as {{ dbt_utils.type_string() }}) as email,
    cast(state as {{ dbt_utils.type_string() }}) as state,
    cast(stats as {{ dbt_utils.type_string() }}) as stats,
    cast(status as {{ dbt_utils.type_bigint() }}) as status,
    cast(street as {{ dbt_utils.type_string() }}) as street,
    cast(api_key as {{ dbt_utils.type_string() }}) as api_key,
    cast(country as {{ dbt_utils.type_string() }}) as country,
    cast(signoff as {{ dbt_utils.type_string() }}) as signoff,
    cast(user_id as {{ dbt_utils.type_bigint() }}) as user_id,
    cast(language as {{ dbt_utils.type_string() }}) as language,
    cast(latitude as {{ dbt_utils.type_float() }}) as latitude,
    cast(zip_code as {{ dbt_utils.type_string() }}) as zip_code,
    cast(longitude as {{ dbt_utils.type_float() }}) as longitude,
    cast(parent_id as {{ dbt_utils.type_bigint() }}) as parent_id,
    cast(permalink as {{ dbt_utils.type_string() }}) as permalink,
    cast(sms_stats as {{ dbt_utils.type_string() }}) as sms_stats,
    cast(auto_merge as {{ dbt_utils.type_bigint() }}) as auto_merge,
    cast(created_at as {{ dbt_utils.type_string() }}) as created_at,
    cast(discussion as {{ dbt_utils.type_bigint() }}) as discussion,
    cast(email_from as {{ dbt_utils.type_string() }}) as email_from,
    cast(network_id as {{ dbt_utils.type_bigint() }}) as network_id,
    cast(updated_at as {{ dbt_utils.type_string() }}) as updated_at,
    cast(sms_enabled as {{ dbt_utils.type_bigint() }}) as sms_enabled,
    cast(users_count as {{ dbt_utils.type_bigint() }}) as users_count,
    cast(applications as {{ dbt_utils.type_bigint() }}) as applications,
    cast(ip_pool_name as {{ dbt_utils.type_string() }}) as ip_pool_name,
    cast(localization as {{ dbt_utils.type_string() }}) as localization,
    cast(csv_file_name as {{ dbt_utils.type_string() }}) as csv_file_name,
    cast(csv_file_size as {{ dbt_utils.type_bigint() }}) as csv_file_size,
    cast(email_replyto as {{ dbt_utils.type_string() }}) as email_replyto,
    cast(first_publish as {{ dbt_utils.type_bigint() }}) as first_publish,
    cast(twilio_active as {{ dbt_utils.type_bigint() }}) as twilio_active,
    cast(csv_updated_at as {{ dbt_utils.type_string() }}) as csv_updated_at,
    cast(additional_text as {{ dbt_utils.type_string() }}) as additional_text,
    cast(adhoc_group_ids as {{ dbt_utils.type_string() }}) as adhoc_group_ids,
    cast(default_country as {{ dbt_utils.type_string() }}) as default_country,
    cast(first_permalink as {{ dbt_utils.type_string() }}) as first_permalink,
    cast(photo_file_name as {{ dbt_utils.type_string() }}) as photo_file_name,
    cast(photo_file_size as {{ dbt_utils.type_bigint() }}) as photo_file_size,
    cast(cancel_donations as {{ dbt_utils.type_bigint() }}) as cancel_donations,
    cast(csv_content_type as {{ dbt_utils.type_string() }}) as csv_content_type,
    cast(description_text as {{ dbt_utils.type_string() }}) as description_text,
    cast(campaigns_enabled as {{ dbt_utils.type_bigint() }}) as campaigns_enabled,
    cast(default_report_id as {{ dbt_utils.type_bigint() }}) as default_report_id,
    cast(image_attribution as {{ dbt_utils.type_string() }}) as image_attribution,
    cast(notify_mass_email as {{ dbt_utils.type_bigint() }}) as notify_mass_email,
    cast(redirects_enabled as {{ dbt_utils.type_bigint() }}) as redirects_enabled,
    cast(photo_content_type as {{ dbt_utils.type_string() }}) as photo_content_type,
    cast(flow_up_sms_opt_ins as {{ dbt_utils.type_bigint() }}) as flow_up_sms_opt_ins,
    cast(twilio_help_message as {{ dbt_utils.type_string() }}) as twilio_help_message,
    cast(use_additional_text as {{ dbt_utils.type_bigint() }}) as use_additional_text,
    cast(administrative_title as {{ dbt_utils.type_string() }}) as administrative_title,
    cast(donation_failed_email as {{ dbt_utils.type_string() }}) as donation_failed_email,
    cast(mass_emails_to_notify as {{ dbt_utils.type_string() }}) as mass_emails_to_notify,
    cast(network_csv_file_name as {{ dbt_utils.type_string() }}) as network_csv_file_name,
    cast(network_csv_file_size as {{ dbt_utils.type_bigint() }}) as network_csv_file_size,
    cast(default_twitter_handle as {{ dbt_utils.type_string() }}) as default_twitter_handle,
    cast(donation_receipt_email as {{ dbt_utils.type_string() }}) as donation_receipt_email,
    cast(network_csv_updated_at as {{ dbt_utils.type_string() }}) as network_csv_updated_at,
    cast(salesforce_last_update as {{ dbt_utils.type_string() }}) as salesforce_last_update,
    cast(current_page_wrapper_id as {{ dbt_utils.type_bigint() }}) as current_page_wrapper_id,
    cast(salesforce_sync_enabled as {{ dbt_utils.type_bigint() }}) as salesforce_sync_enabled,
    cast(use_affirmative_opt_ins as {{ dbt_utils.type_bigint() }}) as use_affirmative_opt_ins,
    cast(donations_without_emails as {{ dbt_utils.type_bigint() }}) as donations_without_emails,
    cast(network_csv_content_type as {{ dbt_utils.type_string() }}) as network_csv_content_type,
    cast(salesforce_custom_fields as {{ dbt_utils.type_string() }}) as salesforce_custom_fields,
    cast(current_email_template_id as {{ dbt_utils.type_bigint() }}) as current_email_template_id,
    cast(email_stats_csv_file_name as {{ dbt_utils.type_string() }}) as email_stats_csv_file_name,
    cast(email_stats_csv_file_size as {{ dbt_utils.type_bigint() }}) as email_stats_csv_file_size,
    cast(additional_sms_opt_in_text as {{ dbt_utils.type_string() }}) as additional_sms_opt_in_text,
    cast(email_stats_csv_updated_at as {{ dbt_utils.type_string() }}) as email_stats_csv_updated_at,
    cast(salesforce_sync_successful as {{ dbt_utils.type_bigint() }}) as salesforce_sync_successful,
    cast(twilio_unsubscribe_message as {{ dbt_utils.type_string() }}) as twilio_unsubscribe_message,
    cast(default_targeting_exclude_id as {{ dbt_utils.type_bigint() }}) as default_targeting_exclude_id,
    cast(default_targeting_include_id as {{ dbt_utils.type_bigint() }}) as default_targeting_include_id,
    cast(email_stats_csv_content_type as {{ dbt_utils.type_string() }}) as email_stats_csv_content_type,
    cast(cancel_donations_instructions as {{ dbt_utils.type_string() }}) as cancel_donations_instructions,
    cast(default_facebook_image_file_name as {{ dbt_utils.type_string() }}) as default_facebook_image_file_name,
    cast(default_facebook_image_file_size as {{ dbt_utils.type_bigint() }}) as default_facebook_image_file_size,
    cast(default_facebook_image_updated_at as {{ dbt_utils.type_string() }}) as default_facebook_image_updated_at,
    cast(mobile_message_stats_csv_file_name as {{ dbt_utils.type_string() }}) as mobile_message_stats_csv_file_name,
    cast(mobile_message_stats_csv_file_size as {{ dbt_utils.type_bigint() }}) as mobile_message_stats_csv_file_size,
    cast(default_facebook_image_content_type as {{ dbt_utils.type_string() }}) as default_facebook_image_content_type,
    cast(mobile_message_stats_csv_updated_at as {{ dbt_utils.type_string() }}) as mobile_message_stats_csv_updated_at,
    cast(mobile_message_stats_csv_content_type as {{ dbt_utils.type_string() }}) as mobile_message_stats_csv_content_type,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('groups_ab1') }}
-- groups
where 1 = 1
