{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ source('cta', '_airbyte_raw_petitions') }}
select
    {{ json_extract_scalar('_airbyte_data', ['id'], ['id']) }} as id,
    {{ json_extract_scalar('_airbyte_data', ['uuid'], ['uuid']) }} as uuid,
    {{ json_extract_scalar('_airbyte_data', ['stats'], ['stats']) }} as stats,
    {{ json_extract_scalar('_airbyte_data', ['title'], ['title']) }} as title,
    {{ json_extract_scalar('_airbyte_data', ['hidden'], ['hidden']) }} as hidden,
    {{ json_extract_scalar('_airbyte_data', ['status'], ['status']) }} as status,
    {{ json_extract_scalar('_airbyte_data', ['user_id'], ['user_id']) }} as user_id,
    {{ json_extract_scalar('_airbyte_data', ['group_id'], ['group_id']) }} as group_id,
    {{ json_extract_scalar('_airbyte_data', ['language'], ['language']) }} as language,
    {{ json_extract_scalar('_airbyte_data', ['tag_list'], ['tag_list']) }} as tag_list,
    {{ json_extract_scalar('_airbyte_data', ['permalink'], ['permalink']) }} as permalink,
    {{ json_extract_scalar('_airbyte_data', ['share_url'], ['share_url']) }} as share_url,
    {{ json_extract_scalar('_airbyte_data', ['show_goal'], ['show_goal']) }} as show_goal,
    {{ json_extract_scalar('_airbyte_data', ['created_at'], ['created_at']) }} as created_at,
    {{ json_extract_scalar('_airbyte_data', ['updated_at'], ['updated_at']) }} as updated_at,
    {{ json_extract_scalar('_airbyte_data', ['browser_url'], ['browser_url']) }} as browser_url,
    {{ json_extract_scalar('_airbyte_data', ['target_name'], ['target_name']) }} as target_name,
    {{ json_extract_scalar('_airbyte_data', ['instructions'], ['instructions']) }} as instructions,
    {{ json_extract_scalar('_airbyte_data', ['redirect_url'], ['redirect_url']) }} as redirect_url,
    {{ json_extract_scalar('_airbyte_data', ['target_title'], ['target_title']) }} as target_title,
    {{ json_extract_scalar('_airbyte_data', ['csv_file_name'], ['csv_file_name']) }} as csv_file_name,
    {{ json_extract_scalar('_airbyte_data', ['csv_file_size'], ['csv_file_size']) }} as csv_file_size,
    {{ json_extract_scalar('_airbyte_data', ['custom_fields'], ['custom_fields']) }} as custom_fields,
    {{ json_extract_scalar('_airbyte_data', ['first_publish'], ['first_publish']) }} as first_publish,
    {{ json_extract_scalar('_airbyte_data', ['pdf_file_name'], ['pdf_file_name']) }} as pdf_file_name,
    {{ json_extract_scalar('_airbyte_data', ['pdf_file_size'], ['pdf_file_size']) }} as pdf_file_size,
    {{ json_extract_scalar('_airbyte_data', ['salesforce_id'], ['salesforce_id']) }} as salesforce_id,
    {{ json_extract_scalar('_airbyte_data', ['csv_updated_at'], ['csv_updated_at']) }} as csv_updated_at,
    {{ json_extract_scalar('_airbyte_data', ['pdf_updated_at'], ['pdf_updated_at']) }} as pdf_updated_at,
    {{ json_extract_scalar('_airbyte_data', ['signature_goal'], ['signature_goal']) }} as signature_goal,
    {{ json_extract_scalar('_airbyte_data', ['display_creator'], ['display_creator']) }} as display_creator,
    {{ json_extract_scalar('_airbyte_data', ['first_permalink'], ['first_permalink']) }} as first_permalink,
    {{ json_extract_scalar('_airbyte_data', ['photo_file_name'], ['photo_file_name']) }} as photo_file_name,
    {{ json_extract_scalar('_airbyte_data', ['photo_file_size'], ['photo_file_size']) }} as photo_file_size,
    {{ json_extract_scalar('_airbyte_data', ['signature_count'], ['signature_count']) }} as signature_count,
    {{ json_extract_scalar('_airbyte_data', ['csv_content_type'], ['csv_content_type']) }} as csv_content_type,
    {{ json_extract_scalar('_airbyte_data', ['description_info'], ['description_info']) }} as description_info,
    {{ json_extract_scalar('_airbyte_data', ['description_text'], ['description_text']) }} as description_text,
    {{ json_extract_scalar('_airbyte_data', ['pdf_content_type'], ['pdf_content_type']) }} as pdf_content_type,
    {{ json_extract_scalar('_airbyte_data', ['zip_code_present'], ['zip_code_present']) }} as zip_code_present,
    {{ json_extract_scalar('_airbyte_data', ['image_attribution'], ['image_attribution']) }} as image_attribution,
    {{ json_extract_scalar('_airbyte_data', ['last_name_present'], ['last_name_present']) }} as last_name_present,
    {{ json_extract_scalar('_airbyte_data', ['thank_you_subhead'], ['thank_you_subhead']) }} as thank_you_subhead,
    {{ json_extract_scalar('_airbyte_data', ['zip_code_required'], ['zip_code_required']) }} as zip_code_required,
    {{ json_extract_scalar('_airbyte_data', ['first_name_present'], ['first_name_present']) }} as first_name_present,
    {{ json_extract_scalar('_airbyte_data', ['last_name_required'], ['last_name_required']) }} as last_name_required,
    {{ json_extract_scalar('_airbyte_data', ['originating_system'], ['originating_system']) }} as originating_system,
    {{ json_extract_scalar('_airbyte_data', ['photo_content_type'], ['photo_content_type']) }} as photo_content_type,
    {{ json_extract_scalar('_airbyte_data', ['thank_you_headline'], ['thank_you_headline']) }} as thank_you_headline,
    {{ json_extract_scalar('_airbyte_data', ['first_name_required'], ['first_name_required']) }} as first_name_required,
    {{ json_extract_scalar('_airbyte_data', ['form_builder_output'], ['form_builder_output']) }} as form_builder_output,
    {{ json_extract_scalar('_airbyte_data', ['submit_button_title'], ['submit_button_title']) }} as submit_button_title,
    {{ json_extract_scalar('_airbyte_data', ['target_organization'], ['target_organization']) }} as target_organization,
    {{ json_extract_scalar('_airbyte_data', ['administrative_title'], ['administrative_title']) }} as administrative_title,
    {{ json_extract_scalar('_airbyte_data', ['suppress_autoresponse'], ['suppress_autoresponse']) }} as suppress_autoresponse,
    {{ json_extract_scalar('_airbyte_data', ['display_sharing_options'], ['display_sharing_options']) }} as display_sharing_options,
    {{ json_extract_scalar('_airbyte_data', ['form_builder_output_json'], ['form_builder_output_json']) }} as form_builder_output_json,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ source('cta', '_airbyte_raw_petitions') }} as table_alias
-- petitions
where 1 = 1

