{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = "_airbyte_ab_id"
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('petitions_ab2') }}
select
    {{ dbt_utils.generate_surrogate_key([
        'id',
        'uuid',
        'stats',
        'title',
        'hidden',
        'status',
        'user_id',
        'group_id',
        'language',
        'tag_list',
        'permalink',
        'share_url',
        'show_goal',
        'created_at',
        'updated_at',
        'browser_url',
        'target_name',
        'instructions',
        'redirect_url',
        'target_title',
        'csv_file_name',
        'csv_file_size',
        'custom_fields',
        'first_publish',
        'pdf_file_name',
        'pdf_file_size',
        'salesforce_id',
        'csv_updated_at',
        'pdf_updated_at',
        'signature_goal',
        'display_creator',
        'first_permalink',
        'photo_file_name',
        'photo_file_size',
        'signature_count',
        'csv_content_type',
        'description_info',
        'description_text',
        'pdf_content_type',
        'zip_code_present',
        'image_attribution',
        'last_name_present',
        'thank_you_subhead',
        'zip_code_required',
        'first_name_present',
        'last_name_required',
        'originating_system',
        'photo_content_type',
        'thank_you_headline',
        'first_name_required',
        'form_builder_output',
        'submit_button_title',
        'target_organization',
        'administrative_title',
        'suppress_autoresponse',
        'display_sharing_options',
        'form_builder_output_json',
    ]) }} as _airbyte_petitions_hashid,
    tmp.*
from {{ ref('petitions_ab2') }} as tmp
-- petitions
where 1 = 1
