{{ config(
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = 'id'
) }}
-- depends_on: {{ source('cta', 'surveys') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    _airbyte_generation_id,
    id,
    uuid,
    stats,
    title,
    hidden,
    status,
    user_id,
    group_id,
    language,
    tag_list,
    permalink,
    share_url,
    show_goal,
    created_at,
    updated_at,
    browser_url,
    instructions,
    redirect_url,
    csv_file_name,
    csv_file_size,
    custom_fields,
    first_publish,
    response_goal,
    salesforce_id,
    csv_updated_at,
    response_count,
    survey_heading,
    display_creator,
    first_permalink,
    photo_file_name,
    photo_file_size,
    csv_content_type,
    description_info,
    description_text,
    zip_code_present,
    image_attribution,
    last_name_present,
    thank_you_subhead,
    zip_code_required,
    first_name_present,
    last_name_required,
    originating_system,
    photo_content_type,
    thank_you_headline,
    first_name_required,
    form_builder_output,
    submit_button_title,
    administrative_title,
    suppress_autoresponse,
    display_sharing_options,
    form_builder_output_json
from {{ source('cta', 'surveys') }}
