version: 2
sources:
- name: cta
  quoting:
    database: true
    schema: true
    identifier: false
  database: "{{env_var('CTA_PROJECT_ID') }}"
  schema: airbyte_internal
  tables:
  - name: _airbyte_raw_page
    quoting:
      identifier: true
  - name: _airbyte_raw_page_insights
    quoting:
      identifier: true
  - name: _airbyte_raw_post
    quoting:
      identifier: true
  - name: _airbyte_raw_post_insights
    quoting:
      identifier: true
