{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = 'id',
    tags = [ "top-level" ]
) }}

-- Final base SQL model
-- depends_on: {{ ref('registration_forms_ab3') }}
select
    distance_from_location,
    metadata,
    eligible_voting_age,
    county,
    social_security,
    uuid,
    pledge_card_data,
    score,
    identification,
    voting_state,
    id,
    state_id,
    longitude,
    person_id,
    ovr_status,
    hard_copy_collected,
    mailing_street_address_two,
    completed,
    created_by_user_id,
    registration_date,
    secondary_identification,
    voting_city,
    phone_number,
    form_number,
    party,
    contacted_voter,
    mailing_street_address_one,
    gender,
    ethnicity,
    signature,
    date_of_birth,
    latitude,
    delivery_id,
    extras,
    created_at,
    voting_street_address_two,
    voting_zipcode,
    mailing_zipcode,
    registration_type,
    redacted_fields,
    van_id,
    name_prefix,
    updated_at,
    shift_id,
    first_name,
    online_registration,
    por_data,
    mailing_city,
    mailing_state,
    voting_street_address_one,
    name_suffix,
    twilio_match_data,
    last_name,
    middle_name,
    us_citizen,
    precinct,
    email_address,
    smarty_streets_match_data,
    scan_id,
    attempted,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at,
    _airbyte_registration_forms_hashid
from {{ ref('registration_forms_ab3') }}
-- registration_forms from {{ source('cta', '_airbyte_raw_registration_forms') }}

