{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id'
) }}
-- Final base SQL model
-- depends_on: {{ ref('account_native_ads_stats_ab3') }}
select
    ctr,
    cvr,
    imp,
    ltr,
    atos,
    conv,
    cost,
    SAFE_CAST(date as date) as date,
    ecpa,
    ecpc,
    ecpe,
    ecpm,
    ecpv,
    rcpc,
    rcpe,
    rcpm,
    roas,
    click,
    ecpcl,
    rcpcl,
    domain,
    ios_id,
    is_ios,
    profit,
    s_conv,
    channel,
    conv_ip,
    heading,
    revenue,
    tagline,
    vcomp_0,
    campaign,
    SAFE_CAST(end_date as timestamp) as end_date,
    SAFE_CAST(start_date as timestamp) as start_date,
    nativead,
    vcomp_25,
    vcomp_50,
    vcomp_75,
    vcomp_95,
    click_url,
    REGEXP_EXTRACT(click_url, r'utm_source=([^&]+)') as utm_source,
    REGEXP_EXTRACT(click_url, r'utm_medium=([^&]+)') as utm_medium,
    REGEXP_EXTRACT(click_url, r'utm_campaign=([^&]+)') as utm_campaign,
    REGEXP_EXTRACT(click_url, r'utm_term=([^&]+)') as utm_term,
    REGEXP_EXTRACT(click_url, r'utm_content=([^&]+)') as utm_content,
    creatives,
    line_item,
    page_time,
    uniq_conv,
    atos_units,
    conv_click,
    is_android,
    page_start,
    unique_imp as reach,
    vcomp_rate,
    campaign_id,
    engage_rate,
    full_domain,
    tp_cpc_cost,
    tp_cpm_cost,
    unique_conv,
    line_item_id,
    native_ad_id,
    view_percent,
    campaign_type,
    page_time_15s,
    native_ad_type,
    sub_advertiser,
    page_time_units,
    conv_imp_derived,
    conv_imp_time_avg,
    sub_advertiser_id,
    conv_click_time_avg,
    unique_imp_inverse_rate as frequency,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at,
    _airbyte_account_native_ads_stats_hashid
from {{ ref('account_native_ads_stats_ab3') }}
-- account_native_ads_stats from {{ source('cta', '_airbyte_raw_account_native_ads_stats') }}
where 1 = 1
{{ incremental_clause('_airbyte_emitted_at') }}

