version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables: 
    - name: core_action
    - name: core_actionfield
    - name: core_actionnotification
    - name: core_actionnotification_to_staff
    - name: core_alloweduserfield
    - name: core_callaction
    - name: core_callaction_checked
    - name: core_callaction_local_office_checked
    - name: core_callaction_targeted
    - name: core_campaignvolunteeraction
    - name: core_eventcreateaction
    - name: core_eventmoderateaction
    - name: core_eventsignupaction
    - name: core_eventvolunteeraction
    - name: core_location
    - name: core_lteaction
    - name: core_phone
    - name: core_reengagementlog
    - name: core_user
    - name: core_user_groups
    - name: core_user_page_tags
    - name: core_useragent
    - name: core_userdailysummary
    - name: core_userdivision
    - name: core_userfield
    - name: core_usergroup
    - name: core_usermerge
    - name: core_usermerge_users
    - name: core_userstaffnote
    - name: core_whipcountactioncalled
    - name: events_campaign
    - name: events_campaignvolunteer
    - name: events_customemail
    - name: events_customemailgroup
    - name: events_emailbodylog
    - name: events_emaillog
    - name: events_emaillog_to_users
    - name: events_event
    - name: events_eventfield
    - name: events_eventsignup
    - name: events_eventsignupfield
    - name: events_historicalevent
    - name: oneclick_storeduser
    - name: oneclick_use
    - name: spam_spamchecklog    
    - name: core_action_base 
    - name: core_actionfield_base 
    - name: core_actionnotification_base 
    - name: core_actionnotification_to_staff_base 
    - name: core_alloweduserfield_base 
    - name: core_callaction_base 
    - name: core_callaction_checked_base 
    - name: core_callaction_local_office_checked_base 
    - name: core_callaction_targeted_base 
    - name: core_campaignvolunteeraction_base 
    - name: core_eventcreateaction_base 
    - name: core_eventmoderateaction_base 
    - name: core_eventsignupaction_base 
    - name: core_eventvolunteeraction_base 
    - name: core_location_base 
    - name: core_lteaction_base 
    - name: core_phone_base 
    - name: core_reengagementlog_base 
    - name: core_user_base 
    - name: core_user_groups_base 
    - name: core_user_page_tags_base 
    - name: core_useragent_base 
    - name: core_userdailysummary_base 
    - name: core_userdivision_base 
    - name: core_userfield_base 
    - name: core_usergroup_base 
    - name: core_usermerge_base 
    - name: core_usermerge_users_base 
    - name: core_userstaffnote_base 
    - name: core_whipcountactioncalled_base 
    - name: events_campaign_base 
    - name: events_campaignvolunteer_base 
    - name: events_customemail_base 
    - name: events_customemailgroup_base 
    - name: events_emailbodylog_base 
    - name: events_emaillog_base 
    - name: events_emaillog_to_users_base 
    - name: events_event_base 
    - name: events_eventfield_base 
    - name: events_eventsignup_base 
    - name: events_eventsignupfield_base 
    - name: events_historicalevent_base 
    - name: oneclick_storeduser_base 
    - name: oneclick_use_base 
    - name: spam_spamchecklog_base