version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
    - name: _airbyte_raw_categories
    - name: _airbyte_raw_customers
    - name: _airbyte_raw_discounts
    - name: _airbyte_raw_items
    - name: _airbyte_raw_locations
    - name: _airbyte_raw_modifier_list
    - name: _airbyte_raw_orders
    - name: _airbyte_raw_payments
    - name: _airbyte_raw_refunds
    - name: _airbyte_raw_shifts
    - name: _airbyte_raw_taxes
    - name: _airbyte_raw_team_member_wages
    - name: _airbyte_raw_team_members
    - name: customers
    - name: customers_address
    - name: customers_cards
    - name: customers_cards_billing_address
    - name: customers_preferences
    - name: locations
    - name: locations_address
    - name: orders
    - name: orders_discounts
    - name: orders_discounts_applied_money
    - name: orders_fulfillments
    - name: orders_fulfillments_pickup_details
    - name: orders_fulfillments_pickup_details_recipient
    - name: orders_fulfillments_shipment_details
    - name: orders_fulfillments_shipment_details_recipient
    - name: orders_fulfillments_shipment_details_recipient_address
    - name: orders_line_items
    - name: orders_line_items_applied_discounts
    - name: orders_line_items_applied_discounts_applied_money
    - name: orders_line_items_applied_taxes
    - name: orders_line_items_applied_taxes_applied_money
    - name: orders_line_items_base_price_money
    - name: orders_line_items_gross_sales_money
    - name: orders_line_items_modifiers
    - name: orders_line_items_modifiers_base_price_money
    - name: orders_line_items_modifiers_total_price_money
    - name: orders_line_items_total_discount_money
    - name: orders_line_items_total_money
    - name: orders_line_items_total_tax_money
    - name: orders_line_items_variation_total_price_money
    - name: orders_net_amounts
    - name: orders_net_amounts_discount_money
    - name: orders_net_amounts_service_charge_money
    - name: orders_net_amounts_tax_money
    - name: orders_net_amounts_tip_money
    - name: orders_net_amounts_total_money
    - name: orders_refunds
    - name: orders_refunds_amount_money
    - name: orders_return_amounts
    - name: orders_return_amounts_discount_money
    - name: orders_return_amounts_service_charge_money
    - name: orders_return_amounts_tax_money
    - name: orders_return_amounts_tip_money
    - name: orders_return_amounts_total_money
    - name: orders_returns
    - name: orders_returns_return_line_items
    - name: orders_returns_return_line_items_base_price_money
    - name: orders_returns_return_line_items_gross_return_money
    - name: orders_returns_return_line_items_total_discount_money
    - name: orders_returns_return_line_items_total_money
    - name: orders_returns_return_line_items_total_tax_money
    - name: orders_returns_return_line_items_variation_total_price_money
    - name: orders_service_charges
    - name: orders_service_charges_amount_money
    - name: orders_service_charges_applied_money
    - name: orders_service_charges_total_money
    - name: orders_service_charges_total_tax_money
    - name: orders_source
    - name: orders_taxes
    - name: orders_taxes_applied_money
    - name: orders_tenders
    - name: orders_tenders_amount_money
    - name: orders_tenders_card_details
    - name: orders_tenders_card_details_card
    - name: orders_tenders_cash_details
    - name: orders_tenders_cash_details_buyer_tendered_money
    - name: orders_tenders_cash_details_change_back_money
    - name: orders_total_discount_money
    - name: orders_total_money
    - name: orders_total_service_charge_money
    - name: orders_total_tax_money
    - name: orders_total_tip_money
    - name: shifts
    - name: shifts_breaks
    - name: shifts_wage
    - name: shifts_wage_hourly_rate
    - name: team_member_wages
    - name: team_member_wages_hourly_rate
    - name: team_members
    - name: team_members_assigned_locations
    - name: categories
    - name: categories_category_data
    - name: discounts
    - name: discounts_discount_data
    - name: discounts_discount_data_amount_money
    - name: items
    - name: items_item_data
    - name: items_item_data_item_options
    - name: items_item_data_modifier_list_info
    - name: items_item_data_variations
    - name: items_item_data_variations_item_variation_data
    - name: items_item_data_variations_item_variation_data_item_option_values
    - name: items_item_data_variations_item_variation_data_location_overrides
    - name: items_item_data_variations_item_variation_data_price_money
    - name: modifier_list
    - name: modifier_list_modifier_list_data
    - name: modifier_list_modifier_list_data_modifiers
    - name: modifier_list_modifier_list_data_modifiers_modifier_data
    - name: modifier_list_modifier_list_data_modifiers_modifier_data_price_money
    - name: payments
    - name: payments_amount_money
    - name: payments_approved_money
    - name: payments_card_details
    - name: payments_card_details_card
    - name: payments_card_details_card_payment_timeline
    - name: payments_processing_fee
    - name: payments_processing_fee_amount_money
    - name: payments_refunded_money
    - name: payments_risk_evaluation
    - name: payments_total_money
    - name: refunds
    - name: refunds_amount_money
    - name: refunds_processing_fee
    - name: refunds_processing_fee_amount_money
    - name: taxes
    - name: taxes_tax_data