name: 'example_airflow_dbt'
version: '1.0'
config-version: 2

profile: 'default'

models:
  example_airflow_dbt:
    0_ctes:
      +tags: 
        - cta
      +materialized: ephemeral
    1_cta_base:
      +tags: 
        - cta
      +materialized: table
    2_partner_matviews:
      +tags: 
        - partner
      +materialized: materialized_view
      +auto_refresh: true
      +refresh_interval_minutes: 1440
    3_partner_views:
      +tags: 
        - partner
      +materialized: view