name: 'example_airflow_dbt'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["{{ env_var('CTA_DATASET_ID') }}/models"]
packages-install-path: "{{ env_var('CTA_DATASET_ID') }}/dbt-packages"

models:
  example_airflow_dbt:
    0_ctes:
      +tags: 
        - cta
      +materialized: ephemeral
    1_cta_base:
      +tags: 
        - cta
      +materialized: table
    2_partner_matviews:
      +tags: 
        - partner
      +materialized: materialized_view
      +auto_refresh: true
      +refresh_interval_minutes: 1440
    3_partner_views:
      +tags: 
        - partner
      +materialized: view