config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true

default:
  outputs:
    cta:
      project: "{{ env_var('CTA_PROJECT_ID') }}"
      dataset: "{{ env_var('CTA_DATASET_ID') }}"
      location: US
      method: oauth
      priority: batch
      retries: 1
      threads: 8
      type: bigquery
    partner:
      project: "{{ env_var('PARTNER_PROJECT_ID') }}"
      dataset: "{{ env_var('PARTNER_DATASET_ID') }}"
      location: US
      method: oauth
      priority: batch
      retries: 1
      threads: 8
      type: bigquery  