version: 2
sources:
- name: cta
  database: "{{ var('CTA_PROJECT_ID') }}"
  schema: "{{ var('CTA_DATASET_ID') }}"
  tables:
- name: partner
  database: "{{ var('PARTNER_PROJECT_ID') }}"
  schema: "{{ var('PARTNER_DATASET_ID') }}"
  tables: