version: 2
sources:
- name: cta
  database: "{{ var('PROJECT_ID') }}"
  schema: "{{ var('DATASET_ID') }}"
  tables:
- name: partner
  database: "{{ var('PROJECT_ID') }}"
  schema: "{{ var('DATASET_ID') }}"
  tables: