version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_managed_form_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
  - name: _airbyte_raw_paid_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
  - name: _airbyte_raw_refunded_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
  - name: _airbyte_raw_cancelled_recurring_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
  - name: managed_form_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
  - name: paid_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
  - name: refunded_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
  - name: cancelled_recurring_contributions_stream
    columns:
      - name: _airbyte_ab_id
        tests:
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
