{% raw %}version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables: {% endraw %}{% for table in table_list %}
    - name: {{ table }}{% endfor %}
  {% for table in table_list %}
    - name: {{ table }}_base{% endfor %}
