version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_account_campaigns_stats
  - name: _airbyte_raw_account_line_items_stats
  - name: _airbyte_raw_account_native_ads_stats
  - name: _airbyte_raw_advertisers
  - name: _airbyte_raw_campaigns
  - name: _airbyte_raw_conversion_trackers
  - name: _airbyte_raw_line_items
  - name: _airbyte_raw_native_ads
  - name: account_campaigns_stats_base
  - name: account_line_items_stats_base
  - name: account_native_ads_stats_base
  - name: account_native_ads_stats_creatives_base
  - name: advertisers_base
  - name: campaigns_base
  - name: campaigns_day_part_base
  - name: conversion_trackers_base
  - name: line_items_base
  - name: native_ads_base
  - name: native_ads_creatives_base
  - name: native_ads_icon_base
  - name: native_ads_input_data_base
  - name: native_ads_input_data_audio_creatives_base
  - name: native_ads_input_data_display_js_creative_base
  - name: native_ads_input_data_video_creatives_base
  - name: native_ads_vast_trackers_base
- name: cta_delivery
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}_delivery"
  tables:
  - name: account_native_ads_stats
  - name: campaigns
  - name: line_items




from {{ source('cta_delivery', 'account_native_ads_stats') }} as ad_stats
inner join {{ source('cta_delivery', 'campaigns') }} as campaigns_base on ad_stats.campaign_id = campaigns_base.id
inner join {{ source('cta_delivery', 'line_items') }} as line_items_base on ad_stats.line_item_id = line_items_base.id
