-- depends_on: {{ source('cta', 'account_line_items_stats_base') }}
select
    _airbyte_account_line_items_stats_hashid,
    MAX(ctr) as ctr,
    MAX(cvr) as cvr,
    MAX(imp) as imp,
    MAX(ltr) as ltr,
    MAX(atos) as atos,
    MAX(conv) as conv,
    MAX(cost) as cost,
    MAX(date) as date,
    MAX(ecpa) as ecpa,
    MAX(ecpc) as ecpc,
    MAX(ecpe) as ecpe,
    MAX(ecpm) as ecpm,
    MAX(ecpv) as ecpv,
    MAX(rcpc) as rcpc,
    MAX(rcpe) as rcpe,
    MAX(rcpm) as rcpm,
    MAX(roas) as roas,
    MAX(click) as click,
    MAX(ecpcl) as ecpcl,
    MAX(rcpcl) as rcpcl,
    MAX(profit) as profit,
    MAX(s_conv) as s_conv,
    MAX(conv_ip) as conv_ip,
    MAX(revenue) as revenue,
    MAX(vcomp_0) as vcomp_0,
    MAX(conv_rev) as conv_rev,
    MAX(vcomp_25) as vcomp_25,
    MAX(vcomp_50) as vcomp_50,
    MAX(vcomp_75) as vcomp_75,
    MAX(vcomp_95) as vcomp_95,
    MAX(line_item) as line_item,
    MAX(page_time) as page_time,
    MAX(uniq_conv) as uniq_conv,
    MAX(uniq_ecpa) as uniq_ecpa,
    MAX(atos_units) as atos_units,
    MAX(conv_click) as conv_click,
    MAX(page_start) as page_start,
    MAX(reach) as reach,
    MAX(vcomp_rate) as vcomp_rate,
    MAX(engage_rate) as engage_rate,
    MAX(tp_cpc_cost) as tp_cpc_cost,
    MAX(tp_cpm_cost) as tp_cpm_cost,
    MAX(unique_conv) as unique_conv,
    MAX(view_percent) as view_percent,
    MAX(page_time_15s) as page_time_15s,
    MAX(sub_advertiser) as sub_advertiser,
    MAX(page_time_units) as page_time_units,
    MAX(conv_imp_derived) as conv_imp_derived,
    MAX(conv_imp_time_avg) as conv_imp_time_avg,
    MAX(conv_click_time_avg) as conv_click_time_avg,
    MAX(frequency) as frequency,
    MAX(_airbyte_ab_id) as _airbyte_ab_id,
    MAX(_airbyte_emitted_at) as _airbyte_emitted_at,
    MAX(_airbyte_normalized_at) as _airbyte_normalized_at
from {{ source('cta', 'account_line_items_stats_base') }}
where 1 = 1
group by _airbyte_account_line_items_stats_hashid

