-- depends_on: {{ source('cta', 'campaigns_base') }}
select
    _airbyte_campaigns_hashid,
    MAX(id) as id,
    MAX(goal) as goal,
    MAX(name) as name,
    MAX(state) as state,
    MAX(budget) as budget,
    MAX(channel) as channel,
    MAX(use_dma) as use_dma,
    MAX(bid_type) as bid_type,
    MAX(day_part) as day_part,
    MAX(end_date) as end_date,
    MAX(daily_cap) as daily_cap,
    MAX(start_date) as start_date,
    MAX(pace_evenly) as pace_evenly,
    MAX(city_options) as city_options,
    MAX(line_item_id) as line_item_id,
    MAX(advertiser_id) as advertiser_id,
    MAX(campaign_type) as campaign_type,
    MAX(domain_action) as domain_action,
    MAX(freq_cap_time) as freq_cap_time,
    MAX(optimize_type) as optimize_type,
    MAX(ARRAY_TO_STRING(all_native_ads_ids,',')) as all_native_ads_ids,
    MAX(ARRAY_TO_STRING(domain_options,',')) as domain_options,
    MAX(freq_cap_limit) as freq_cap_limit,
    MAX(optimize_value) as optimize_value,
    MAX(ARRAY_TO_STRING(country_options,',')) as country_options,
    MAX(smart_targeting) as smart_targeting,
    MAX(ARRAY_TO_STRING(weekday_budgets,',')) as weekday_budgets,
    MAX(weekday_enabled) as weekday_enabled,
    MAX(bid_amount_total) as bid_amount_total,
    MAX(ARRAY_TO_STRING(category_options,',')) as category_options,
    MAX(ARRAY_TO_STRING(language_options,',')) as language_options,
    MAX(ARRAY_TO_STRING(us_state_options,',')) as us_state_options,
    MAX(ARRAY_TO_STRING(weekday_percents,',')) as weekday_percents,
    MAX(ARRAY_TO_STRING(uk_county_options,',')) as uk_county_options,
    MAX(ARRAY_TO_STRING(device_type_options,',')) as device_type_options,
    MAX(ARRAY_TO_STRING(other_state_options,',')) as other_state_options,
    MAX(ARRAY_TO_STRING(supply_type_options,',')) as supply_type_options,
    MAX(ARRAY_TO_STRING(custom_segments_list,',')) as custom_segments_list,
    MAX(ARRAY_TO_STRING(third_party_segments,',')) as third_party_segments,
    MAX(ARRAY_TO_STRING(supply_source_options,',')) as supply_source_options,
    MAX(allow_iframe_engagement) as allow_iframe_engagement,
    MAX(ARRAY_TO_STRING(canada_province_options,',')) as canada_province_options,
    MAX(_airbyte_ab_id) as _airbyte_ab_id,
    MAX(_airbyte_emitted_at) as _airbyte_emitted_at,
    MAX(_airbyte_normalized_at) as _airbyte_normalized_at
from {{ source('cta', 'campaigns_base') }}
where 1=1
group by _airbyte_campaigns_hashid