version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables: 
    - name: activities
    - name: ad_account
    - name: ad_creatives
    - name: ad_sets
    - name: ads
    - name: ads_insights
    - name: ads_insights_action_carousel_card
    - name: ads_insights_action_conversion_device
    - name: ads_insights_action_product_id
    - name: ads_insights_action_reaction
    - name: ads_insights_action_type
    - name: ads_insights_action_video_sound
    - name: ads_insights_action_video_type
    - name: ads_insights_age_and_gender
    - name: ads_insights_country
    - name: ads_insights_delivery_device
    - name: ads_insights_delivery_platform
    - name: ads_insights_delivery_platform_and_device_platform
    - name: ads_insights_demographics_age
    - name: ads_insights_demographics_country
    - name: ads_insights_demographics_dma_region
    - name: ads_insights_demographics_gender
    - name: ads_insights_dma
    - name: ads_insights_platform_and_device
    - name: ads_insights_region
    - name: campaigns
    - name: custom_conversions
    - name: images
    - name: videos
  
    - name: activities_base
    - name: ad_account_base
    - name: ad_creatives_base
    - name: ad_sets_base
    - name: ads_base
    - name: ads_insights_base
    - name: ads_insights_action_carousel_card_base
    - name: ads_insights_action_conversion_device_base
    - name: ads_insights_action_product_id_base
    - name: ads_insights_action_reaction_base
    - name: ads_insights_action_type_base
    - name: ads_insights_action_video_sound_base
    - name: ads_insights_action_video_type_base
    - name: ads_insights_age_and_gender_base
    - name: ads_insights_country_base
    - name: ads_insights_delivery_device_base
    - name: ads_insights_delivery_platform_base
    - name: ads_insights_delivery_platform_and_device_platform_base
    - name: ads_insights_demographics_age_base
    - name: ads_insights_demographics_country_base
    - name: ads_insights_demographics_dma_region_base
    - name: ads_insights_demographics_gender_base
    - name: ads_insights_dma_base
    - name: ads_insights_platform_and_device_base
    - name: ads_insights_region_base
    - name: campaigns_base
    - name: custom_conversions_base
    - name: images_base
    - name: videos_base