version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: ctaResults_base
  - name: ctas_base
  - name: ctas_prompts_base
  - name: ctas_prompts_answers_base
  - name: ctas_questions_base
  - name: ctas_shareables_base
  - name: outreachEntries_base
  - name: profileOrganizationTags_base
  - name: profiles_base
  - name: regions_base
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_ctaResults' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_ctas' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_outreachEntries' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_profileOrganizationTags' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_profiles' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_regions' }}"
