version: 2
sources:
- name: empower_partner_a
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_ctaResults
  - name: _airbyte_raw_ctas
  - name: _airbyte_raw_outreachEntries
  - name: _airbyte_raw_profileOrganizationTags
  - name: _airbyte_raw_profiles
  - name: _airbyte_raw_regions
