version: 2
sources:
- name: usvote_foundation
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_offices
  - name: _airbyte_raw_officials
  - name: _airbyte_raw_regions
  - name: _airbyte_raw_states
