version: 2
sources:
- name: cta
  quoting:
    database: "{{ env_var('CTA_PROJECT_ID') }}"
    schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_offices
  - name: _airbyte_raw_officials
  - name: _airbyte_raw_regions
  - name: _airbyte_raw_states
