{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id',
) }}

{% set raw_source_name = var('cta_dataset_id') + "_raw__stream_page" %}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ source('cta', raw_source_name) }} 
select
    {{ json_extract_scalar('_airbyte_data', ['name_with_location_descriptor'], ['name_with_location_descriptor']) }} as name_with_location_descriptor,
    {{ json_extract_scalar('_airbyte_data', ['attire'], ['attire']) }} as attire,
    {{ json_extract('table_alias', '_airbyte_data', ['messaging_feature_status'], ['messaging_feature_status']) }} as messaging_feature_status,
    {{ json_extract('table_alias', '_airbyte_data', ['subscribed_apps'], ['subscribed_apps']) }} as subscribed_apps,
    {{ json_extract_scalar('_airbyte_data', ['about'], ['about']) }} as about,
    {{ json_extract('table_alias', '_airbyte_data', ['videos'], ['videos']) }} as videos,
    {{ json_extract('table_alias', '_airbyte_data', ['published_posts'], ['published_posts']) }} as published_posts,
    {{ json_extract('table_alias', '_airbyte_data', ['cover'], ['cover']) }} as cover,
    {{ json_extract_scalar('_airbyte_data', ['culinary_team'], ['culinary_team']) }} as culinary_team,
    {{ json_extract('table_alias', '_airbyte_data', ['tagged'], ['tagged']) }} as tagged,
    {{ json_extract_scalar('_airbyte_data', ['app_id'], ['app_id']) }} as app_id,
    {{ json_extract_scalar('_airbyte_data', ['is_community_page'], ['is_community_page']) }} as is_community_page,
    {{ json_extract('table_alias', '_airbyte_data', ['events'], ['events']) }} as events,
    {{ json_extract('table_alias', '_airbyte_data', ['custom_labels'], ['custom_labels']) }} as custom_labels,
    {{ json_extract_scalar('_airbyte_data', ['offer_eligible'], ['offer_eligible']) }} as offer_eligible,
    {{ json_extract('table_alias', '_airbyte_data', ['messaging_feature_review'], ['messaging_feature_review']) }} as messaging_feature_review,
    {{ json_extract_scalar('_airbyte_data', ['global_brand_page_name'], ['global_brand_page_name']) }} as global_brand_page_name,
    {{ json_extract('table_alias', '_airbyte_data', ['personas'], ['personas']) }} as personas,
    {{ json_extract('table_alias', '_airbyte_data', ['page_backed_instagram_accounts'], ['page_backed_instagram_accounts']) }} as page_backed_instagram_accounts,
    {{ json_extract('table_alias', '_airbyte_data', ['image_copyrights'], ['image_copyrights']) }} as image_copyrights,
    {{ json_extract_scalar('_airbyte_data', ['mission'], ['mission']) }} as mission,
    {{ json_extract_scalar('_airbyte_data', ['release_date'], ['release_date']) }} as release_date,
    {{ json_extract_scalar('_airbyte_data', ['global_brand_root_id'], ['global_brand_root_id']) }} as global_brand_root_id,
    {{ json_extract('table_alias', '_airbyte_data', ['connected_instagram_account'], ['connected_instagram_account']) }} as connected_instagram_account,
    {{ json_extract_scalar('_airbyte_data', ['store_number'], ['store_number']) }} as store_number,
    {{ json_extract_scalar('_airbyte_data', ['description_html'], ['description_html']) }} as description_html,
    {{ json_extract('table_alias', '_airbyte_data', ['instagram_accounts'], ['instagram_accounts']) }} as instagram_accounts,
    {{ json_extract('table_alias', '_airbyte_data', ['albums'], ['albums']) }} as albums,
    {{ json_extract('table_alias', '_airbyte_data', ['nativeoffers'], ['nativeoffers']) }} as nativeoffers,
    {{ json_extract_scalar('_airbyte_data', ['leadgen_tos_acceptance_time'], ['leadgen_tos_acceptance_time']) }} as leadgen_tos_acceptance_time,
    {{ json_extract('table_alias', '_airbyte_data', ['mini_shop_storefront'], ['mini_shop_storefront']) }} as mini_shop_storefront,
    {{ json_extract('table_alias', '_airbyte_data', ['ads_posts'], ['ads_posts']) }} as ads_posts,
    {{ json_extract_scalar('_airbyte_data', ['new_like_count'], ['new_like_count']) }} as new_like_count,
    {{ json_extract_scalar('_airbyte_data', ['genre'], ['genre']) }} as genre,
    {{ json_extract_scalar('_airbyte_data', ['record_label'], ['record_label']) }} as record_label,
    {{ json_extract('table_alias', '_airbyte_data', ['start_info'], ['start_info']) }} as start_info,
    {{ json_extract_scalar('_airbyte_data', ['store_code'], ['store_code']) }} as store_code,
    {{ json_extract_scalar('_airbyte_data', ['website'], ['website']) }} as website,
    {{ json_extract('table_alias', '_airbyte_data', ['global_brand_children'], ['global_brand_children']) }} as global_brand_children,
    {{ json_extract('table_alias', '_airbyte_data', ['canvas_elements'], ['canvas_elements']) }} as canvas_elements,
    {{ json_extract_scalar('_airbyte_data', ['differently_open_offerings'], ['differently_open_offerings']) }} as differently_open_offerings,
    {{ json_extract_scalar('_airbyte_data', ['business'], ['business']) }} as business,
    {{ json_extract_scalar('_airbyte_data', ['founded'], ['founded']) }} as founded,
    {{ json_extract_scalar('_airbyte_data', ['is_owned'], ['is_owned']) }} as is_owned,
    {{ json_extract_scalar('_airbyte_data', ['privacy_info_url'], ['privacy_info_url']) }} as privacy_info_url,
    {{ json_extract_scalar('_airbyte_data', ['company_overview'], ['company_overview']) }} as company_overview,
    {{ json_extract_scalar('_airbyte_data', ['unread_message_count'], ['unread_message_count']) }} as unread_message_count,
    {{ json_extract('table_alias', '_airbyte_data', ['indexed_videos'], ['indexed_videos']) }} as indexed_videos,
    {{ json_extract('table_alias', '_airbyte_data', ['restaurant_specialties'], ['restaurant_specialties']) }} as restaurant_specialties,
    {{ json_extract_scalar('_airbyte_data', ['single_line_address'], ['single_line_address']) }} as single_line_address,
    {{ json_extract_scalar('_airbyte_data', ['promotion_ineligible_reason'], ['promotion_ineligible_reason']) }} as promotion_ineligible_reason,
    {{ json_extract_scalar('_airbyte_data', ['checkins'], ['checkins']) }} as checkins,
    {{ json_extract_string_array('_airbyte_data', ['pickup_options'], ['pickup_options']) }} as pickup_options,
    {{ json_extract_scalar('_airbyte_data', ['written_by'], ['written_by']) }} as written_by,
    {{ json_extract('table_alias', '_airbyte_data', ['crosspost_whitelisted_pages'], ['crosspost_whitelisted_pages']) }} as crosspost_whitelisted_pages,
    {{ json_extract('table_alias', '_airbyte_data', ['engagement'], ['engagement']) }} as engagement,
    {{ json_extract_scalar('_airbyte_data', ['keywords'], ['keywords']) }} as keywords,
    {{ json_extract_scalar('_airbyte_data', ['overall_star_rating'], ['overall_star_rating']) }} as overall_star_rating,
    {{ json_extract_scalar('_airbyte_data', ['price_range'], ['price_range']) }} as price_range,
    {{ json_extract_scalar('_airbyte_data', ['pharma_safety_info'], ['pharma_safety_info']) }} as pharma_safety_info,
    {{ json_extract_scalar('_airbyte_data', ['features'], ['features']) }} as features,
    {{ json_extract_scalar('_airbyte_data', ['affiliation'], ['affiliation']) }} as affiliation,
    {{ json_extract_scalar('_airbyte_data', ['whatsapp_number'], ['whatsapp_number']) }} as whatsapp_number,
    {{ json_extract_scalar('_airbyte_data', ['current_location'], ['current_location']) }} as current_location,
    {{ json_extract('table_alias', '_airbyte_data', ['instagram_business_account'], ['instagram_business_account']) }} as instagram_business_account,
    {{ json_extract_scalar('_airbyte_data', ['fan_count'], ['fan_count']) }} as fan_count,
    {{ json_extract_scalar('_airbyte_data', ['talking_about_count'], ['talking_about_count']) }} as talking_about_count,
    {{ json_extract('table_alias', '_airbyte_data', ['live_videos'], ['live_videos']) }} as live_videos,
    {{ json_extract_scalar('_airbyte_data', ['name'], ['name']) }} as name,
    {{ json_extract_scalar('_airbyte_data', ['produced_by'], ['produced_by']) }} as produced_by,
    {{ json_extract_scalar('_airbyte_data', ['is_webhooks_subscribed'], ['is_webhooks_subscribed']) }} as is_webhooks_subscribed,
    {{ json_extract_scalar('_airbyte_data', ['booking_agent'], ['booking_agent']) }} as booking_agent,
    {{ json_extract('table_alias', '_airbyte_data', ['custom_user_settings'], ['custom_user_settings']) }} as custom_user_settings,
    {{ json_extract_scalar('_airbyte_data', ['can_checkin'], ['can_checkin']) }} as can_checkin,
    {{ json_extract('table_alias', '_airbyte_data', ['roles'], ['roles']) }} as roles,
    {{ json_extract_scalar('_airbyte_data', ['description'], ['description']) }} as description,
    {{ json_extract('table_alias', '_airbyte_data', ['voip_info'], ['voip_info']) }} as voip_info,
    {{ json_extract_scalar('_airbyte_data', ['merchant_id'], ['merchant_id']) }} as merchant_id,
    {{ json_extract_string_array('_airbyte_data', ['emails'], ['emails']) }} as emails,
    {{ json_extract('table_alias', '_airbyte_data', ['messenger_profile'], ['messenger_profile']) }} as messenger_profile,
    {{ json_extract_scalar('_airbyte_data', ['supports_instant_articles'], ['supports_instant_articles']) }} as supports_instant_articles,
    {{ json_extract('table_alias', '_airbyte_data', ['ratings'], ['ratings']) }} as ratings,
    {{ json_extract_scalar('_airbyte_data', ['display_subtext'], ['display_subtext']) }} as display_subtext,
    {{ json_extract('table_alias', '_airbyte_data', ['copyright_whitelisted_partners'], ['copyright_whitelisted_partners']) }} as copyright_whitelisted_partners,
    {{ json_extract('table_alias', '_airbyte_data', ['best_page'], ['best_page']) }} as best_page,
    {{ json_extract('table_alias', '_airbyte_data', ['contact_address'], ['contact_address']) }} as contact_address,
    {{ json_extract_scalar('_airbyte_data', ['hours'], ['hours']) }} as hours,
    {{ json_extract_scalar('_airbyte_data', ['hometown'], ['hometown']) }} as hometown,
    {{ json_extract_scalar('_airbyte_data', ['screenplay_by'], ['screenplay_by']) }} as screenplay_by,
    {{ json_extract_scalar('_airbyte_data', ['is_always_open'], ['is_always_open']) }} as is_always_open,
    {{ json_extract_string_array('_airbyte_data', ['delivery_and_pickup_option_info'], ['delivery_and_pickup_option_info']) }} as delivery_and_pickup_option_info,
    {{ json_extract('table_alias', '_airbyte_data', ['secondary_receivers'], ['secondary_receivers']) }} as secondary_receivers,
    {{ json_extract('table_alias', '_airbyte_data', ['agencies'], ['agencies']) }} as agencies,
    {{ json_extract('table_alias', '_airbyte_data', ['commerce_payouts'], ['commerce_payouts']) }} as commerce_payouts,
    {{ json_extract('table_alias', '_airbyte_data', ['media_fingerprints'], ['media_fingerprints']) }} as media_fingerprints,
    {{ json_extract_scalar('_airbyte_data', ['is_eligible_for_branded_content'], ['is_eligible_for_branded_content']) }} as is_eligible_for_branded_content,
    {{ json_extract_scalar('_airbyte_data', ['schedule'], ['schedule']) }} as schedule,
    {{ json_extract('table_alias', '_airbyte_data', ['admin_notes'], ['admin_notes']) }} as admin_notes,
    {{ json_extract_scalar('_airbyte_data', ['is_unclaimed'], ['is_unclaimed']) }} as is_unclaimed,
    {{ json_extract_scalar('_airbyte_data', ['followers_count'], ['followers_count']) }} as followers_count,
    {{ json_extract_scalar('_airbyte_data', ['recipient'], ['recipient']) }} as recipient,
    {{ json_extract('table_alias', '_airbyte_data', ['location'], ['location']) }} as location,
    {{ json_extract('table_alias', '_airbyte_data', ['video_lists'], ['video_lists']) }} as video_lists,
    {{ json_extract_scalar('_airbyte_data', ['username'], ['username']) }} as username,
    {{ json_extract_scalar('_airbyte_data', ['were_here_count'], ['were_here_count']) }} as were_here_count,
    {{ json_extract_scalar('_airbyte_data', ['studio'], ['studio']) }} as studio,
    {{ json_extract('table_alias', '_airbyte_data', ['parking'], ['parking']) }} as parking,
    {{ json_extract('table_alias', '_airbyte_data', ['visitor_posts'], ['visitor_posts']) }} as visitor_posts,
    {{ json_extract_string_array('_airbyte_data', ['food_styles'], ['food_styles']) }} as food_styles,
    {{ json_extract('table_alias', '_airbyte_data', ['restaurant_services'], ['restaurant_services']) }} as restaurant_services,
    {{ json_extract_scalar('_airbyte_data', ['is_published'], ['is_published']) }} as is_published,
    {{ json_extract_scalar('_airbyte_data', ['bio'], ['bio']) }} as bio,
    {{ json_extract_scalar('_airbyte_data', ['has_whatsapp_number'], ['has_whatsapp_number']) }} as has_whatsapp_number,
    {{ json_extract_scalar('_airbyte_data', ['displayed_message_response_time'], ['displayed_message_response_time']) }} as displayed_message_response_time,
    {{ json_extract_scalar('_airbyte_data', ['is_permanently_closed'], ['is_permanently_closed']) }} as is_permanently_closed,
    {{ json_extract('table_alias', '_airbyte_data', ['chat_plugin'], ['chat_plugin']) }} as chat_plugin,
    {{ json_extract_scalar('_airbyte_data', ['public_transit'], ['public_transit']) }} as public_transit,
    {{ json_extract_array('_airbyte_data', ['category_list'], ['category_list']) }} as category_list,
    {{ json_extract_scalar('_airbyte_data', ['is_messenger_bot_get_started_enabled'], ['is_messenger_bot_get_started_enabled']) }} as is_messenger_bot_get_started_enabled,
    {{ json_extract('table_alias', '_airbyte_data', ['claimed_urls'], ['claimed_urls']) }} as claimed_urls,
    {{ json_extract_string_array('_airbyte_data', ['copyright_whitelisted_ig_partners'], ['copyright_whitelisted_ig_partners']) }} as copyright_whitelisted_ig_partners,
    {{ json_extract_scalar('_airbyte_data', ['season'], ['season']) }} as season,
    {{ json_extract_scalar('_airbyte_data', ['store_location_descriptor'], ['store_location_descriptor']) }} as store_location_descriptor,
    {{ json_extract('table_alias', '_airbyte_data', ['leadgen_tos_accepting_user'], ['leadgen_tos_accepting_user']) }} as leadgen_tos_accepting_user,
    {{ json_extract_scalar('_airbyte_data', ['id'], ['id']) }} as id,
    {{ json_extract_scalar('_airbyte_data', ['band_members'], ['band_members']) }} as band_members,
    {{ json_extract('table_alias', '_airbyte_data', ['payment_options'], ['payment_options']) }} as payment_options,
    {{ json_extract('table_alias', '_airbyte_data', ['instant_articles_insights'], ['instant_articles_insights']) }} as instant_articles_insights,
    {{ json_extract_scalar('_airbyte_data', ['mpg'], ['mpg']) }} as mpg,
    {{ json_extract('table_alias', '_airbyte_data', ['shop_setup_status'], ['shop_setup_status']) }} as shop_setup_status,
    {{ json_extract_scalar('_airbyte_data', ['access_token'], ['access_token']) }} as access_token,
    {{ json_extract('table_alias', '_airbyte_data', ['product_catalogs'], ['product_catalogs']) }} as product_catalogs,
    {{ json_extract('table_alias', '_airbyte_data', ['commerce_orders'], ['commerce_orders']) }} as commerce_orders,
    {{ json_extract_scalar('_airbyte_data', ['phone'], ['phone']) }} as phone,
    {{ json_extract_scalar('_airbyte_data', ['instant_articles_review_status'], ['instant_articles_review_status']) }} as instant_articles_review_status,
    {{ json_extract('table_alias', '_airbyte_data', ['commerce_eligibility'], ['commerce_eligibility']) }} as commerce_eligibility,
    {{ json_extract_scalar('_airbyte_data', ['country_page_likes'], ['country_page_likes']) }} as country_page_likes,
    {{ json_extract('table_alias', '_airbyte_data', ['video_copyright_rules'], ['video_copyright_rules']) }} as video_copyright_rules,
    {{ json_extract('table_alias', '_airbyte_data', ['tabs'], ['tabs']) }} as tabs,
    {{ json_extract_scalar('_airbyte_data', ['plot_outline'], ['plot_outline']) }} as plot_outline,
    {{ json_extract('table_alias', '_airbyte_data', ['leadgen_forms'], ['leadgen_forms']) }} as leadgen_forms,
    {{ json_extract_scalar('_airbyte_data', ['products'], ['products']) }} as products,
    {{ json_extract('table_alias', '_airbyte_data', ['commerce_transactions'], ['commerce_transactions']) }} as commerce_transactions,
    {{ json_extract('table_alias', '_airbyte_data', ['blocked'], ['blocked']) }} as blocked,
    {{ json_extract_scalar('_airbyte_data', ['promotion_eligible'], ['promotion_eligible']) }} as promotion_eligible,
    {{ json_extract_string_array('_airbyte_data', ['messenger_ads_default_quick_replies'], ['messenger_ads_default_quick_replies']) }} as messenger_ads_default_quick_replies,
    {{ json_extract_scalar('_airbyte_data', ['place_type'], ['place_type']) }} as place_type,
    {{ json_extract_scalar('_airbyte_data', ['general_manager'], ['general_manager']) }} as general_manager,
    {{ json_extract_scalar('_airbyte_data', ['supports_donate_button_in_live_video'], ['supports_donate_button_in_live_video']) }} as supports_donate_button_in_live_video,
    {{ json_extract_scalar('_airbyte_data', ['is_verified'], ['is_verified']) }} as is_verified,
    {{ json_extract('table_alias', '_airbyte_data', ['scheduled_posts'], ['scheduled_posts']) }} as scheduled_posts,
    {{ json_extract('table_alias', '_airbyte_data', ['picture'], ['picture']) }} as picture,
    {{ json_extract_scalar('_airbyte_data', ['artists_we_like'], ['artists_we_like']) }} as artists_we_like,
    {{ json_extract_scalar('_airbyte_data', ['page_token'], ['page_token']) }} as page_token,
    {{ json_extract('table_alias', '_airbyte_data', ['rtb_dynamic_posts'], ['rtb_dynamic_posts']) }} as rtb_dynamic_posts,
    {{ json_extract('table_alias', '_airbyte_data', ['parent_page'], ['parent_page']) }} as parent_page,
    {{ json_extract('table_alias', '_airbyte_data', ['call_to_actions'], ['call_to_actions']) }} as call_to_actions,
    {{ json_extract('table_alias', '_airbyte_data', ['posts'], ['posts']) }} as posts,
    {{ json_extract('table_alias', '_airbyte_data', ['photos'], ['photos']) }} as photos,
    {{ json_extract_scalar('_airbyte_data', ['impressum'], ['impressum']) }} as impressum,
    {{ json_extract_scalar('_airbyte_data', ['press_contact'], ['press_contact']) }} as press_contact,
    {{ json_extract_scalar('_airbyte_data', ['band_interests'], ['band_interests']) }} as band_interests,
    {{ json_extract_scalar('_airbyte_data', ['has_whatsapp_business_number'], ['has_whatsapp_business_number']) }} as has_whatsapp_business_number,
    {{ json_extract_scalar('_airbyte_data', ['members'], ['members']) }} as members,
    {{ json_extract_scalar('_airbyte_data', ['has_added_app'], ['has_added_app']) }} as has_added_app,
    {{ json_extract('table_alias', '_airbyte_data', ['likes'], ['likes']) }} as likes,
    {{ json_extract_scalar('_airbyte_data', ['personal_interests'], ['personal_interests']) }} as personal_interests,
    {{ json_extract('table_alias', '_airbyte_data', ['settings'], ['settings']) }} as settings,
    {{ json_extract('table_alias', '_airbyte_data', ['insights'], ['insights']) }} as insights,
    {{ json_extract('table_alias', '_airbyte_data', ['assigned_users'], ['assigned_users']) }} as assigned_users,
    {{ json_extract_scalar('_airbyte_data', ['merchant_review_status'], ['merchant_review_status']) }} as merchant_review_status,
    {{ json_extract('table_alias', '_airbyte_data', ['connected_page_backed_instagram_account'], ['connected_page_backed_instagram_account']) }} as connected_page_backed_instagram_account,
    {{ json_extract_scalar('_airbyte_data', ['rating_count'], ['rating_count']) }} as rating_count,
    {{ json_extract('table_alias', '_airbyte_data', ['feed'], ['feed']) }} as feed,
    {{ json_extract('table_alias', '_airbyte_data', ['canvases'], ['canvases']) }} as canvases,
    {{ json_extract('table_alias', '_airbyte_data', ['featured_video'], ['featured_video']) }} as featured_video,
    {{ json_extract_scalar('_airbyte_data', ['is_messenger_platform_bot'], ['is_messenger_platform_bot']) }} as is_messenger_platform_bot,
    {{ json_extract('table_alias', '_airbyte_data', ['commerce_merchant_settings'], ['commerce_merchant_settings']) }} as commerce_merchant_settings,
    {{ json_extract_scalar('_airbyte_data', ['birthday'], ['birthday']) }} as birthday,
    {{ json_extract_scalar('_airbyte_data', ['has_transitioned_to_new_page_experience'], ['has_transitioned_to_new_page_experience']) }} as has_transitioned_to_new_page_experience,
    {{ json_extract('table_alias', '_airbyte_data', ['instant_articles'], ['instant_articles']) }} as instant_articles,
    {{ json_extract_scalar('_airbyte_data', ['link'], ['link']) }} as link,
    {{ json_extract('table_alias', '_airbyte_data', ['ad_campaign'], ['ad_campaign']) }} as ad_campaign,
    {{ json_extract_scalar('_airbyte_data', ['verification_status'], ['verification_status']) }} as verification_status,
    {{ json_extract('table_alias', '_airbyte_data', ['conversations'], ['conversations']) }} as conversations,
    {{ json_extract_scalar('_airbyte_data', ['network'], ['network']) }} as network,
    {{ json_extract_scalar('_airbyte_data', ['directed_by'], ['directed_by']) }} as directed_by,
    {{ json_extract_scalar('_airbyte_data', ['personal_info'], ['personal_info']) }} as personal_info,
    {{ json_extract_scalar('_airbyte_data', ['influences'], ['influences']) }} as influences,
    {{ json_extract_scalar('_airbyte_data', ['general_info'], ['general_info']) }} as general_info,
    {{ json_extract_scalar('_airbyte_data', ['can_post'], ['can_post']) }} as can_post,
    {{ json_extract('table_alias', '_airbyte_data', ['preferred_audience'], ['preferred_audience']) }} as preferred_audience,
    {{ json_extract_scalar('_airbyte_data', ['temporary_status'], ['temporary_status']) }} as temporary_status,
    {{ json_extract_scalar('_airbyte_data', ['is_chain'], ['is_chain']) }} as is_chain,
    {{ json_extract_scalar('_airbyte_data', ['built'], ['built']) }} as built,
    {{ json_extract('table_alias', '_airbyte_data', ['groups'], ['groups']) }} as {{ adapter.quote('groups') }},
    {{ json_extract('table_alias', '_airbyte_data', ['threads'], ['threads']) }} as threads,
    {{ json_extract_scalar('_airbyte_data', ['messenger_ads_quick_replies_type'], ['messenger_ads_quick_replies_type']) }} as messenger_ads_quick_replies_type,
    {{ json_extract('table_alias', '_airbyte_data', ['thread_owner'], ['thread_owner']) }} as thread_owner,
    {{ json_extract_scalar('_airbyte_data', ['awards'], ['awards']) }} as awards,
    {{ json_extract_scalar('_airbyte_data', ['starring'], ['starring']) }} as starring,
    {{ json_extract_string_array('_airbyte_data', ['messenger_ads_default_icebreakers'], ['messenger_ads_default_icebreakers']) }} as messenger_ads_default_icebreakers,
    {{ json_extract('table_alias', '_airbyte_data', ['locations'], ['locations']) }} as locations,
    {{ json_extract_scalar('_airbyte_data', ['unseen_message_count'], ['unseen_message_count']) }} as unseen_message_count,
    {{ json_extract_scalar('_airbyte_data', ['category'], ['category']) }} as category,
    {{ json_extract_scalar('_airbyte_data', ['unread_notif_count'], ['unread_notif_count']) }} as unread_notif_count,
    {{ json_extract_scalar('_airbyte_data', ['leadgen_tos_accepted'], ['leadgen_tos_accepted']) }} as leadgen_tos_accepted,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ source('cta', raw_source_name) }}  as table_alias
-- page
where 1 = 1

