{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    tags = [ "nested-intermediate" ]
) }}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ ref('page') }}
select
    _airbyte_page_hashid,
    {{ json_extract_scalar('best_page', ['studio'], ['studio']) }} as studio,
    {{ json_extract_string_array('best_page', ['food_styles'], ['food_styles']) }} as food_styles,
    {{ json_extract_scalar('best_page', ['name_with_location_descriptor'], ['name_with_location_descriptor']) }} as name_with_location_descriptor,
    {{ json_extract_scalar('best_page', ['attire'], ['attire']) }} as attire,
    {{ json_extract_scalar('best_page', ['is_published'], ['is_published']) }} as is_published,
    {{ json_extract_scalar('best_page', ['about'], ['about']) }} as about,
    {{ json_extract_scalar('best_page', ['bio'], ['bio']) }} as bio,
    {{ json_extract_scalar('best_page', ['has_whatsapp_number'], ['has_whatsapp_number']) }} as has_whatsapp_number,
    {{ json_extract_scalar('best_page', ['displayed_message_response_time'], ['displayed_message_response_time']) }} as displayed_message_response_time,
    {{ json_extract_scalar('best_page', ['is_permanently_closed'], ['is_permanently_closed']) }} as is_permanently_closed,
    {{ json_extract_scalar('best_page', ['public_transit'], ['public_transit']) }} as public_transit,
    {{ json_extract_scalar('best_page', ['culinary_team'], ['culinary_team']) }} as culinary_team,
    {{ json_extract_scalar('best_page', ['is_messenger_bot_get_started_enabled'], ['is_messenger_bot_get_started_enabled']) }} as is_messenger_bot_get_started_enabled,
    {{ json_extract_string_array('best_page', ['copyright_whitelisted_ig_partners'], ['copyright_whitelisted_ig_partners']) }} as copyright_whitelisted_ig_partners,
    {{ json_extract_scalar('best_page', ['season'], ['season']) }} as season,
    {{ json_extract_scalar('best_page', ['store_location_descriptor'], ['store_location_descriptor']) }} as store_location_descriptor,
    {{ json_extract_scalar('best_page', ['id'], ['id']) }} as id,
    {{ json_extract_scalar('best_page', ['app_id'], ['app_id']) }} as app_id,
    {{ json_extract_scalar('best_page', ['is_community_page'], ['is_community_page']) }} as is_community_page,
    {{ json_extract_scalar('best_page', ['band_members'], ['band_members']) }} as band_members,
    {{ json_extract_scalar('best_page', ['mpg'], ['mpg']) }} as mpg,
    {{ json_extract_scalar('best_page', ['offer_eligible'], ['offer_eligible']) }} as offer_eligible,
    {{ json_extract_scalar('best_page', ['global_brand_page_name'], ['global_brand_page_name']) }} as global_brand_page_name,
    {{ json_extract_scalar('best_page', ['access_token'], ['access_token']) }} as access_token,
    {{ json_extract_scalar('best_page', ['mission'], ['mission']) }} as mission,
    {{ json_extract_scalar('best_page', ['phone'], ['phone']) }} as phone,
    {{ json_extract_scalar('best_page', ['release_date'], ['release_date']) }} as release_date,
    {{ json_extract_scalar('best_page', ['instant_articles_review_status'], ['instant_articles_review_status']) }} as instant_articles_review_status,
    {{ json_extract_scalar('best_page', ['global_brand_root_id'], ['global_brand_root_id']) }} as global_brand_root_id,
    {{ json_extract_scalar('best_page', ['store_number'], ['store_number']) }} as store_number,
    {{ json_extract_scalar('best_page', ['country_page_likes'], ['country_page_likes']) }} as country_page_likes,
    {{ json_extract_scalar('best_page', ['description_html'], ['description_html']) }} as description_html,
    {{ json_extract_scalar('best_page', ['leadgen_tos_acceptance_time'], ['leadgen_tos_acceptance_time']) }} as leadgen_tos_acceptance_time,
    {{ json_extract_scalar('best_page', ['plot_outline'], ['plot_outline']) }} as plot_outline,
    {{ json_extract_scalar('best_page', ['products'], ['products']) }} as products,
    {{ json_extract_scalar('best_page', ['new_like_count'], ['new_like_count']) }} as new_like_count,
    {{ json_extract_scalar('best_page', ['promotion_eligible'], ['promotion_eligible']) }} as promotion_eligible,
    {{ json_extract_string_array('best_page', ['messenger_ads_default_quick_replies'], ['messenger_ads_default_quick_replies']) }} as messenger_ads_default_quick_replies,
    {{ json_extract_scalar('best_page', ['place_type'], ['place_type']) }} as place_type,
    {{ json_extract_scalar('best_page', ['genre'], ['genre']) }} as genre,
    {{ json_extract_scalar('best_page', ['general_manager'], ['general_manager']) }} as general_manager,
    {{ json_extract_scalar('best_page', ['record_label'], ['record_label']) }} as record_label,
    {{ json_extract_scalar('best_page', ['store_code'], ['store_code']) }} as store_code,
    {{ json_extract_scalar('best_page', ['website'], ['website']) }} as website,
    {{ json_extract_scalar('best_page', ['supports_donate_button_in_live_video'], ['supports_donate_button_in_live_video']) }} as supports_donate_button_in_live_video,
    {{ json_extract_scalar('best_page', ['differently_open_offerings'], ['differently_open_offerings']) }} as differently_open_offerings,
    {{ json_extract_scalar('best_page', ['business'], ['business']) }} as business,
    {{ json_extract_scalar('best_page', ['founded'], ['founded']) }} as founded,
    {{ json_extract_scalar('best_page', ['is_owned'], ['is_owned']) }} as is_owned,
    {{ json_extract_scalar('best_page', ['privacy_info_url'], ['privacy_info_url']) }} as privacy_info_url,
    {{ json_extract_scalar('best_page', ['is_verified'], ['is_verified']) }} as is_verified,
    {{ json_extract_scalar('best_page', ['company_overview'], ['company_overview']) }} as company_overview,
    {{ json_extract_scalar('best_page', ['unread_message_count'], ['unread_message_count']) }} as unread_message_count,
    {{ json_extract_scalar('best_page', ['single_line_address'], ['single_line_address']) }} as single_line_address,
    {{ json_extract_scalar('best_page', ['artists_we_like'], ['artists_we_like']) }} as artists_we_like,
    {{ json_extract_scalar('best_page', ['promotion_ineligible_reason'], ['promotion_ineligible_reason']) }} as promotion_ineligible_reason,
    {{ json_extract_scalar('best_page', ['page_token'], ['page_token']) }} as page_token,
    {{ json_extract_scalar('best_page', ['checkins'], ['checkins']) }} as checkins,
    {{ json_extract_string_array('best_page', ['pickup_options'], ['pickup_options']) }} as pickup_options,
    {{ json_extract_scalar('best_page', ['written_by'], ['written_by']) }} as written_by,
    {{ json_extract_scalar('best_page', ['keywords'], ['keywords']) }} as keywords,
    {{ json_extract_scalar('best_page', ['overall_star_rating'], ['overall_star_rating']) }} as overall_star_rating,
    {{ json_extract_scalar('best_page', ['price_range'], ['price_range']) }} as price_range,
    {{ json_extract_scalar('best_page', ['pharma_safety_info'], ['pharma_safety_info']) }} as pharma_safety_info,
    {{ json_extract_scalar('best_page', ['impressum'], ['impressum']) }} as impressum,
    {{ json_extract_scalar('best_page', ['press_contact'], ['press_contact']) }} as press_contact,
    {{ json_extract_scalar('best_page', ['features'], ['features']) }} as features,
    {{ json_extract_scalar('best_page', ['band_interests'], ['band_interests']) }} as band_interests,
    {{ json_extract_scalar('best_page', ['has_whatsapp_business_number'], ['has_whatsapp_business_number']) }} as has_whatsapp_business_number,
    {{ json_extract_scalar('best_page', ['affiliation'], ['affiliation']) }} as affiliation,
    {{ json_extract_scalar('best_page', ['members'], ['members']) }} as members,
    {{ json_extract_scalar('best_page', ['has_added_app'], ['has_added_app']) }} as has_added_app,
    {{ json_extract_scalar('best_page', ['whatsapp_number'], ['whatsapp_number']) }} as whatsapp_number,
    {{ json_extract_scalar('best_page', ['current_location'], ['current_location']) }} as current_location,
    {{ json_extract_scalar('best_page', ['personal_interests'], ['personal_interests']) }} as personal_interests,
    {{ json_extract_scalar('best_page', ['fan_count'], ['fan_count']) }} as fan_count,
    {{ json_extract_scalar('best_page', ['talking_about_count'], ['talking_about_count']) }} as talking_about_count,
    {{ json_extract_scalar('best_page', ['merchant_review_status'], ['merchant_review_status']) }} as merchant_review_status,
    {{ json_extract_scalar('best_page', ['rating_count'], ['rating_count']) }} as rating_count,
    {{ json_extract_scalar('best_page', ['is_messenger_platform_bot'], ['is_messenger_platform_bot']) }} as is_messenger_platform_bot,
    {{ json_extract_scalar('best_page', ['name'], ['name']) }} as name,
    {{ json_extract_scalar('best_page', ['produced_by'], ['produced_by']) }} as produced_by,
    {{ json_extract_scalar('best_page', ['is_webhooks_subscribed'], ['is_webhooks_subscribed']) }} as is_webhooks_subscribed,
    {{ json_extract_scalar('best_page', ['booking_agent'], ['booking_agent']) }} as booking_agent,
    {{ json_extract_scalar('best_page', ['birthday'], ['birthday']) }} as birthday,
    {{ json_extract_scalar('best_page', ['has_transitioned_to_new_page_experience'], ['has_transitioned_to_new_page_experience']) }} as has_transitioned_to_new_page_experience,
    {{ json_extract_scalar('best_page', ['can_checkin'], ['can_checkin']) }} as can_checkin,
    {{ json_extract_scalar('best_page', ['link'], ['link']) }} as link,
    {{ json_extract_scalar('best_page', ['description'], ['description']) }} as description,
    {{ json_extract_scalar('best_page', ['merchant_id'], ['merchant_id']) }} as merchant_id,
    {{ json_extract_scalar('best_page', ['verification_status'], ['verification_status']) }} as verification_status,
    {{ json_extract_scalar('best_page', ['network'], ['network']) }} as network,
    {{ json_extract_string_array('best_page', ['emails'], ['emails']) }} as emails,
    {{ json_extract_scalar('best_page', ['directed_by'], ['directed_by']) }} as directed_by,
    {{ json_extract_scalar('best_page', ['personal_info'], ['personal_info']) }} as personal_info,
    {{ json_extract_scalar('best_page', ['supports_instant_articles'], ['supports_instant_articles']) }} as supports_instant_articles,
    {{ json_extract_scalar('best_page', ['influences'], ['influences']) }} as influences,
    {{ json_extract_scalar('best_page', ['display_subtext'], ['display_subtext']) }} as display_subtext,
    {{ json_extract_scalar('best_page', ['general_info'], ['general_info']) }} as general_info,
    {{ json_extract_scalar('best_page', ['can_post'], ['can_post']) }} as can_post,
    {{ json_extract_scalar('best_page', ['hours'], ['hours']) }} as hours,
    {{ json_extract_scalar('best_page', ['hometown'], ['hometown']) }} as hometown,
    {{ json_extract_scalar('best_page', ['temporary_status'], ['temporary_status']) }} as temporary_status,
    {{ json_extract_scalar('best_page', ['screenplay_by'], ['screenplay_by']) }} as screenplay_by,
    {{ json_extract_scalar('best_page', ['is_chain'], ['is_chain']) }} as is_chain,
    {{ json_extract_scalar('best_page', ['built'], ['built']) }} as built,
    {{ json_extract_scalar('best_page', ['is_always_open'], ['is_always_open']) }} as is_always_open,
    {{ json_extract_string_array('best_page', ['delivery_and_pickup_option_info'], ['delivery_and_pickup_option_info']) }} as delivery_and_pickup_option_info,
    {{ json_extract_scalar('best_page', ['messenger_ads_quick_replies_type'], ['messenger_ads_quick_replies_type']) }} as messenger_ads_quick_replies_type,
    {{ json_extract_scalar('best_page', ['is_eligible_for_branded_content'], ['is_eligible_for_branded_content']) }} as is_eligible_for_branded_content,
    {{ json_extract_scalar('best_page', ['schedule'], ['schedule']) }} as schedule,
    {{ json_extract_scalar('best_page', ['is_unclaimed'], ['is_unclaimed']) }} as is_unclaimed,
    {{ json_extract_scalar('best_page', ['awards'], ['awards']) }} as awards,
    {{ json_extract_scalar('best_page', ['followers_count'], ['followers_count']) }} as followers_count,
    {{ json_extract_scalar('best_page', ['recipient'], ['recipient']) }} as recipient,
    {{ json_extract_scalar('best_page', ['starring'], ['starring']) }} as starring,
    {{ json_extract_string_array('best_page', ['messenger_ads_default_icebreakers'], ['messenger_ads_default_icebreakers']) }} as messenger_ads_default_icebreakers,
    {{ json_extract_scalar('best_page', ['unseen_message_count'], ['unseen_message_count']) }} as unseen_message_count,
    {{ json_extract_scalar('best_page', ['category'], ['category']) }} as category,
    {{ json_extract_scalar('best_page', ['unread_notif_count'], ['unread_notif_count']) }} as unread_notif_count,
    {{ json_extract_scalar('best_page', ['leadgen_tos_accepted'], ['leadgen_tos_accepted']) }} as leadgen_tos_accepted,
    {{ json_extract_scalar('best_page', ['username'], ['username']) }} as username,
    {{ json_extract_scalar('best_page', ['were_here_count'], ['were_here_count']) }} as were_here_count,
    _airbyte_raw_id,
    _airbyte_extracted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('page') }} as table_alias
-- best_page at page/best_page
where 1 = 1
and best_page is not null

