{% set partitions_to_replace = [
    'timestamp_trunc(current_timestamp, day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 1 day), day)'
] %}

{{ config(
    partitions = partitions_to_replace,
    cluster_by = "_cta_loaded_at",
    partition_by = {"field": "_cta_loaded_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_payroll_hashid'
) }}

-- Final base SQL model
-- depends_on: {{ ref('payroll_cta1') }}

select
    `Company_Code`,
    `Payroll_Name`,
    `File_Number`,
    `Associate_ID`,
    `Pay_Date`,
    `Job_Title_Description`,
    `Home_Department_Code`,
    `Home_Department_Description`,
    `Worked_In_Department`,
    `Worked_In_Department_Description`,
    `Distribution_Number`,
    `Gross_Pay_USD`,
    `Net_Pay_USD`,
    `Take_Home_USD`,
    `Regular_Hours_Total`,
    `Overtime_Hours_Total`,
    `Additional_Hours___HOL`,
    `Additional_Hours___SIK`,
    `Additional_Hours___PTO`,
    `Additional_Hours___COV`,
    `Total_Hours`,
    `Regular_Earnings_Total_USD`,
    `Overtime_Earnings_Total_USD`,
    `Additional_Earnings___HOL_USD`,
    `SIK___SICK_LEAVE_Earnings_USD`,
    `PTO_Earnings_USD`,
    `Additional_Earnings___COV_USD`,
    `1FA___FF_FMLA_Earnings_USD`,
    `1FE___FF_PSL_EE_Earnings_USD`,
    `1FF___FF_PSL_FAM_Earnings_USD`,
    `BN___BONUS_Earnings_USD`,
    `DEV___Phone_Bonus_Earnings_USD`,
    `DIB___DRIVER_Earnings_USD`,
    `PER___PERSONAL_Earnings_USD`,
    `PPE___PRPD_Earnings_Earnings_USD`,
    `RF1___REFERRAL_Earnings_USD`,
    `UPT___UNPAID_TIME_Earnings_USD`,
    `VAC___VACATION_Earnings_USD`,
    `Total_Deductions_USD`,
    `Family_Leave_Insurance___Employee_Tax_USD`,
    `Federal_Income___Employee_Tax_USD`,
    `Lived_In_Local___Employee_Tax_USD`,
    `Lived_In_State___Employee_Tax_USD`,
    `Local_4___Employee_Tax_USD`,
    `Local_5___Employee_Tax_USD`,
    `Medical_Leave_Insurance___Employee_Tax_USD`,
    `Medicare___Employee_Tax_USD`,
    `Medicare_Adjust___Employee_Tax_USD`,
    `Medicare_Surtax_Adjust___Employee_Tax_USD`,
    `School_District___Employee_Tax_USD`,
    `SDI___Employee_Tax_USD`,
    `Social_Security___Employee_Tax_USD`,
    `SUI___Employee_Tax_USD`,
    `SUI_SDI___Employee_Tax_USD`,
    `Transit___Employee_Tax_USD`,
    `Worked_In_Local___Employee_Tax_USD`,
    `Worked_In_State___Employee_Tax_USD`,
    `Workers_Comp_Assessment___Employee_Tax_USD`,
    `Family_Leave_Insurance___Employer_Tax_USD`,
    `FUTA___Employer_Tax_USD`,
    `Lived_in_Local___Employer_Tax_USD`,
    `Lived_in_State___Employer_Tax_USD`,
    `Local_4___Employer_Tax_USD`,
    `Local_5___Employer_Tax_USD`,
    `Medical_Leave_Insurance___Employer_Tax_USD`,
    `Medicare___Employer_Tax_USD`,
    `MTA___Employer_Tax_USD`,
    `School_District___Employer_Tax_USD`,
    `SDI___Employer_Tax_USD`,
    `Social_Security___Employer_Tax_USD`,
    `SUI___Employer_Tax_USD`,
    `SUI_SDI___Employer_Tax_USD`,
    `Transit___Employer_Tax_USD`,
    `Worked_in_Local___Employer_Tax_USD`,
    `Worked_in_State___Employer_Tax_USD`,
    `Workers_Comp_Assessment___Employer_Tax_USD`,
    `Void_Check_Indicator`,
    `Check_Voucher_Code`,
    `Check_Voucher_Number`,
    `_payroll_hashid`,
    `_cta_loaded_at`
from {{ ref('payroll_cta1') }}
{% if is_incremental() %}
where timestamp_trunc(_airbyte_emitted_at, day) in ({{ partitions_to_replace | join(',') }})
{% endif %}
