
-- depends_on: {{ source('cta', 'participations_base') }}
select
    _airbyte_participations_hashid,
    max(id) as id,
    max(status) as status,
    max(user_id) as user_id,
    max(attended) as attended,
    max(end_date) as end_date,
    max(event_id) as event_id,
    max(event_type) as event_type,
    max(start_date) as start_date,
    max(timeslot_id) as timeslot_id,
    max(created_date) as created_date,
    max(modified_date) as modified_date,
    max(referrer__url) as referrer__url,
    max(affiliation_id) as affiliation_id,
    max(email_at_signup) as email_at_signup,
    max(event_type_name) as event_type_name,
    max(organization_id) as organization_id,
    max(user__given_name) as user__given_name,
    max(affiliation__name) as affiliation__name,
    max(affiliation__slug) as affiliation__slug,
    max(override_end_date) as override_end_date,
    max(user__family_name) as user__family_name,
    max(user__postal_code) as user__postal_code,
    max(organization__name) as organization__name,
    max(organization__slug) as organization__slug,
    max(referrer__utm_term) as referrer__utm_term,
    max(user__blocked_date) as user__blocked_date,
    max(user__phone_number) as user__phone_number,
    max(custom_field_values) as custom_field_values,
    max(override_start_date) as override_start_date,
    max(user__email_address) as user__email_address,
    max(user__modified_date) as user__modified_date,
    max(given_name_at_signup) as given_name_at_signup,
    max(referrer__utm_medium) as referrer__utm_medium,
    max(referrer__utm_source) as referrer__utm_source,
    max(family_name_at_signup) as family_name_at_signup,
    max(postal_code_at_signup) as postal_code_at_signup,
    max(referrer__utm_content) as referrer__utm_content,
    max(phone_number_at_signup) as phone_number_at_signup,
    max(referrer__utm_campaign) as referrer__utm_campaign,
    max(experience_feedback_text) as experience_feedback_text,
    max(experience_feedback_type) as experience_feedback_type,
    max(_airbyte_raw_id) as _airbyte_raw_id,
    max(_airbyte_extracted_at) as _airbyte_extracted_at
from {{ source("cta", "participations_base") }}
group by _airbyte_participations_hashid
