name: default
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["{{ env_var('SYNC_NAME') }}/models"]
packages-install-path: "dbt-packages"

models:
  +persist_docs:
    relation: true
    columns: true
  elementary:
    schema: "elementary"
    database:  "{{ env_var('CTA_PROJECT_ID') }}"
  default:
    0_ctes:
      +tags: 
        - normalization
      +materialized: ephemeral
    1_cta_full_refresh:
      +tags: 
        - normalization
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +on_schema_change: sync_all_columns
      +full_refresh: false
    1_cta_incremental:
      +tags:
        - normalization
      +materialized: incremental
      +on_schema_change: sync_all_columns
    2_p2p_mapping:
      +tags: 
        - mapping
      +materialized: table