version: 2
sources:
- name: cta_raw
  database: airbyte_internal
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_assignment' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_assignment_feedback' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_campaign' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_campaign_admin' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_campaign_contact' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_canned_response' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_interaction_step' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_invite' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_job_request' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_knex_migrations' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_knex_migrations_lock' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_log' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_message' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_opt_out' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_organization' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_organization_contact' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_owned_phone_number' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_pending_message_part' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_question_response' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_tag' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_tag_campaign_contact' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_tag_canned_response' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_user' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_user_cell' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_user_organization' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_zip_code' }}"
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_data
        tests:
          - not_null

- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: assignment_base
    columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
  - name: assignment_feedback_base
  - name: campaign_base
  - name: campaign_admin_base
  - name: campaign_contact_base
  - name: canned_response_base
  - name: interaction_step_base
  - name: invite_base
  - name: job_request_base
  - name: knex_migrations_base
  - name: knex_migrations_lock_base
  - name: log_base
  - name: message_base
  - name: opt_out_base
  - name: organization_base
  - name: organization_contact_base
  - name: owned_phone_number_base
  - name: pending_message_part_base
  - name: question_response_base
  - name: tag_base
  - name: tag_campaign_contact_base
  - name: tag_canned_response_base
  - name: user_base
  - name: user_cell_base
  - name: user_organization_base
  - name: zip_code_base
