version: 2
sources:
- name: cta
  database: "{{env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables: "{{ var('source_tables') }}"
  # TODO(): note in README what the canonical source tables are
- name: partner
  database: "{{ env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables: "{{ var('source_tables') }}"