{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id'
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('ads_insights_overall_ab1') }}
select
    cast(cpc as {{ dbt_utils.type_float() }}) as cpc,
    cast(cpm as {{ dbt_utils.type_float() }}) as cpm,
    cast(cpp as {{ dbt_utils.type_float() }}) as cpp,
    cast(ctr as {{ dbt_utils.type_float() }}) as ctr,
    cast(ad_id as {{ dbt_utils.type_string() }}) as ad_id,
    cast(reach as {{ dbt_utils.type_bigint() }}) as reach,
    cast(spend as {{ dbt_utils.type_float() }}) as spend,
    cast(clicks as {{ dbt_utils.type_bigint() }}) as clicks,
    cast(labels as {{ dbt_utils.type_string() }}) as labels,
    actions,
    cast(ad_name as {{ dbt_utils.type_string() }}) as ad_name,
    cast(adset_id as {{ dbt_utils.type_string() }}) as adset_id,
    cast(location as {{ dbt_utils.type_string() }}) as location,
    cast(wish_bid as {{ dbt_utils.type_float() }}) as wish_bid,
    cast({{ empty_string_to_null('date_stop') }} as {{ type_date() }}) as date_stop,
    cast(frequency as {{ dbt_utils.type_float() }}) as frequency,
    cast(objective as {{ dbt_utils.type_string() }}) as objective,
    cast(account_id as {{ dbt_utils.type_string() }}) as account_id,
    cast(adset_name as {{ dbt_utils.type_string() }}) as adset_name,
    cast({{ empty_string_to_null('date_start') }} as {{ type_date() }}) as date_start,
    cast(unique_ctr as {{ dbt_utils.type_float() }}) as unique_ctr,
    cast(auction_bid as {{ dbt_utils.type_float() }}) as auction_bid,
    cast(buying_type as {{ dbt_utils.type_string() }}) as buying_type,
    cast(campaign_id as {{ dbt_utils.type_string() }}) as campaign_id,
    conversions,
    cast(impressions as {{ dbt_utils.type_bigint() }}) as impressions,
    website_ctr,
    cast(account_name as {{ dbt_utils.type_string() }}) as account_name,
    cast({{ empty_string_to_null('created_time') }} as {{ type_date() }}) as created_time,
    cast(social_spend as {{ dbt_utils.type_float() }}) as social_spend,
    cast({{ empty_string_to_null('updated_time') }} as {{ type_date() }}) as updated_time,
    action_values,
    cast(age_targeting as {{ dbt_utils.type_string() }}) as age_targeting,
    cast(campaign_name as {{ dbt_utils.type_string() }}) as campaign_name,
    purchase_roas,
    cast(unique_clicks as {{ dbt_utils.type_bigint() }}) as unique_clicks,
    unique_actions,
    cast(full_view_reach as {{ dbt_utils.type_float() }}) as full_view_reach,
    outbound_clicks,
    cast(quality_ranking as {{ dbt_utils.type_string() }}) as quality_ranking,
    cast(account_currency as {{ dbt_utils.type_string() }}) as account_currency,
    ad_click_actions,
    cast(gender_targeting as {{ dbt_utils.type_string() }}) as gender_targeting,
    conversion_values,
    cost_per_ad_click,
    cost_per_thruplay,
    cast(optimization_goal as {{ dbt_utils.type_string() }}) as optimization_goal,
    cast(inline_link_clicks as {{ dbt_utils.type_bigint() }}) as inline_link_clicks,
    video_play_actions,
    cast(attribution_setting as {{ dbt_utils.type_string() }}) as attribution_setting,
    cost_per_conversion,
    outbound_clicks_ctr,
    cast(canvas_avg_view_time as {{ dbt_utils.type_float() }}) as canvas_avg_view_time,
    cost_per_action_type,
    ad_impression_actions,
    catalog_segment_value,
    cast(cost_per_unique_click as {{ dbt_utils.type_float() }}) as cost_per_unique_click,
    cast(full_view_impressions as {{ dbt_utils.type_float() }}) as full_view_impressions,
    cast(inline_link_click_ctr as {{ dbt_utils.type_float() }}) as inline_link_click_ctr,
    website_purchase_roas,
    cast(estimated_ad_recallers as {{ dbt_utils.type_float() }}) as estimated_ad_recallers,
    cast(inline_post_engagement as {{ dbt_utils.type_bigint() }}) as inline_post_engagement,
    cast(unique_link_clicks_ctr as {{ dbt_utils.type_float() }}) as unique_link_clicks_ctr,
    unique_outbound_clicks,
    cast(auction_competitiveness as {{ dbt_utils.type_float() }}) as auction_competitiveness,
    cast(canvas_avg_view_percent as {{ dbt_utils.type_float() }}) as canvas_avg_view_percent,
    catalog_segment_actions,
    cast(conversion_rate_ranking as {{ dbt_utils.type_string() }}) as conversion_rate_ranking,
    converted_product_value,
    cost_per_outbound_click,
    cast(engagement_rate_ranking as {{ dbt_utils.type_string() }}) as engagement_rate_ranking,
    cast(estimated_ad_recall_rate as {{ dbt_utils.type_float() }}) as estimated_ad_recall_rate,
    mobile_app_purchase_roas,
    video_play_curve_actions,
    cast(unique_inline_link_clicks as {{ dbt_utils.type_bigint() }}) as unique_inline_link_clicks,
    video_p25_watched_actions,
    video_p50_watched_actions,
    video_p75_watched_actions,
    video_p95_watched_actions,
    cast(auction_max_competitor_bid as {{ dbt_utils.type_float() }}) as auction_max_competitor_bid,
    converted_product_quantity,
    cost_per_15_sec_video_view,
    cast(cost_per_inline_link_click as {{ dbt_utils.type_float() }}) as cost_per_inline_link_click,
    unique_outbound_clicks_ctr,
    video_p100_watched_actions,
    video_time_watched_actions,
    cost_per_unique_action_type,
    cast(unique_inline_link_click_ctr as {{ dbt_utils.type_float() }}) as unique_inline_link_click_ctr,
    video_15_sec_watched_actions,
    video_30_sec_watched_actions,
    cost_per_unique_outbound_click,
    video_avg_time_watched_actions,
    cast(cost_per_estimated_ad_recallers as {{ dbt_utils.type_float() }}) as cost_per_estimated_ad_recallers,
    cast(cost_per_inline_post_engagement as {{ dbt_utils.type_float() }}) as cost_per_inline_post_engagement,
    cast(cost_per_unique_inline_link_click as {{ dbt_utils.type_float() }}) as cost_per_unique_inline_link_click,
    cast(instant_experience_clicks_to_open as {{ dbt_utils.type_float() }}) as instant_experience_clicks_to_open,
    cast(estimated_ad_recallers_lower_bound as {{ dbt_utils.type_float() }}) as estimated_ad_recallers_lower_bound,
    cast(estimated_ad_recallers_upper_bound as {{ dbt_utils.type_float() }}) as estimated_ad_recallers_upper_bound,
    cast(instant_experience_clicks_to_start as {{ dbt_utils.type_float() }}) as instant_experience_clicks_to_start,
    instant_experience_outbound_clicks,
    video_play_retention_graph_actions,
    cost_per_2_sec_continuous_video_view,
    cast(estimated_ad_recall_rate_lower_bound as {{ dbt_utils.type_float() }}) as estimated_ad_recall_rate_lower_bound,
    cast(estimated_ad_recall_rate_upper_bound as {{ dbt_utils.type_float() }}) as estimated_ad_recall_rate_upper_bound,
    video_play_retention_0_to_15s_actions,
    video_continuous_2_sec_watched_actions,
    video_play_retention_20_to_60s_actions,
    cast(qualifying_question_qualify_answer_rate as {{ dbt_utils.type_float() }}) as qualifying_question_qualify_answer_rate,
    catalog_segment_value_omni_purchase_roas,
    catalog_segment_value_mobile_purchase_roas,
    catalog_segment_value_website_purchase_roas,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('ads_insights_overall_ab1') }}
-- ads_insights
where 1 = 1
{{ incremental_clause('_airbyte_emitted_at') }}

