version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
    - name: _airbyte_raw_affiliations
    - name: _airbyte_raw_event_co_hosts
    - name: _airbyte_raw_event_tags
    - name: _airbyte_raw_events
    - name: _airbyte_raw_organizations
    - name: _airbyte_raw_participations
    - name: _airbyte_raw_sms_opt_ins
    - name: _airbyte_raw_timeslots
    - name: _airbyte_raw_users
    - name: _airbyte_raw_van_events
    - name: _airbyte_raw_van_locations
    - name: _airbyte_raw_van_persons
    - name: _airbyte_raw_van_shifts
    - name: _airbyte_raw_van_signups
    - name: affiliations_base
    - name: event_co_hosts_base
    - name: event_tags_base
    - name: events_base
    - name: organizations_base
    - name: participations_base
    - name: sms_opt_ins_base
    - name: timeslots_base
    - name: users_base
    - name: van_events_base
    - name: van_locations_base
    - name: van_persons_base
    - name: van_shifts_base
    - name: van_signups_base


- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID') }}"
  tables:
    - name: affiliations
    - name: event_co_hosts
    - name: event_tags
    - name: events
    - name: organizations
    - name: participations
    - name: sms_opt_ins
    - name: timeslots
    - name: users
    - name: van_events
    - name: van_locations
    - name: van_persons
    - name: van_shifts
    - name: van_signups