name: default
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["{{ env_var('SYNC_NAME') }}/models"]
packages-install-path: "dbt-packages"

models:
  default:
    0_ctes:
      +tags: 
        - cta
      +materialized: ephemeral
    0_ctes_dev: #useful for debugging sometimes (eg, some field is being cast to the wrong data type and you need to figure out which)
      +tags: 
        - cta
      +materialized: table
    1_cta_base: # this is semantically equivalent to `1_cta_full_refresh` but the ambiguous name was causing confusion!
    #TODO(): switch all models to use `1_cta_full_refresh` and delete `1_cta_base` from this file
    #...but don't break anything in the process pls
      +tags: 
        - cta
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +on_schema_change: sync_all_columns
      +full_refresh: false
    1_cta_full_refresh: # USE THIS for full-refresh-overwrite models going forward!
      +tags: 
        - cta
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +on_schema_change: sync_all_columns
      +full_refresh: false # this avoids dropping-and-rebuilding tables in this model, which would break the downstream matviews
    1_cta_tables:
      +tags:
        - cta
      +materialized: table
    1_cta_incremental:
      +tags:
        - cta
      +materialized: incremental
      +on_schema_change: sync_all_columns
    2_partner_matviews:
      +tags: 
        - partner
      +materialized: materialized_view
      +auto_refresh: true
      +refresh_interval_minutes: 1440
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
    2_partner_tables:
      +tags: 
        - partner
      +materialized: table
    3_partner_views:
      +tags: 
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"

    # For the rare instances when raw data are synced directly into the partner project:
    0_partner_ctes:
      +tags: 
        - partner
      +materialized: ephemeral
    1_partner_tables:
      +tags:
        - partner
      +materialized: table
    1_partner_incremental:
      +tags:
        - partner
      +materialized: incremental
      +on_schema_change: sync_all_columns