name: default
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["{{ env_var('SYNC_NAME') }}/models"]
packages-install-path: "dbt-packages"
vars:
  campaigns_raw: _airbyte_raw_campaigns
  campaigns_base: campaigns_base
  campaigns: campaigns

models:
  +persist_docs:
    relation: true
    columns: true
  elementary:
    schema: "elementary"
    database:  "{{ env_var('CTA_PROJECT_ID') }}"
  default:
    0_ctes:
      +tags: 
        - cta
      +materialized: ephemeral
    1_cta_full_refresh:
      +tags: 
        - cta
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +on_schema_change: sync_all_columns
      #+full_refresh: true
    1_cta_incremental:
      +tags:
        - cta
      +materialized: incremental
      +on_schema_change: sync_all_columns
    2_partner_matviews:
      +tags: 
        - partner
      +materialized: materialized_view
      +auto_refresh: false
      +refresh_interval_minutes: 1440
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
    3_partner_views:
      +tags: 
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"

    # These two models are specifically for google_ads,
    # which delivers raw data to the partner project instead of CTA:
    0_partner_ctes:
      +tags: 
        - partner
      +materialized: ephemeral
    1_partner_incremental:
      +tags:
        - partner
      +materialized: incremental
      +on_schema_change: sync_all_columns

    # for the /bigquery_monitoring project (no other syncs use these models)
    0_staging:
      +tags:
        - partner # adding this tag so we can run /bigquery_monitoring from DMDF
      +materialized: ephemeral
    1_intermediate:
      +tags:
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
    2_reporting:
      +tags:
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"

    # for testing
    0_ctes_dev:
      +tags: 
        - cta
      +materialized: table