name: default
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["{{ env_var('SYNC_NAME') }}/models"]
packages-install-path: "dbt-packages"

models:
  elementary:
    schema: "elementary"
    database:  "{{ env_var('CTA_PROJECT_ID') }}"
  default:
    0_ctes:
      +tags: 
        - cta
      +materialized: ephemeral
    0_ctes_dev: #useful for debugging sometimes (eg, some field is being cast to the wrong data type and you need to figure out which)
      +tags: 
        - cta
      +materialized: table
    1_cta_full_refresh:
      +tags: 
        - cta
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +on_schema_change: sync_all_columns
      +full_refresh: false
    1_cta_tables:
      +tags:
        - cta
      +materialized: table
    1_cta_incremental:
      +tags:
        - cta
      +materialized: incremental
      +on_schema_change: sync_all_columns
    2_partner_matviews:
      +tags: 
        - partner
      +materialized: materialized_view
      +auto_refresh: false
      +refresh_interval_minutes: 1440
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
    2_partner_tables:
      +tags: 
        - partner
      +materialized: table
    3_partner_views:
      +tags: 
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"

    # For the rare instances when raw data are synced directly into the partner project:
    0_partner_ctes:
      +tags: 
        - partner
      +materialized: ephemeral
    1_partner_tables:
      +tags:
        - partner
      +materialized: table
    1_partner_incremental:
      +tags:
        - partner
      +materialized: incremental
      +on_schema_change: sync_all_columns

    # for the /monitoring project
    0_staging:
      +materialized: view
    1_intermediate:
      +materialized: view
    2_reporting:
      +materialized: view
