name: default
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["{{ env_var('SYNC_NAME') }}/models"]
packages-install-path: "dbt-packages"

vars:
  disable_run_results: "false" 
  disable_tests_results: "false" 
  disable_dbt_artifacts_autoupload: "false"
  disable_dbt_invocation_autoupload: "false"

models:
  +persist_docs:
    relation: true
    columns: true
  elementary:
    schema: "elementary"
    database:  "{{ env_var('CTA_PROJECT_ID') }}"
    +enabled: false
  default:
    0_ctes:
      +tags: 
        - cta
      +materialized: ephemeral
    1_cta_full_refresh:
      +tags: 
        - cta
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +on_schema_change: sync_all_columns
      +full_refresh: false
      +pre-hook: "TRUNCATE TABLE {{ this }};"
      +labels:
        data_object_type: cta_base_table
        sync_mode: full_refresh
    1_cta_incremental:
      +tags:
        - cta
      +materialized: incremental
      +on_schema_change: sync_all_columns
      +labels:
        data_object_type: cta_base_table
        sync_mode: incremental
    2_cta_delivery: # for delivery via Analytics Hub subscriptions
      +tags: 
        - cta_delivery
      +materialized: table
      +full_refresh: true
      +labels:
        data_object_type: cta_delivery_table
        sync_mode: full_refresh
    2_partner_matviews: # for delivery via materialized views
      +tags: 
        - partner
      +materialized: materialized_view
      +auto_refresh: false
      +refresh_interval_minutes: 1440
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
      +labels:
        data_object_type: partner_materialized_view
        origin: cta
    3_partner_views:
      +tags: 
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
      +labels:
        data_object_type: partner_materialized_view
        origin: cta

    # These two models are specifically for google_ads,
    # which delivers raw data to the partner project instead of CTA:
    0_partner_ctes:
      +tags: 
        - partner
      +materialized: ephemeral
    1_partner_incremental:
      +tags:
        - partner
      +materialized: incremental
      +on_schema_change: sync_all_columns
      +labels:
        data_object_type: partner_table
        sync_mode: incremental
        origin: cta

    # for the /bigquery_monitoring project (no other syncs use these models)
    0_staging:
      +tags:
        - partner # adding this tag so we can run /bigquery_monitoring from DMDF
      +materialized: ephemeral
    1_intermediate:
      +tags:
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
    2_reporting:
      +tags:
        - partner
      +materialized: view
      +grant_access_to:
        - project: "{{ env_var('CTA_PROJECT_ID') }}"
          dataset: "{{ env_var('CTA_DATASET_ID') }}"
      +labels:
        data_object_type: partner_view
        origin: cta