config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true

default:
  outputs:
    default:
      type: bigquery
      method: oauth
      priority: batch
      threads: 4
      project: default
      dataset: default
    cta:
      project: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
      dataset: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
      location: US
      method: oauth
      priority: batch
      threads: 4
      type: bigquery
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 1200
      job_retries: 5
      job_retry_deadline_seconds: 1200
    cta_delivery:
      project: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
      dataset: "{{ env_var('DELIVERY_DATASET_ID', 'not-set') }}"
      location: US
      method: oauth
      priority: batch
      threads: 4
      type: bigquery
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 1200
      job_retries: 5
      job_retry_deadline_seconds: 1200
    cta_1_thread:
      project: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
      dataset: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
      location: US
      method: oauth
      priority: batch
      threads: 1
      type: bigquery
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 1200
      job_retries: 5
      job_retry_deadline_seconds: 1200
    partner:
      project: "{{ env_var('PARTNER_PROJECT_ID', 'not-set') }}"
      dataset: "{{ env_var('PARTNER_DATASET_ID', 'not-set') }}"
      location: US
      method: oauth
      priority: batch
      threads: 1
      type: bigquery
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 600
      job_retries: 5
      job_retry_deadline_seconds: 1200
elementary:
  outputs:
    default:
      type: bigquery
      method: oauth
      project: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
      dataset: elementary
      threads: 4 
