{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = "_airbyte_raw_id"
) }}

-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref("events_ab2") }}
select
    tmp.*,
    to_hex(
        md5(
            cast(
                concat(
                    coalesce(cast(id as string), ''),
                    '-',
                    coalesce(cast(title as string), ''),
                    '-',
                    coalesce(cast(summary as string), ''),
                    '-',
                    coalesce(cast(owner_id as string), ''),
                    '-',
                    coalesce(cast(timezone as string), ''),
                    '-',
                    coalesce(cast(van_name as string), ''),
                    '-',
                    coalesce(cast(creator_id as string), ''),
                    '-',
                    coalesce(cast(event_type as string), ''),
                    '-',
                    coalesce(cast(is_virtual as string), ''),
                    '-',
                    coalesce(cast(visibility as string), ''),
                    '-',
                    coalesce(cast(browser_url as string), ''),
                    '-',
                    coalesce(cast(description as string), ''),
                    '-',
                    coalesce(cast(created_date as string), ''),
                    '-',
                    coalesce(cast(deleted_date as string), ''),
                    '-',
                    coalesce(cast(contact__name as string), ''),
                    '-',
                    coalesce(cast(high_priority as string), ''),
                    '-',
                    coalesce(cast(location__lat as string), ''),
                    '-',
                    coalesce(cast(location__lon as string), ''),
                    '-',
                    coalesce(cast(modified_date as string), ''),
                    '-',
                    coalesce(cast(referrer__url as string), ''),
                    '-',
                    coalesce(cast(reviewed_date as string), ''),
                    '-',
                    coalesce(cast(reviewed_by_id as string), ''),
                    '-',
                    coalesce(cast(approval_status as string), ''),
                    '-',
                    coalesce(cast(location__venue as string), ''),
                    '-',
                    coalesce(cast(organization_id as string), ''),
                    '-',
                    coalesce(cast(location__region as string), ''),
                    '-',
                    coalesce(cast(event_campaign_id as string), ''),
                    '-',
                    coalesce(cast(location__country as string), ''),
                    '-',
                    coalesce(cast(owner__given_name as string), ''),
                    '-',
                    coalesce(cast(registration_mode as string), ''),
                    '-',
                    coalesce(cast(rejection_message as string), ''),
                    '-',
                    coalesce(cast(featured_image_url as string), ''),
                    '-',
                    coalesce(cast(location__locality as string), ''),
                    '-',
                    coalesce(cast(organization__name as string), ''),
                    '-',
                    coalesce(cast(organization__slug as string), ''),
                    '-',
                    coalesce(cast(owner__family_name as string), ''),
                    '-',
                    coalesce(cast(owner__postal_code as string), ''),
                    '-',
                    coalesce(cast(referrer__utm_term as string), ''),
                    '-',
                    coalesce(cast(virtual_action_url as string), ''),
                    '-',
                    coalesce(cast(accessibility_notes as string), ''),
                    '-',
                    coalesce(cast(creator__given_name as string), ''),
                    '-',
                    coalesce(cast(organization__state as string), ''),
                    '-',
                    coalesce(cast(owner__phone_number as string), ''),
                    '-',
                    coalesce(cast(accessibility_status as string), ''),
                    '-',
                    coalesce(cast(creator__family_name as string), ''),
                    '-',
                    coalesce(cast(creator__postal_code as string), ''),
                    '-',
                    coalesce(cast(event_campaign__slug as string), ''),
                    '-',
                    coalesce(cast(location__is_private as string), ''),
                    '-',
                    coalesce(cast(owner__email_address as string), ''),
                    '-',
                    coalesce(cast(owner__modified_date as string), ''),
                    '-',
                    coalesce(cast(referrer__utm_medium as string), ''),
                    '-',
                    coalesce(cast(referrer__utm_source as string), ''),
                    '-',
                    coalesce(cast(contact__phone_number as string), ''),
                    '-',
                    coalesce(cast(creator__phone_number as string), ''),
                    '-',
                    coalesce(cast(location__postal_code as string), ''),
                    '-',
                    coalesce(cast(referrer__utm_content as string), ''),
                    '-',
                    coalesce(cast(contact__email_address as string), ''),
                    '-',
                    coalesce(cast(creator__email_address as string), ''),
                    '-',
                    coalesce(cast(creator__modified_date as string), ''),
                    '-',
                    coalesce(cast(organization__district as string), ''),
                    '-',
                    coalesce(cast(referrer__utm_campaign as string), ''),
                    '-',
                    coalesce(cast(location__modified_date as string), ''),
                    '-',
                    coalesce(cast(organization__race_type as string), ''),
                    '-',
                    coalesce(cast(reviewed_by__given_name as string), ''),
                    '-',
                    coalesce(cast(location__address_line_1 as string), ''),
                    '-',
                    coalesce(cast(location__address_line_2 as string), ''),
                    '-',
                    coalesce(cast(reviewed_by__family_name as string), ''),
                    '-',
                    coalesce(cast(reviewed_by__postal_code as string), ''),
                    '-',
                    coalesce(cast(created_by_volunteer_host as string), ''),
                    '-',
                    coalesce(cast(reviewed_by__phone_number as string), ''),
                    '-',
                    coalesce(cast(reviewed_by__email_address as string), ''),
                    '-',
                    coalesce(cast(reviewed_by__modified_date as string), ''),
                    '-',
                    coalesce(cast(organization__modified_date as string), ''),
                    '-',
                    coalesce(cast(location__state_leg_district as string), ''),
                    '-',
                    coalesce(cast(organization__candidate_name as string), ''),
                    '-',
                    coalesce(cast(organization__is_coordinated as string), ''),
                    '-',
                    coalesce(cast(organization__is_independent as string), ''),
                    '-',
                    coalesce(cast(location__state_senate_district as string), ''),
                    '-',
                    coalesce(cast(location__congressional_district as string), ''),
                    '-',
                    coalesce(cast(organization__is_primary_campaign as string), '')
                ) as string
            )
        )
    ) as _airbyte_events_hashid
from {{ ref("events_ab2") }} as tmp
-- events
where 1 = 1
