{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'events') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    notes,
    extras,
    created_at,
    description,
    type,
    location_id,
    event_type_id,
    public,
    updated_at,
    turf_id,
    public_page_header_data,
    public_page_header_map_data,
    id,
    slug,
    campaign_id,
    public_page_header_file_locator,
    invited_count,
    no_show_count,
    end_time,
    public_settings,
    created_by_user_id,
    start_time,
    first_occurrence_id,
    organization_id,
    name,
    walk_in_count,
    attended_count,
   {{ dbt_utils.surrogate_key([
     'notes',
    'extras',
    'description',
    'type',
    'location_id',
    'event_type_id',
    'public',
    'turf_id',
    'public_page_header_data',
    'public_page_header_map_data',
    'id',
    'slug',
    'campaign_id',
    'public_page_header_file_locator',
    'invited_count',
    'no_show_count',
    'public_settings',
    'created_by_user_id',
    'first_occurrence_id',
    'organization_id',
    'name',
    'walk_in_count',
    'attended_count'
    ]) }} as _airbyte_events_hashid
from {{ source('cta', 'events') }}
