
{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'events') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   id,
   url,
   name,
   slug,
   type,
   notes,
   extras,
   public,
   turf_id,
   end_time,
   url_label,
   created_at,
   start_time,
   updated_at,
   campaign_id,
   description,
   location_id,
   invited_count,
   no_show_count,
   walk_in_count,
   attended_count,
   organization_id,
   public_settings,
   created_by_user_id,
   first_occurrence_id,
   public_page_header_data,
   public_page_header_map_data,
   public_page_header_file_locator,
   {{ dbt_utils.surrogate_key([
     'id',
    'url',
    'name',
    'slug',
    'type',
    'notes',
    'extras',
    'public',
    'turf_id',
    'url_label',
    'campaign_id',
    'description',
    'location_id',
    'invited_count',
    'no_show_count',
    'walk_in_count',
    'attended_count',
    'organization_id',
    'public_settings',
    'created_by_user_id',
    'first_occurrence_id',
    'public_page_header_data',
    'public_page_header_map_data',
    'public_page_header_file_locator'
    ]) }} as _airbyte_events_hashid
from {{ source('cta', 'events') }}