
{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'landing_page_signups') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   mailing_county,
   state_api_submission_result,
   language,
   source,
   voting_state,
   finish_with_state,
   id,
   tracking_source,
   citizen,
   phone_type,
   mailing_street_address_two,
   built_via_api,
   organization_name,
   vr_app_status_datetime,
   opt_in_partner_sms,
   phone,
   started_registration_at,
   voting_city,
   voting_county,
   party,
   submitted_signature_to_state_api,
   status,
   has_state_license,
   mailing_street_address_one,
   date_of_birth,
   created_at,
   voting_street_address_two,
   voting_zipcode,
   mailing_zipcode,
   name_prefix,
   volunteer_for_rtv,
   updated_at,
   vr_app_status,
   vr_submission_mod,
   vr_submission_error,
   first_name,
   email,
   tracking_id,
   mailing_city,
   submitted_via_vendor_api,
   opt_in_sms,
   mailing_state,
   voting_street_address_one,
   race,
   name_suffix,
   has_ssn,
   opt_in_email,
   last_name,
   middle_name,
   ineligible_reason,
   volunteer_for_partner,
   source_id,
   vr_app_status_details,
   pre_registered,
   opt_in_partner_email,
   {{ dbt_utils.surrogate_key([
     'mailing_county',
    'state_api_submission_result',
    'language',
    'source',
    'voting_state',
    'finish_with_state',
    'id',
    'tracking_source',
    'citizen',
    'phone_type',
    'mailing_street_address_two',
    'built_via_api',
    'organization_name',
    'opt_in_partner_sms',
    'phone',
    'voting_city',
    'voting_county',
    'party',
    'submitted_signature_to_state_api',
    'status',
    'has_state_license',
    'mailing_street_address_one',
    'date_of_birth',
    'voting_street_address_two',
    'voting_zipcode',
    'mailing_zipcode',
    'name_prefix',
    'volunteer_for_rtv',
    'vr_app_status',
    'vr_submission_mod',
    'vr_submission_error',
    'first_name',
    'email',
    'tracking_id',
    'mailing_city',
    'submitted_via_vendor_api',
    'opt_in_sms',
    'mailing_state',
    'voting_street_address_one',
    'race',
    'name_suffix',
    'has_ssn',
    'opt_in_email',
    'last_name',
    'middle_name',
    'ineligible_reason',
    'volunteer_for_partner',
    'source_id',
    'vr_app_status_details',
    'pre_registered',
    'opt_in_partner_email'
    ]) }} as _airbyte_landing_page_signups_hashid
from {{ source('cta', 'landing_page_signups') }}