
{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'locations') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   id,
   city,
   name,
   email,
   geoid,
   hours,
   notes,
   score,
   state,
   county,
   extras,
   has_av,
   turf_id,
   zipcode,
   category,
   has_wifi,
   latitude,
   precinct,
   timezone,
   longitude,
   created_at,
   updated_at,
   venue_info,
   contact_name,
   phone_number,
   contact_email,
   contact_phone,
   has_projector,
   location_type,
   forms_per_hour,
   has_it_support,
   street_address,
   largest_turnout,
   rooms_available,
   has_hosted_event,
   maximum_occupancy,
   created_by_user_id,
   signatures_per_hour,
   parking_spots_available,
   primary_point_of_contact,
   registration_forms_count,
   has_public_transportation,
   {{ dbt_utils.surrogate_key([
     'id',
    'city',
    'name',
    'email',
    'geoid',
    'hours',
    'notes',
    'state',
    'county',
    'extras',
    'has_av',
    'turf_id',
    'zipcode',
    'category',
    'has_wifi',
    'precinct',
    'timezone',
    'venue_info',
    'contact_name',
    'phone_number',
    'contact_email',
    'contact_phone',
    'has_projector',
    'location_type',
    'has_it_support',
    'street_address',
    'largest_turnout',
    'rooms_available',
    'has_hosted_event',
    'maximum_occupancy',
    'created_by_user_id',
    'parking_spots_available',
    'primary_point_of_contact',
    'registration_forms_count',
    'has_public_transportation'
    ]) }} as _airbyte_locations_hashid
from {{ source('cta', 'locations') }}