{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'locations') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    street_address,
    primary_point_of_contact,
    notes,
    contact_phone,
    has_hosted_event,
    city,
    timezone,
    latitude,
    county,
    extras,
    created_at,
    forms_per_hour,
    has_it_support,
    contact_email,
    score,
    rooms_available,
    updated_at,
    turf_id,
    has_public_transportation,
    id,
    state,
    email,
    longitude,
    hours,
    contact_name,
    maximum_occupancy,
    largest_turnout,
    has_projector,
    parking_spots_available,
    venue_info,
    created_by_user_id,
    location_type,
    zipcode,
    precinct,
    geoid,
    name,
    phone_number,
    signatures_per_hour,
    has_wifi,
    registration_forms_count,
    has_av,
   {{ dbt_utils.surrogate_key([
     'street_address',
    'primary_point_of_contact',
    'notes',
    'contact_phone',
    'has_hosted_event',
    'city',
    'timezone',
    'county',
    'extras',
    'has_it_support',
    'contact_email',
    'rooms_available',
    'turf_id',
    'has_public_transportation',
    'id',
    'state',
    'email',
    'hours',
    'contact_name',
    'maximum_occupancy',
    'largest_turnout',
    'has_projector',
    'parking_spots_available',
    'venue_info',
    'created_by_user_id',
    'location_type',
    'zipcode',
    'precinct',
    'geoid',
    'name',
    'phone_number',
    'has_wifi',
    'registration_forms_count',
    'has_av'
    ]) }} as _airbyte_locations_hashid
from {{ source('cta', 'locations') }}
