{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'organizations') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    id,
    name,
    slug,
    notes,
    state,
    active,
    extras,
    issues,
    turf_id,
    website,
    zipcode,
    leader_id,
    address_id,
    created_at,
    updated_at,
    contact_name,
    mailing_city,
    phone_number,
    denominations,
    mailing_state,
    members_count,
    street_address,
    influence_level,
    mailing_zipcode,
    membership_type,
    organization_type,
    soft_member_count,
    created_by_user_id,
    mailing_street_address,
    membership_type_legacy,
   {{ dbt_utils.surrogate_key([
     'id',
    'city',
    'name',
    'slug',
    'notes',
    'state',
    'active',
    'extras',
    'issues',
    'turf_id',
    'website',
    'zipcode',
    'leader_id',
    'address_id',
    'contact_name',
    'mailing_city',
    'phone_number',
    'denominations',
    'mailing_state',
    'members_count',
    'street_address',
    'influence_level',
    'mailing_zipcode',
    'membership_type',
    'organization_type',
    'soft_member_count',
    'created_by_user_id',
    'mailing_street_address',
    'membership_type_legacy'
    ]) }} as _airbyte_organizations_hashid
from {{ source('cta', 'organizations') }}
