
{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'people') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   gender,
   ethnicity,
   email_source,
   interest_level,
   prefix,
   social_links,
   birth_date,
   call_stoppage,
   extras,
   created_at,
   denominations,
   external_id,
   issues,
   skills,
   search_terms,
   mailing_address_id,
   residential_address_id,
   suffix_name,
   primary_phone_number,
   requested_public_record_exception,
   updated_at,
   voter_source_id,
   receives_sms,
   leadership_score,
   registered_state,
   id,
   first_name,
   assigned_to_user_id,
   slug,
   voter_status,
   languages,
   primary_email_address,
   primary_language,
   last_name,
   middle_name,
   external_ids,
   ethnicities,
   registration_date,
   best_contact_method,
   party_id,
   creator_id,
   pronouns,
   work_organization_id,
   position,
   {{ dbt_utils.surrogate_key([
     'gender',
    'email_source',
    'interest_level',
    'prefix',
    'social_links',
    'birth_date',
    'call_stoppage',
    'extras',
    'denominations',
    'external_id',
    'issues',
    'skills',
    'search_terms',
    'mailing_address_id',
    'residential_address_id',
    'suffix_name',
    'primary_phone_number',
    'requested_public_record_exception',
    'voter_source_id',
    'receives_sms',
    'registered_state',
    'id',
    'first_name',
    'assigned_to_user_id',
    'slug',
    'voter_status',
    'languages',
    'primary_email_address',
    'primary_language',
    'last_name',
    'middle_name',
    'external_ids',
    'ethnicities',
    'registration_date',
    'best_contact_method',
    'party_id',
    'creator_id',
    'pronouns',
    'work_organization_id',
    'position'
    ]) }} as _airbyte_people_hashid
from {{ source('cta', 'people') }}