{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'petitions_signatures') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    city,
    county,
    extras,
    created_at,
    page_id,
    updated_at,
    line_number,
    id,
    state,
    first_name,
    email,
    petition_page_id,
    ostraka_external_id,
    last_name,
    address_two,
    middle_name,
    created_by_user_id,
    petition_packet_id,
    zipcode,
    voter_match_status,
    page_number,
    signature_date,
    address_one,
    signature_exists,
    reviewer_id,
    phone_number,
   {{ dbt_utils.surrogate_key([
     'city',
    'county',
    'extras',
    'page_id',
    'line_number',
    'id',
    'state',
    'first_name',
    'email',
    'petition_page_id',
    'ostraka_external_id',
    'last_name',
    'address_two',
    'middle_name',
    'created_by_user_id',
    'petition_packet_id',
    'zipcode',
    'voter_match_status',
    'page_number',
    'signature_date',
    'address_one',
    'signature_exists',
    'reviewer_id',
    'phone_number'
    ]) }} as _airbyte_petitions_signatures_hashid
from {{ source('cta', 'petitions_signatures') }}
