{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    schema = "_airbyte_default",
    tags = [ "nested-intermediate" ]
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('page_best_page_ab2') }}
select
    {{ dbt_utils.generate_surrogate_key([
        '_airbyte_page_hashid',
        'studio',
        array_to_string('food_styles'),
        'name_with_location_descriptor',
        'attire',
        boolean_to_string('is_published'),
        'about',
        'bio',
        boolean_to_string('has_whatsapp_number'),
        'displayed_message_response_time',
        boolean_to_string('is_permanently_closed'),
        'public_transit',
        'culinary_team',
        boolean_to_string('is_messenger_bot_get_started_enabled'),
        array_to_string('copyright_whitelisted_ig_partners'),
        'season',
        'store_location_descriptor',
        'id',
        'app_id',
        boolean_to_string('is_community_page'),
        'band_members',
        'mpg',
        boolean_to_string('offer_eligible'),
        'global_brand_page_name',
        'access_token',
        'mission',
        'phone',
        'release_date',
        'instant_articles_review_status',
        'global_brand_root_id',
        'store_number',
        'country_page_likes',
        'description_html',
        'leadgen_tos_acceptance_time',
        'plot_outline',
        'products',
        'new_like_count',
        boolean_to_string('promotion_eligible'),
        array_to_string('messenger_ads_default_quick_replies'),
        'place_type',
        'genre',
        'general_manager',
        'record_label',
        'store_code',
        'website',
        boolean_to_string('supports_donate_button_in_live_video'),
        'differently_open_offerings',
        'business',
        'founded',
        boolean_to_string('is_owned'),
        'privacy_info_url',
        boolean_to_string('is_verified'),
        'company_overview',
        'unread_message_count',
        'single_line_address',
        'artists_we_like',
        'promotion_ineligible_reason',
        'page_token',
        'checkins',
        array_to_string('pickup_options'),
        'written_by',
        'keywords',
        'overall_star_rating',
        'price_range',
        'pharma_safety_info',
        'impressum',
        'press_contact',
        'features',
        'band_interests',
        boolean_to_string('has_whatsapp_business_number'),
        'affiliation',
        'members',
        boolean_to_string('has_added_app'),
        'whatsapp_number',
        'current_location',
        'personal_interests',
        'fan_count',
        'talking_about_count',
        'merchant_review_status',
        'rating_count',
        boolean_to_string('is_messenger_platform_bot'),
        'name',
        'produced_by',
        boolean_to_string('is_webhooks_subscribed'),
        'booking_agent',
        'birthday',
        boolean_to_string('has_transitioned_to_new_page_experience'),
        boolean_to_string('can_checkin'),
        'link',
        'description',
        'merchant_id',
        'verification_status',
        'network',
        array_to_string('emails'),
        'directed_by',
        'personal_info',
        boolean_to_string('supports_instant_articles'),
        'influences',
        'display_subtext',
        'general_info',
        boolean_to_string('can_post'),
        'hours',
        'hometown',
        'temporary_status',
        'screenplay_by',
        boolean_to_string('is_chain'),
        'built',
        boolean_to_string('is_always_open'),
        array_to_string('delivery_and_pickup_option_info'),
        'messenger_ads_quick_replies_type',
        boolean_to_string('is_eligible_for_branded_content'),
        'schedule',
        boolean_to_string('is_unclaimed'),
        'awards',
        'followers_count',
        'recipient',
        'starring',
        array_to_string('messenger_ads_default_icebreakers'),
        'unseen_message_count',
        'category',
        'unread_notif_count',
        boolean_to_string('leadgen_tos_accepted'),
        'username',
        'were_here_count',
    ]) }} as _airbyte_best_page_hashid,
    tmp.*
from {{ ref('page_best_page_ab2') }} tmp
-- best_page at page/best_page
where 1 = 1

