{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    schema = "_airbyte_default",
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('page_ab1') }}
select
    cast(name_with_location_descriptor as {{ dbt_utils.type_string() }}) as name_with_location_descriptor,
    cast(attire as {{ dbt_utils.type_string() }}) as attire,
    cast(messaging_feature_status as {{ type_json() }}) as messaging_feature_status,
    cast(subscribed_apps as {{ type_json() }}) as subscribed_apps,
    cast(about as {{ dbt_utils.type_string() }}) as about,
    cast(videos as {{ type_json() }}) as videos,
    cast(published_posts as {{ type_json() }}) as published_posts,
    cast(cover as {{ type_json() }}) as cover,
    cast(culinary_team as {{ dbt_utils.type_string() }}) as culinary_team,
    cast(tagged as {{ type_json() }}) as tagged,
    cast(app_id as {{ dbt_utils.type_string() }}) as app_id,
    {{ cast_to_boolean('is_community_page') }} as is_community_page,
    cast(events as {{ type_json() }}) as events,
    cast(custom_labels as {{ type_json() }}) as custom_labels,
    {{ cast_to_boolean('offer_eligible') }} as offer_eligible,
    cast(messaging_feature_review as {{ type_json() }}) as messaging_feature_review,
    cast(global_brand_page_name as {{ dbt_utils.type_string() }}) as global_brand_page_name,
    cast(personas as {{ type_json() }}) as personas,
    cast(page_backed_instagram_accounts as {{ type_json() }}) as page_backed_instagram_accounts,
    cast(image_copyrights as {{ type_json() }}) as image_copyrights,
    cast(mission as {{ dbt_utils.type_string() }}) as mission,
    cast(release_date as {{ dbt_utils.type_string() }}) as release_date,
    cast(global_brand_root_id as {{ dbt_utils.type_string() }}) as global_brand_root_id,
    cast(connected_instagram_account as {{ type_json() }}) as connected_instagram_account,
    cast(store_number as {{ dbt_utils.type_bigint() }}) as store_number,
    cast(description_html as {{ dbt_utils.type_string() }}) as description_html,
    cast(instagram_accounts as {{ type_json() }}) as instagram_accounts,
    cast(albums as {{ type_json() }}) as albums,
    cast(nativeoffers as {{ type_json() }}) as nativeoffers,
    cast({{ empty_string_to_null('leadgen_tos_acceptance_time') }} as {{ type_timestamp_with_timezone() }}) as leadgen_tos_acceptance_time,
    cast(mini_shop_storefront as {{ type_json() }}) as mini_shop_storefront,
    cast(ads_posts as {{ type_json() }}) as ads_posts,
    cast(new_like_count as {{ dbt_utils.type_bigint() }}) as new_like_count,
    cast(genre as {{ dbt_utils.type_string() }}) as genre,
    cast(record_label as {{ dbt_utils.type_string() }}) as record_label,
    cast(start_info as {{ type_json() }}) as start_info,
    cast(store_code as {{ dbt_utils.type_string() }}) as store_code,
    cast(website as {{ dbt_utils.type_string() }}) as website,
    cast(global_brand_children as {{ type_json() }}) as global_brand_children,
    cast(canvas_elements as {{ type_json() }}) as canvas_elements,
    cast(differently_open_offerings as {{ dbt_utils.type_string() }}) as differently_open_offerings,
    cast(business as {{ dbt_utils.type_string() }}) as business,
    cast(founded as {{ dbt_utils.type_string() }}) as founded,
    {{ cast_to_boolean('is_owned') }} as is_owned,
    cast(privacy_info_url as {{ dbt_utils.type_string() }}) as privacy_info_url,
    cast(company_overview as {{ dbt_utils.type_string() }}) as company_overview,
    cast(unread_message_count as {{ dbt_utils.type_bigint() }}) as unread_message_count,
    cast(indexed_videos as {{ type_json() }}) as indexed_videos,
    cast(restaurant_specialties as {{ type_json() }}) as restaurant_specialties,
    cast(single_line_address as {{ dbt_utils.type_string() }}) as single_line_address,
    cast(promotion_ineligible_reason as {{ dbt_utils.type_string() }}) as promotion_ineligible_reason,
    cast(checkins as {{ dbt_utils.type_bigint() }}) as checkins,
    pickup_options,
    cast(written_by as {{ dbt_utils.type_string() }}) as written_by,
    cast(crosspost_whitelisted_pages as {{ type_json() }}) as crosspost_whitelisted_pages,
    cast(engagement as {{ type_json() }}) as engagement,
    cast(keywords as {{ dbt_utils.type_string() }}) as keywords,
    cast(overall_star_rating as {{ dbt_utils.type_float() }}) as overall_star_rating,
    cast(price_range as {{ dbt_utils.type_string() }}) as price_range,
    cast(pharma_safety_info as {{ dbt_utils.type_string() }}) as pharma_safety_info,
    cast(features as {{ dbt_utils.type_string() }}) as features,
    cast(affiliation as {{ dbt_utils.type_string() }}) as affiliation,
    cast(whatsapp_number as {{ dbt_utils.type_string() }}) as whatsapp_number,
    cast(current_location as {{ dbt_utils.type_string() }}) as current_location,
    cast(instagram_business_account as {{ type_json() }}) as instagram_business_account,
    cast(fan_count as {{ dbt_utils.type_bigint() }}) as fan_count,
    cast(talking_about_count as {{ dbt_utils.type_bigint() }}) as talking_about_count,
    cast(live_videos as {{ type_json() }}) as live_videos,
    cast(name as {{ dbt_utils.type_string() }}) as name,
    cast(produced_by as {{ dbt_utils.type_string() }}) as produced_by,
    {{ cast_to_boolean('is_webhooks_subscribed') }} as is_webhooks_subscribed,
    cast(booking_agent as {{ dbt_utils.type_string() }}) as booking_agent,
    cast(custom_user_settings as {{ type_json() }}) as custom_user_settings,
    {{ cast_to_boolean('can_checkin') }} as can_checkin,
    cast(roles as {{ type_json() }}) as roles,
    cast(description as {{ dbt_utils.type_string() }}) as description,
    cast(voip_info as {{ type_json() }}) as voip_info,
    cast(merchant_id as {{ dbt_utils.type_string() }}) as merchant_id,
    emails,
    cast(messenger_profile as {{ type_json() }}) as messenger_profile,
    {{ cast_to_boolean('supports_instant_articles') }} as supports_instant_articles,
    cast(ratings as {{ type_json() }}) as ratings,
    cast(display_subtext as {{ dbt_utils.type_string() }}) as display_subtext,
    cast(copyright_whitelisted_partners as {{ type_json() }}) as copyright_whitelisted_partners,
    cast(best_page as {{ type_json() }}) as best_page,
    cast(contact_address as {{ type_json() }}) as contact_address,
    cast(hours as {{ dbt_utils.type_string() }}) as hours,
    cast(hometown as {{ dbt_utils.type_string() }}) as hometown,
    cast(screenplay_by as {{ dbt_utils.type_string() }}) as screenplay_by,
    {{ cast_to_boolean('is_always_open') }} as is_always_open,
    delivery_and_pickup_option_info,
    cast(secondary_receivers as {{ type_json() }}) as secondary_receivers,
    cast(agencies as {{ type_json() }}) as agencies,
    cast(commerce_payouts as {{ type_json() }}) as commerce_payouts,
    cast(media_fingerprints as {{ type_json() }}) as media_fingerprints,
    {{ cast_to_boolean('is_eligible_for_branded_content') }} as is_eligible_for_branded_content,
    cast(schedule as {{ dbt_utils.type_string() }}) as schedule,
    cast(admin_notes as {{ type_json() }}) as admin_notes,
    {{ cast_to_boolean('is_unclaimed') }} as is_unclaimed,
    cast(followers_count as {{ dbt_utils.type_bigint() }}) as followers_count,
    cast(recipient as {{ dbt_utils.type_string() }}) as recipient,
    cast(location as {{ type_json() }}) as location,
    cast(video_lists as {{ type_json() }}) as video_lists,
    cast(username as {{ dbt_utils.type_string() }}) as username,
    cast(were_here_count as {{ dbt_utils.type_bigint() }}) as were_here_count,
    cast(studio as {{ dbt_utils.type_string() }}) as studio,
    cast(parking as {{ type_json() }}) as parking,
    cast(visitor_posts as {{ type_json() }}) as visitor_posts,
    food_styles,
    cast(restaurant_services as {{ type_json() }}) as restaurant_services,
    {{ cast_to_boolean('is_published') }} as is_published,
    cast(bio as {{ dbt_utils.type_string() }}) as bio,
    {{ cast_to_boolean('has_whatsapp_number') }} as has_whatsapp_number,
    cast(displayed_message_response_time as {{ dbt_utils.type_string() }}) as displayed_message_response_time,
    {{ cast_to_boolean('is_permanently_closed') }} as is_permanently_closed,
    cast(chat_plugin as {{ type_json() }}) as chat_plugin,
    cast(public_transit as {{ dbt_utils.type_string() }}) as public_transit,
    category_list,
    {{ cast_to_boolean('is_messenger_bot_get_started_enabled') }} as is_messenger_bot_get_started_enabled,
    cast(claimed_urls as {{ type_json() }}) as claimed_urls,
    copyright_whitelisted_ig_partners,
    cast(season as {{ dbt_utils.type_string() }}) as season,
    cast(store_location_descriptor as {{ dbt_utils.type_string() }}) as store_location_descriptor,
    cast(leadgen_tos_accepting_user as {{ type_json() }}) as leadgen_tos_accepting_user,
    cast(id as {{ dbt_utils.type_string() }}) as id,
    cast(band_members as {{ dbt_utils.type_string() }}) as band_members,
    cast(payment_options as {{ type_json() }}) as payment_options,
    cast(instant_articles_insights as {{ type_json() }}) as instant_articles_insights,
    cast(mpg as {{ dbt_utils.type_string() }}) as mpg,
    cast(shop_setup_status as {{ type_json() }}) as shop_setup_status,
    cast(access_token as {{ dbt_utils.type_string() }}) as access_token,
    cast(product_catalogs as {{ type_json() }}) as product_catalogs,
    cast(commerce_orders as {{ type_json() }}) as commerce_orders,
    cast(phone as {{ dbt_utils.type_string() }}) as phone,
    cast(instant_articles_review_status as {{ dbt_utils.type_string() }}) as instant_articles_review_status,
    cast(commerce_eligibility as {{ type_json() }}) as commerce_eligibility,
    cast(country_page_likes as {{ dbt_utils.type_bigint() }}) as country_page_likes,
    cast(video_copyright_rules as {{ type_json() }}) as video_copyright_rules,
    cast(tabs as {{ type_json() }}) as tabs,
    cast(plot_outline as {{ dbt_utils.type_string() }}) as plot_outline,
    cast(leadgen_forms as {{ type_json() }}) as leadgen_forms,
    cast(products as {{ dbt_utils.type_string() }}) as products,
    cast(commerce_transactions as {{ type_json() }}) as commerce_transactions,
    cast(blocked as {{ type_json() }}) as blocked,
    {{ cast_to_boolean('promotion_eligible') }} as promotion_eligible,
    messenger_ads_default_quick_replies,
    cast(place_type as {{ dbt_utils.type_string() }}) as place_type,
    cast(general_manager as {{ dbt_utils.type_string() }}) as general_manager,
    {{ cast_to_boolean('supports_donate_button_in_live_video') }} as supports_donate_button_in_live_video,
    {{ cast_to_boolean('is_verified') }} as is_verified,
    cast(scheduled_posts as {{ type_json() }}) as scheduled_posts,
    cast(picture as {{ type_json() }}) as picture,
    cast(artists_we_like as {{ dbt_utils.type_string() }}) as artists_we_like,
    cast(page_token as {{ dbt_utils.type_string() }}) as page_token,
    cast(rtb_dynamic_posts as {{ type_json() }}) as rtb_dynamic_posts,
    cast(parent_page as {{ type_json() }}) as parent_page,
    cast(call_to_actions as {{ type_json() }}) as call_to_actions,
    cast(posts as {{ type_json() }}) as posts,
    cast(photos as {{ type_json() }}) as photos,
    cast(impressum as {{ dbt_utils.type_string() }}) as impressum,
    cast(press_contact as {{ dbt_utils.type_string() }}) as press_contact,
    cast(band_interests as {{ dbt_utils.type_string() }}) as band_interests,
    {{ cast_to_boolean('has_whatsapp_business_number') }} as has_whatsapp_business_number,
    cast(members as {{ dbt_utils.type_string() }}) as members,
    {{ cast_to_boolean('has_added_app') }} as has_added_app,
    cast(likes as {{ type_json() }}) as likes,
    cast(personal_interests as {{ dbt_utils.type_string() }}) as personal_interests,
    cast(settings as {{ type_json() }}) as settings,
    cast(insights as {{ type_json() }}) as insights,
    cast(assigned_users as {{ type_json() }}) as assigned_users,
    cast(merchant_review_status as {{ dbt_utils.type_string() }}) as merchant_review_status,
    cast(connected_page_backed_instagram_account as {{ type_json() }}) as connected_page_backed_instagram_account,
    cast(rating_count as {{ dbt_utils.type_bigint() }}) as rating_count,
    cast(feed as {{ type_json() }}) as feed,
    cast(canvases as {{ type_json() }}) as canvases,
    cast(featured_video as {{ type_json() }}) as featured_video,
    {{ cast_to_boolean('is_messenger_platform_bot') }} as is_messenger_platform_bot,
    cast(commerce_merchant_settings as {{ type_json() }}) as commerce_merchant_settings,
    cast(birthday as {{ dbt_utils.type_string() }}) as birthday,
    {{ cast_to_boolean('has_transitioned_to_new_page_experience') }} as has_transitioned_to_new_page_experience,
    cast(instant_articles as {{ type_json() }}) as instant_articles,
    cast(link as {{ dbt_utils.type_string() }}) as link,
    cast(ad_campaign as {{ type_json() }}) as ad_campaign,
    cast(verification_status as {{ dbt_utils.type_string() }}) as verification_status,
    cast(conversations as {{ type_json() }}) as conversations,
    cast(network as {{ dbt_utils.type_string() }}) as network,
    cast(directed_by as {{ dbt_utils.type_string() }}) as directed_by,
    cast(personal_info as {{ dbt_utils.type_string() }}) as personal_info,
    cast(influences as {{ dbt_utils.type_string() }}) as influences,
    cast(general_info as {{ dbt_utils.type_string() }}) as general_info,
    {{ cast_to_boolean('can_post') }} as can_post,
    cast(preferred_audience as {{ type_json() }}) as preferred_audience,
    cast(temporary_status as {{ dbt_utils.type_string() }}) as temporary_status,
    {{ cast_to_boolean('is_chain') }} as is_chain,
    cast(built as {{ dbt_utils.type_string() }}) as built,
    cast({{ adapter.quote('groups') }} as {{ type_json() }}) as {{ adapter.quote('groups') }},
    cast(threads as {{ type_json() }}) as threads,
    cast(messenger_ads_quick_replies_type as {{ dbt_utils.type_string() }}) as messenger_ads_quick_replies_type,
    cast(thread_owner as {{ type_json() }}) as thread_owner,
    cast(awards as {{ dbt_utils.type_string() }}) as awards,
    cast(starring as {{ dbt_utils.type_string() }}) as starring,
    messenger_ads_default_icebreakers,
    cast(locations as {{ type_json() }}) as locations,
    cast(unseen_message_count as {{ dbt_utils.type_bigint() }}) as unseen_message_count,
    cast(category as {{ dbt_utils.type_string() }}) as category,
    cast(unread_notif_count as {{ dbt_utils.type_bigint() }}) as unread_notif_count,
    {{ cast_to_boolean('leadgen_tos_accepted') }} as leadgen_tos_accepted,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('page_ab1') }}
-- page
where 1 = 1

