{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('landing_page_signups_ab1') }}
select
    cast(mailing_county as {{ dbt_utils.type_string() }}) as mailing_county,
    cast(state_api_submission_result as {{ dbt_utils.type_string() }}) as state_api_submission_result,
    cast(language as {{ dbt_utils.type_string() }}) as language,
    cast(source as {{ dbt_utils.type_string() }}) as source,
    cast(voting_state as {{ dbt_utils.type_string() }}) as voting_state,
    {{ cast_to_boolean('finish_with_state') }} as finish_with_state,
    cast(id as {{ dbt_utils.type_bigint() }}) as id,
    cast(tracking_source as {{ dbt_utils.type_string() }}) as tracking_source,
    {{ cast_to_boolean('citizen') }} as citizen,
    cast(phone_type as {{ dbt_utils.type_string() }}) as phone_type,
    cast(mailing_street_address_two as {{ dbt_utils.type_string() }}) as mailing_street_address_two,
    {{ cast_to_boolean('built_via_api') }} as built_via_api,
    cast(organization_name as {{ dbt_utils.type_string() }}) as organization_name,
    cast({{ empty_string_to_null('vr_app_status_datetime') }} as {{ type_timestamp_without_timezone() }}) as vr_app_status_datetime,
    {{ cast_to_boolean('opt_in_partner_sms') }} as opt_in_partner_sms,
    cast(phone as {{ dbt_utils.type_string() }}) as phone,
    cast({{ empty_string_to_null('started_registration_at') }} as {{ type_timestamp_without_timezone() }}) as started_registration_at,
    cast(voting_city as {{ dbt_utils.type_string() }}) as voting_city,
    cast(voting_county as {{ dbt_utils.type_string() }}) as voting_county,
    cast(party as {{ dbt_utils.type_string() }}) as party,
    {{ cast_to_boolean('submitted_signature_to_state_api') }} as submitted_signature_to_state_api,
    cast(status as {{ dbt_utils.type_string() }}) as status,
    {{ cast_to_boolean('has_state_license') }} as has_state_license,
    cast(mailing_street_address_one as {{ dbt_utils.type_string() }}) as mailing_street_address_one,
    cast({{ empty_string_to_null('date_of_birth') }} as {{ type_date() }}) as date_of_birth,
    cast({{ empty_string_to_null('created_at') }} as {{ type_timestamp_without_timezone() }}) as created_at,
    cast(voting_street_address_two as {{ dbt_utils.type_string() }}) as voting_street_address_two,
    cast(voting_zipcode as {{ dbt_utils.type_string() }}) as voting_zipcode,
    cast(mailing_zipcode as {{ dbt_utils.type_string() }}) as mailing_zipcode,
    cast(name_prefix as {{ dbt_utils.type_string() }}) as name_prefix,
    {{ cast_to_boolean('volunteer_for_rtv') }} as volunteer_for_rtv,
    cast({{ empty_string_to_null('updated_at') }} as {{ type_timestamp_without_timezone() }}) as updated_at,
    cast(vr_app_status as {{ dbt_utils.type_string() }}) as vr_app_status,
    cast(vr_submission_mod as {{ dbt_utils.type_string() }}) as vr_submission_mod,
    cast(vr_submission_error as {{ dbt_utils.type_string() }}) as vr_submission_error,
    cast(first_name as {{ dbt_utils.type_string() }}) as first_name,
    cast(email as {{ dbt_utils.type_string() }}) as email,
    cast(tracking_id as {{ dbt_utils.type_string() }}) as tracking_id,
    cast(mailing_city as {{ dbt_utils.type_string() }}) as mailing_city,
    {{ cast_to_boolean('submitted_via_vendor_api') }} as submitted_via_vendor_api,
    {{ cast_to_boolean('opt_in_sms') }} as opt_in_sms,
    cast(mailing_state as {{ dbt_utils.type_string() }}) as mailing_state,
    cast(voting_street_address_one as {{ dbt_utils.type_string() }}) as voting_street_address_one,
    cast(race as {{ dbt_utils.type_string() }}) as race,
    cast(name_suffix as {{ dbt_utils.type_string() }}) as name_suffix,
    {{ cast_to_boolean('has_ssn') }} as has_ssn,
    {{ cast_to_boolean('opt_in_email') }} as opt_in_email,
    cast(last_name as {{ dbt_utils.type_string() }}) as last_name,
    cast(middle_name as {{ dbt_utils.type_string() }}) as middle_name,
    cast(ineligible_reason as {{ dbt_utils.type_string() }}) as ineligible_reason,
    {{ cast_to_boolean('volunteer_for_partner') }} as volunteer_for_partner,
    cast(source_id as {{ dbt_utils.type_string() }}) as source_id,
    cast(vr_app_status_details as {{ dbt_utils.type_string() }}) as vr_app_status_details,
    {{ cast_to_boolean('pre_registered') }} as pre_registered,
    {{ cast_to_boolean('opt_in_partner_email') }} as opt_in_partner_email,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('landing_page_signups_ab1') }}
-- landing_page_signups
where 1 = 1
{{ incremental_clause('_airbyte_emitted_at') }}

