{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('registrant_matches_ab1') }}
select
    cast(reg_address_street_name as {{ dbt_utils.type_string() }}) as reg_address_street_name,
    cast(zip9 as {{ dbt_utils.type_string() }}) as zip9,
    cast({{ empty_string_to_null('birthdate') }} as {{ type_date() }}) as birthdate,
    cast(cass_city as {{ dbt_utils.type_string() }}) as cass_city,
    cast(reg_address_two as {{ dbt_utils.type_string() }}) as reg_address_two,
    cast(mailing_address_street_name as {{ dbt_utils.type_string() }}) as mailing_address_street_name,
    cast(id as {{ dbt_utils.type_bigint() }}) as id,
    cast(state as {{ dbt_utils.type_string() }}) as state,
    cast(household_id_1 as {{ dbt_utils.type_string() }}) as household_id_1,
    cast(mailing_address_unit_type as {{ dbt_utils.type_string() }}) as mailing_address_unit_type,
    cast(household_id_2 as {{ dbt_utils.type_string() }}) as household_id_2,
    cast(cass_county_fips as {{ dbt_utils.type_bigint() }}) as cass_county_fips,
    cast({{ empty_string_to_null('earliest_registration_date') }} as {{ type_date() }}) as earliest_registration_date,
    cast(mailing_address_street_type as {{ dbt_utils.type_string() }}) as mailing_address_street_type,
    cast(voter_file_version as {{ dbt_utils.type_string() }}) as voter_file_version,
    cast(reg_zip4 as {{ dbt_utils.type_string() }}) as reg_zip4,
    cast(reg_zip5 as {{ dbt_utils.type_string() }}) as reg_zip5,
    cast(mailing_address_unit_number as {{ dbt_utils.type_string() }}) as mailing_address_unit_number,
    cast(likely_cell_assignment_score as {{ dbt_utils.type_string() }}) as likely_cell_assignment_score,
    cast(race_source as {{ dbt_utils.type_string() }}) as race_source,
    cast({{ empty_string_to_null('voter_file_latest_registration_date') }} as {{ type_date() }}) as voter_file_latest_registration_date,
    cast(full_name as {{ dbt_utils.type_string() }}) as full_name,
    cast({{ empty_string_to_null('registration_date') }} as {{ type_date() }}) as registration_date,
    cast(reg_address_one as {{ dbt_utils.type_string() }}) as reg_address_one,
    cast(confidence_score as {{ dbt_utils.type_float() }}) as confidence_score,
    cast(likely_landline_assignment_score as {{ dbt_utils.type_string() }}) as likely_landline_assignment_score,
    cast(phone_number as {{ dbt_utils.type_string() }}) as phone_number,
    cast(mailing_address_post_directional as {{ dbt_utils.type_string() }}) as mailing_address_post_directional,
    cast(reg_state as {{ dbt_utils.type_string() }}) as reg_state,
    cast(type_code as {{ dbt_utils.type_string() }}) as type_code,
    cast(election_cycle as {{ dbt_utils.type_string() }}) as election_cycle,
    cast(cass_street_address as {{ dbt_utils.type_string() }}) as cass_street_address,
    cast(likely_cell_connectivity_score as {{ dbt_utils.type_string() }}) as likely_cell_connectivity_score,
    cast(dwid as {{ dbt_utils.type_bigint() }}) as dwid,
    cast(cass_state_fips as {{ dbt_utils.type_bigint() }}) as cass_state_fips,
    cast(reg_address_street_number as {{ dbt_utils.type_string() }}) as reg_address_street_number,
    cast(mailing_address_one as {{ dbt_utils.type_string() }}) as mailing_address_one,
    cast(gender as {{ dbt_utils.type_string() }}) as gender,
    cast(ethnicity as {{ dbt_utils.type_string() }}) as ethnicity,
    cast(mailing_address_pre_directional as {{ dbt_utils.type_string() }}) as mailing_address_pre_directional,
    cast(likely_landline as {{ dbt_utils.type_string() }}) as likely_landline,
    cast({{ empty_string_to_null('created_at') }} as {{ type_timestamp_without_timezone() }}) as created_at,
    cast(mailing_address_street_number as {{ dbt_utils.type_string() }}) as mailing_address_street_number,
    cast(likely_cell as {{ dbt_utils.type_string() }}) as likely_cell,
    cast(registration_form_id as {{ dbt_utils.type_bigint() }}) as registration_form_id,
    cast(reg_address_unit_number as {{ dbt_utils.type_string() }}) as reg_address_unit_number,
    cast(reg_address_post_directional as {{ dbt_utils.type_string() }}) as reg_address_post_directional,
    cast(precinct_code as {{ dbt_utils.type_string() }}) as precinct_code,
    cast(reg_address_unit_type as {{ dbt_utils.type_string() }}) as reg_address_unit_type,
    cast({{ empty_string_to_null('updated_at') }} as {{ type_timestamp_without_timezone() }}) as updated_at,
    cast(reg_address_street_type as {{ dbt_utils.type_string() }}) as reg_address_street_type,
    cast(reg_address_pre_directional as {{ dbt_utils.type_string() }}) as reg_address_pre_directional,
    cast(first_name as {{ dbt_utils.type_string() }}) as first_name,
    cast(cass_state as {{ dbt_utils.type_string() }}) as cass_state,
    cast(mailing_city as {{ dbt_utils.type_string() }}) as mailing_city,
    cast(mailing_zip5 as {{ dbt_utils.type_string() }}) as mailing_zip5,
    cast(mailing_state as {{ dbt_utils.type_string() }}) as mailing_state,
    cast(race as {{ dbt_utils.type_string() }}) as race,
    cast(likely_cell_restricted as {{ dbt_utils.type_string() }}) as likely_cell_restricted,
    cast(name_suffix as {{ dbt_utils.type_string() }}) as name_suffix,
    cast(unique_precinct_code as {{ dbt_utils.type_string() }}) as unique_precinct_code,
    cast({{ empty_string_to_null('change_of_address_date') }} as {{ type_date() }}) as change_of_address_date,
    cast(last_name as {{ dbt_utils.type_string() }}) as last_name,
    cast(cass_zipcode as {{ dbt_utils.type_string() }}) as cass_zipcode,
    cast(mailing_address_two as {{ dbt_utils.type_string() }}) as mailing_address_two,
    cast(county_name as {{ dbt_utils.type_string() }}) as county_name,
    cast(middle_name as {{ dbt_utils.type_string() }}) as middle_name,
    cast({{ empty_string_to_null('voter_file_acqusition_date') }} as {{ type_date() }}) as voter_file_acqusition_date,
    cast(mailing_zip4 as {{ dbt_utils.type_string() }}) as mailing_zip4,
    cast(reg_city as {{ dbt_utils.type_string() }}) as reg_city,
    cast(likely_landline_restricted as {{ dbt_utils.type_string() }}) as likely_landline_restricted,
    cast(applicant_id as {{ dbt_utils.type_string() }}) as applicant_id,
    cast(race_confidence as {{ dbt_utils.type_string() }}) as race_confidence,
    cast(likely_landline_connectivity_score as {{ dbt_utils.type_string() }}) as likely_landline_connectivity_score,
    cast(age as {{ dbt_utils.type_bigint() }}) as age,
    cast(precinct_name as {{ dbt_utils.type_string() }}) as precinct_name,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('registrant_matches_ab1') }}
-- registrant_matches
where 1 = 1

