version: 2
sources:
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_adaccounts' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ads' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ads_stats_daily' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_adsquads' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_campaigns' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_creatives' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_media' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_organizations' }}"
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_segments' }}"

- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables:
  - name: adaccounts_base
  - name: adaccounts_regulations_base
  - name: ads_base
  - name: ad_stats_base
  - name: adsquads_base
  - name: adsquads_skadnetwork_properties_base
  - name: adsquads_targeting_base
  - name: adsquads_targeting_geos_base
  - name: campaigns_base
  - name: creatives_base
  - name: creatives_web_view_properties_base
  - name: media_base
  - name: segments_base
  - name: organizations_base
  - name: organizations_configuration_settings_base

- name: cta_delivery
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}_delivery"
  tables:
  - name: ad_stats
  - name: adaccounts
  - name: adaccounts_regulations
  - name: ads
  - name: adsquads
  - name: adsquads_skadnetwork_properties
  - name: adsquads_targeting
  - name: adsquads_targeting_geos
  - name: campaigns
  - name: creatives
  - name: creatives_web_view_properties
  - name: media
  - name: segments
  - name: organizations
  - name: organizations_configuration_settings