{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('page_ab2') }}
select
    {{ dbt_utils.surrogate_key([
        'name_with_location_descriptor',
        'attire',
        'about',
        'culinary_team',
        'app_id',
        'global_brand_page_name',
        'mission',
        'release_date',
        'global_brand_root_id',
        'store_number',
        'description_html',
        'leadgen_tos_acceptance_time',
        'new_like_count',
        'genre',
        'record_label',
        'store_code',
        'website',
        'differently_open_offerings',
        'business',
        'founded',
        'privacy_info_url',
        'company_overview',
        'unread_message_count',
        'single_line_address',
        'promotion_ineligible_reason',
        'checkins',
        'written_by',
        'keywords',
        'overall_star_rating',
        'price_range',
        'pharma_safety_info',
        'features',
        'affiliation',
        'whatsapp_number',
        'current_location',
        'fan_count',
        'talking_about_count',
        'name',
        'produced_by',
        'booking_agent',
        'description',
        'merchant_id',
        'display_subtext',
        'hours',
        'hometown',
        'screenplay_by',
        'schedule',
        'followers_count',
        'recipient',
        'username',
        'were_here_count',
        'studio',
        'bio',
        'displayed_message_response_time',
        'public_transit',
        'season',
        'store_location_descriptor',
        'id',
        'band_members',
        'mpg',
        'access_token',
        'phone',
        'instant_articles_review_status',
        'country_page_likes',
    ]) }} as _airbyte_page_hashid,
    tmp.*
from {{ ref('page_ab2') }} tmp
-- page
where 1 = 1

