version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
    - name: all_campaign_raw
    - name: all_question_response_raw
    - name: all_tag_raw
    - name: assignable_campaign_contacts_with_escalation_tags_raw
    - name: assignable_campaign_contacts_raw
    - name: assignable_campaigns_raw
    - name: assignable_needs_message_raw
    - name: assignable_needs_reply_with_escalation_tags_raw
    - name: assignable_needs_reply_raw
    - name: assignment_request_raw
    - name: assignment_raw
    - name: campaign_contact_tag_raw
    - name: campaign_contact_raw
    - name: campaign_team_raw
    - name: canned_response_raw
    - name: interaction_step_raw
    - name: invite_raw
    - name: message_raw
    - name: opt_out_raw
    - name: organization_raw
    - name: question_response_raw
    - name: tag_raw
    - name: team_raw
    - name: user_organization_raw
    - name: user_team_raw
    - name: user_raw
    - name: zip_code_raw