{% set partitions_to_replace = [
    'timestamp_trunc(current_timestamp, day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 1 day), day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 2 day), day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 3 day), day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 4 day), day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 5 day), day)',
    'timestamp_trunc(timestamp_sub(current_timestamp, interval 6 day), day)'
] %}

{{ config(
    partitions = partitions_to_replace,
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level" ]
) }}

-- Final base SQL model
-- depends_on: {{ ref('scans_qc_overview_ab3') }}
select
    distance_from_location,
    eligible_voting_age,
    canvasser_id,
    visual_qc_completed_by_user_id,
    program_state,
    data_entry_time,
    bad_number,
    field_start,
    shift_type,
    collection_location_id,
    identification,
    voter_registration_scan_id,
    voting_state,
    collection_location_zip,
    collection_location_city,
    collective_name,
    visual_qc_county,
    address_validated,
    qc_deadline,
    mailing_street_address_two,
    organization_name,
    canvasser_last_name,
    shift_start,
    upload_time,
    name,
    voting_city,
    collection_location_name,
    phone_number,
    party,
    voting_address_latitude,
    qc_organization,
    mailing_street_address_one,
    gender,
    ethnicity,
    signature,
    turf_parent_id,
    date_of_birth,
    extras,
    voting_street_address_two,
    voting_address_longitude,
    phone_verification_completed_by_user_id,
    voting_zipcode,
    mailing_zipcode,
    registration_type,
    registration_form_id,
    packet_filename,
    name_prefix,
    collection_location_longitude,
    through_visual_qc,
    turf_id,
    van_committee_id,
    shift_id,
    collection_location_latitude,
    shift_end,
    collection_location_county,
    first_name,
    data_entry_county,
    voter_registration_scan_updated_at,
    digital,
    mailing_city,
    is_registration_form,
    voting_street_address_one,
    name_suffix,
    data_entry_updated_at,
    last_name,
    middle_name,
    voter_registration_scan_batches_id,
    phone_validated,
    email_address,
    phone_verified,
    collection_location_street_address,
    field_end,
    canvasser_first_name,
    complete,
    has_phone_number_visual_qc,
    collection_location_state,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at,
    _airbyte_scans_qc_overview_hashid
from {{ ref('scans_qc_overview_ab3') }}
-- scans_qc_overview from {{ source('cta', '_airbyte_raw_scans_qc_overview') }}
{% if is_incremental() %}
where timestamp_trunc(_airbyte_emitted_at, day) in ({{ partitions_to_replace | join(',') }})
{% endif %}
