version: 2
sources:
- name: cta
  database: "{{ env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables:
  - name: stack_tags_base
- name: partner
  database: "{{ env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables:
  - name: stack_tags