
{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'videos') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   id,
   icon,
   title,
   views,
   format,
   length,
   source,
   ad_breaks,
   published,
   embed_html,
   embeddable,
   is_episode,
   post_views,
   description,
   live_status,
   content_tags,
   created_time,
   updated_time,
   custom_labels,
   permalink_url,
   backdated_time,
   content_category,
   is_crosspost_video,
   universal_video_id,
   is_instagram_eligible,
   scheduled_publish_time,
   is_crossposting_eligible,
   backdated_time_granularity,
   premiere_living_room_status,
   {{ dbt_utils.surrogate_key([
     'id',
    'icon',
    'title',
    'views',
    'source',
    'published',
    'embed_html',
    'embeddable',
    'is_episode',
    'post_views',
    'description',
    'live_status',
    'created_time',
    'updated_time',
    'permalink_url',
    'backdated_time',
    'content_category',
    'is_crosspost_video',
    'universal_video_id',
    'is_instagram_eligible',
    'scheduled_publish_time',
    'is_crossposting_eligible',
    'backdated_time_granularity',
    'premiere_living_room_status'
    ]) }} as _airbyte_videos_hashid
from {{ source('cta', 'videos') }}