version: 2
sources:
- name: tot_quickbooks_schema
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_accounts
  - name: _airbyte_raw_bill_payments
  - name: _airbyte_raw_bills
  - name: _airbyte_raw_budgets
  - name: _airbyte_raw_classes
  - name: _airbyte_raw_credit_memos
  - name: _airbyte_raw_customers
  - name: _airbyte_raw_departments
  - name: _airbyte_raw_deposits
  - name: _airbyte_raw_employees
  - name: _airbyte_raw_estimates
  - name: _airbyte_raw_invoices
  - name: _airbyte_raw_items
  - name: _airbyte_raw_journal_entries
  - name: _airbyte_raw_payment_methods
  - name: _airbyte_raw_payments
  - name: _airbyte_raw_purchase_orders
  - name: _airbyte_raw_purchases
  - name: _airbyte_raw_refund_receipts
  - name: _airbyte_raw_sales_receipts
  - name: _airbyte_raw_tax_agencies
  - name: _airbyte_raw_tax_codes
  - name: _airbyte_raw_tax_rates
  - name: _airbyte_raw_terms
  - name: _airbyte_raw_time_activities
  - name: _airbyte_raw_transfers
  - name: _airbyte_raw_vendor_credits
  - name: _airbyte_raw_vendors
  - name: accounts_base
  - name: accounts_CurrencyRef_base
  - name: accounts_MetaData_base
  - name: accounts_ParentRef_base
  - name: bill_payments_base
  - name: bill_payments_APAccountRef_base
  - name: bill_payments_CheckPayment_base
  - name: bill_payments_CheckPayment_BankAccountRef_base
  - name: bill_payments_CreditCardPayment_base
  - name: bill_payments_CreditCardPayment_CCAccountRef_base
  - name: bill_payments_CurrencyRef_base
  - name: bill_payments_DepartmentRef_base
  - name: bill_payments_Line_base
  - name: bill_payments_Line_LinkedTxn_base
  - name: bill_payments_MetaData_base
  - name: bill_payments_VendorRef_base
  - name: bills_base
  - name: bills_APAccountRef_base
  - name: bills_CurrencyRef_base
  - name: bills_DepartmentRef_base
  - name: bills_Line_base
  - name: bills_Line_AccountBasedExpenseLineDetail_base
  - name: bills_Line_AccountBasedExpenseLineDetail_AccountRef_base
  - name: bills_Line_AccountBasedExpenseLineDetail_CustomerRef_base
  - name: bills_Line_AccountBasedExpenseLineDetail_TaxCodeRef_base
  - name: bills_Line_ItemBasedExpenseLineDetail_base
  - name: bills_Line_ItemBasedExpenseLineDetail_ItemRef_base
  - name: bills_Line_ItemBasedExpenseLineDetail_TaxCodeRef_base
  - name: bills_LinkedTxn_base
  - name: bills_MetaData_base
  - name: bills_SalesTermRef_base
  - name: bills_VendorRef_base
  - name: budgets_base
  - name: budgets_BudgetDetail_base
  - name: budgets_BudgetDetail_AccountRef_base
  - name: budgets_BudgetDetail_ClassRef_base
  - name: budgets_BudgetDetail_CustomerRef_base
  - name: budgets_BudgetDetail_DepartmentRef_base
  - name: budgets_MetaData_base
  - name: classes_base
  - name: classes_MetaData_base
  - name: classes_ParentRef_base
  - name: credit_memos_base
  - name: credit_memos_BillAddr_base
  - name: credit_memos_BillEmail_base
  - name: credit_memos_ClassRef_base
  - name: credit_memos_CurrencyRef_base
  - name: credit_memos_CustomField_base
  - name: credit_memos_CustomerMemo_base
  - name: credit_memos_CustomerRef_base
  - name: credit_memos_Line_base
  - name: credit_memos_Line_SalesItemLineDetail_base
  - name: credit_memos_Line_SalesItemLineDetail_ItemRef_base
  - name: credit_memos_Line_SalesItemLineDetail_TaxCodeRef_base
  - name: credit_memos_MetaData_base
  - name: credit_memos_SalesTermRef_base
  - name: credit_memos_ShipAddr_base
  - name: credit_memos_TxnTaxDetail_base
  - name: customers_base
  - name: customers_BillAddr_base
  - name: customers_CurrencyRef_base
  - name: customers_DefaultTaxCodeRef_base
  - name: customers_Fax_base
  - name: customers_MetaData_base
  - name: customers_Mobile_base
  - name: customers_ParentRef_base
  - name: customers_PaymentMethodRef_base
  - name: customers_PrimaryEmailAddr_base
  - name: customers_PrimaryPhone_base
  - name: customers_SalesTermRef_base
  - name: customers_ShipAddr_base
  - name: customers_WebAddr_base
  - name: departments_base
  - name: departments_MetaData_base
  - name: departments_ParentRef_base
  - name: deposits_base
  - name: deposits_CashBack_base
  - name: deposits_CashBack_AccountRef_base
  - name: deposits_CurrencyRef_base
  - name: deposits_DepartmentRef_base
  - name: deposits_DepositToAccountRef_base
  - name: deposits_Line_base
  - name: deposits_Line_DepositLineDetail_base
  - name: deposits_Line_DepositLineDetail_AccountRef_base
  - name: deposits_Line_DepositLineDetail_PaymentMethodRef_base
  - name: deposits_Line_LinkedTxn_base
  - name: deposits_MetaData_base
  - name: employees_base
  - name: employees_MetaData_base
  - name: employees_PrimaryPhone_base
  - name: estimates_base
  - name: estimates_BillAddr_base
  - name: estimates_BillEmail_base
  - name: estimates_CurrencyRef_base
  - name: estimates_CustomField_base
  - name: estimates_CustomerMemo_base
  - name: estimates_CustomerRef_base
  - name: estimates_DeliveryInfo_base
  - name: estimates_Line_base
  - name: estimates_Line_SalesItemLineDetail_base
  - name: estimates_Line_SalesItemLineDetail_ItemRef_base
  - name: estimates_Line_SalesItemLineDetail_TaxCodeRef_base
  - name: estimates_LinkedTxn_base
  - name: estimates_MetaData_base
  - name: estimates_ShipAddr_base
  - name: estimates_TxnTaxDetail_base
  - name: estimates_TxnTaxDetail_TaxLine_base
  - name: estimates_TxnTaxDetail_TaxLine_TaxLineDetail_base
  - name: estimates_TxnTaxDetail_TaxLine_TaxLineDetail_TaxRateRef_base
  - name: estimates_TxnTaxDetail_TxnTaxCodeRef_base
  - name: invoices_base
  - name: invoices_BillAddr_base
  - name: invoices_BillEmail_base
  - name: invoices_CurrencyRef_base
  - name: invoices_CustomField_base
  - name: invoices_CustomerMemo_base
  - name: invoices_CustomerRef_base
  - name: invoices_DeliveryInfo_base
  - name: invoices_Line_base
  - name: invoices_Line_DiscountLineDetail_base
  - name: invoices_Line_DiscountLineDetail_DiscountAccountRef_base
  - name: invoices_Line_LinkedTxn_base
  - name: invoices_Line_SalesItemLineDetail_base
  - name: invoices_Line_SalesItemLineDetail_ClassRef_base
  - name: invoices_Line_SalesItemLineDetail_ItemRef_base
  - name: invoices_Line_SalesItemLineDetail_TaxCodeRef_base
  - name: invoices_LinkedTxn_base
  - name: invoices_MetaData_base
  - name: invoices_SalesTermRef_base
  - name: invoices_ShipAddr_base
  - name: invoices_TxnTaxDetail_base
  - name: invoices_TxnTaxDetail_TaxLine_base
  - name: invoices_TxnTaxDetail_TaxLine_TaxLineDetail_base
  - name: invoices_TxnTaxDetail_TaxLine_TaxLineDetail_TaxRateRef_base
  - name: invoices_TxnTaxDetail_TxnTaxCodeRef_base
  - name: items_base
  - name: items_AssetAccountRef_base
  - name: items_ExpenseAccountRef_base
  - name: items_IncomeAccountRef_base
  - name: items_MetaData_base
  - name: journal_entries_base
  - name: journal_entries_CurrencyRef_base
  - name: journal_entries_Line_base
  - name: journal_entries_Line_JournalEntryLineDetail_base
  - name: journal_entries_Line_JournalEntryLineDetail_AccountRef_base
  - name: journal_entries_MetaData_base
  - name: journal_entries_TaxRateRef_base
  - name: journal_entries_TxnTaxDetail_base
  - name: journal_entries_TxnTaxDetail_TaxLine_base
  - name: journal_entries_TxnTaxDetail_TaxLine_TaxLineDetail_base
  - name: journal_entries_TxnTaxDetail_TaxLine_TaxLineDetail_TaxRateRef_base
  - name: journal_entries_TxnTaxDetail_TxnTaxCodeRef_base
  - name: payment_methods_base
  - name: payment_methods_MetaData_base
  - name: payments_base
  - name: payments_ARAccountRef_base
  - name: payments_CurrencyRef_base
  - name: payments_CustomerRef_base
  - name: payments_DepositToAccountRef_base
  - name: payments_Line_base
  - name: payments_Line_LineEx_base
  - name: payments_Line_LineEx_any_base
  - name: payments_Line_LineEx_any_value_base
  - name: payments_Line_LinkedTxn_base
  - name: payments_LinkedTxn_base
  - name: payments_MetaData_base
  - name: payments_PaymentMethodRef_base
  - name: purchase_orders_base
  - name: purchase_orders_APAccountRef_base
  - name: purchase_orders_ClassRef_base
  - name: purchase_orders_CurrencyRef_base
  - name: purchase_orders_CustomField_base
  - name: purchase_orders_DepartmentRef_base
  - name: purchase_orders_Line_base
  - name: purchase_orders_Line_ItemBasedExpenseLineDetail_base
  - name: purchase_orders_Line_ItemBasedExpenseLineDetail_ClassRef_base
  - name: purchase_orders_Line_ItemBasedExpenseLineDetail_CustomerRef_base
  - name: purchase_orders_Line_ItemBasedExpenseLineDetail_ItemRef_base
  - name: purchase_orders_Line_ItemBasedExpenseLineDetail_TaxCodeRef_base
  - name: purchase_orders_LinkedTxn_base
  - name: purchase_orders_MetaData_base
  - name: purchase_orders_SalesTermRef_base
  - name: purchase_orders_ShipAddr_base
  - name: purchase_orders_ShipTo_base
  - name: purchase_orders_VendorAddr_base
  - name: purchase_orders_VendorRef_base
  - name: purchases_base
  - name: purchases_AccountRef_base
  - name: purchases_CurrencyRef_base
  - name: purchases_EntityRef_base
  - name: purchases_Line_base
  - name: purchases_Line_AccountBasedExpenseLineDetail_base
  - name: purchases_Line_AccountBasedExpenseLineDetail_AccountRef_base
  - name: purchases_Line_AccountBasedExpenseLineDetail_CustomerRef_base
  - name: purchases_Line_AccountBasedExpenseLineDetail_TaxCodeRef_base
  - name: purchases_Line_ItemBasedExpenseLineDetail_base
  - name: purchases_Line_ItemBasedExpenseLineDetail_ItemRef_base
  - name: purchases_Line_ItemBasedExpenseLineDetail_TaxCodeRef_base
  - name: purchases_MetaData_base
  - name: purchases_PurchaseEx_base
  - name: purchases_PurchaseEx_any_base
  - name: purchases_PurchaseEx_any_value_base
  - name: purchases_RemitToAddr_base
  - name: refund_receipts_base
  - name: refund_receipts_BillAddr_base
  - name: refund_receipts_BillEmail_base
  - name: refund_receipts_CurrencyRef_base
  - name: refund_receipts_CustomField_base
  - name: refund_receipts_CustomerMemo_base
  - name: refund_receipts_CustomerRef_base
  - name: refund_receipts_DepositToAccountRef_base
  - name: refund_receipts_Line_base
  - name: refund_receipts_Line_SalesItemLineDetail_base
  - name: refund_receipts_Line_SalesItemLineDetail_ItemRef_base
  - name: refund_receipts_Line_SalesItemLineDetail_TaxCodeRef_base
  - name: refund_receipts_MetaData_base
  - name: refund_receipts_PaymentMethodRef_base
  - name: refund_receipts_TxnTaxDetail_base
  - name: sales_receipts_base
  - name: sales_receipts_BillAddr_base
  - name: sales_receipts_BillEmail_base
  - name: sales_receipts_CurrencyRef_base
  - name: sales_receipts_CustomField_base
  - name: sales_receipts_CustomerMemo_base
  - name: sales_receipts_CustomerRef_base
  - name: sales_receipts_DepositToAccountRef_base
  - name: sales_receipts_Line_base
  - name: sales_receipts_Line_DiscountLineDetail_base
  - name: sales_receipts_Line_DiscountLineDetail_DiscountAccountRef_base
  - name: sales_receipts_Line_SalesItemLineDetail_base
  - name: sales_receipts_Line_SalesItemLineDetail_ItemRef_base
  - name: sales_receipts_Line_SalesItemLineDetail_TaxCodeRef_base
  - name: sales_receipts_LinkedTxn_base
  - name: sales_receipts_MetaData_base
  - name: sales_receipts_PaymentMethodRef_base
  - name: sales_receipts_ShipAddr_base
  - name: sales_receipts_TxnTaxDetail_base
  - name: tax_agencies_base
  - name: tax_agencies_MetaData_base
  - name: tax_codes_base
  - name: tax_codes_MetaData_base
  - name: tax_codes_SalesTaxRateList_base
  - name: tax_codes_SalesTaxRateList_TaxRateDetail_base
  - name: tax_codes_SalesTaxRateList_TaxRateDetail_TaxRateRef_base
  - name: tax_rates_base
  - name: tax_rates_AgencyRef_base
  - name: tax_rates_MetaData_base
  - name: terms_base
  - name: terms_MetaData_base
  - name: time_activities_base
  - name: time_activities_CustomerRef_base
  - name: time_activities_EmployeeRef_base
  - name: time_activities_ItemRef_base
  - name: time_activities_MetaData_base
  - name: transfers_base
  - name: transfers_CurrencyRef_base
  - name: transfers_FromAccountRef_base
  - name: transfers_MetaData_base
  - name: transfers_ToAccountRef_base
  - name: vendor_credits_base
  - name: vendor_credits_APAccountRef_base
  - name: vendor_credits_CurrencyRef_base
  - name: vendor_credits_DepartmentRef_base
  - name: vendor_credits_Line_base
  - name: vendor_credits_Line_AccountBasedExpenseLineDetail_base
  - name: vendor_credits_Line_AccountBasedExpenseLineDetail_AccountRef_base
  - name: vendor_credits_Line_AccountBasedExpenseLineDetail_ClassRef_base
  - name: vendor_credits_Line_AccountBasedExpenseLineDetail_CustomerRef_base
  - name: vendor_credits_Line_AccountBasedExpenseLineDetail_TaxCodeRef_base
  - name: vendor_credits_MetaData_base
  - name: vendor_credits_VendorRef_base
  - name: vendors_base
  - name: vendors_BillAddr_base
  - name: vendors_CurrencyRef_base
  - name: vendors_Fax_base
  - name: vendors_MetaData_base
  - name: vendors_Mobile_base
  - name: vendors_PrimaryEmailAddr_base
  - name: vendors_PrimaryPhone_base
  - name: vendors_TermRef_base
  - name: vendors_WebAddr_base