version: 2
sources:
  - name: cta_delivery
    database: "{{ env_var('CTA_PROJECT_ID') }}"
    schema: "{{ env_var('CTA_DATASET_ID') }}_delivery"
    tables:
      - name: basic_user_data
        tests:
          - unique:
              column_name: id
      - name: clickstream_data
        tests:
          - unique:
              column_name: session_id