version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: page
  - name: page_insights
  - name: post
  - name: post_insights
  - name: page_base
  - name: page_insights_base
  - name: post_base
  - name: post_insights_base