version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page"
  - name: page_insights
  - name: post
  - name: post_insights