{% set partitions_to_replace = [
    "timestamp_trunc(current_timestamp, day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 1 day), day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 2 day), day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 3 day), day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 4 day), day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 5 day), day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 6 day), day)"
] %}
{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    partitions = partitions_to_replace,
    unique_key = "_airbyte_ab_id"
) }}
-- Final base SQL model
-- depends_on: {{ ref('groups_ab4') }}
select
    id,
    city,
    name,
    email,
    state,
    stats,
    status,
    street,
    api_key,
    country,
    signoff,
    user_id,
    language,
    latitude,
    zip_code,
    longitude,
    parent_id,
    permalink,
    sms_stats,
    auto_merge,
    created_at,
    discussion,
    email_from,
    network_id,
    updated_at,
    sms_enabled,
    users_count,
    applications,
    ip_pool_name,
    localization,
    csv_file_name,
    csv_file_size,
    email_replyto,
    first_publish,
    twilio_active,
    csv_updated_at,
    additional_text,
    adhoc_group_ids,
    default_country,
    first_permalink,
    photo_file_name,
    photo_file_size,
    cancel_donations,
    csv_content_type,
    description_text,
    campaigns_enabled,
    default_report_id,
    image_attribution,
    notify_mass_email,
    redirects_enabled,
    photo_content_type,
    flow_up_sms_opt_ins,
    twilio_help_message,
    use_additional_text,
    administrative_title,
    donation_failed_email,
    mass_emails_to_notify,
    network_csv_file_name,
    network_csv_file_size,
    default_twitter_handle,
    donation_receipt_email,
    network_csv_updated_at,
    salesforce_last_update,
    current_page_wrapper_id,
    salesforce_sync_enabled,
    use_affirmative_opt_ins,
    donations_without_emails,
    network_csv_content_type,
    salesforce_custom_fields,
    current_email_template_id,
    email_stats_csv_file_name,
    email_stats_csv_file_size,
    additional_sms_opt_in_text,
    email_stats_csv_updated_at,
    salesforce_sync_successful,
    twilio_unsubscribe_message,
    default_targeting_exclude_id,
    default_targeting_include_id,
    email_stats_csv_content_type,
    cancel_donations_instructions,
    default_facebook_image_file_name,
    default_facebook_image_file_size,
    default_facebook_image_updated_at,
    mobile_message_stats_csv_file_name,
    mobile_message_stats_csv_file_size,
    default_facebook_image_content_type,
    mobile_message_stats_csv_updated_at,
    mobile_message_stats_csv_content_type,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at,
    _airbyte_groups_hashid
from {{ ref('groups_ab4') }}
-- groups from {{ source('cta', '_airbyte_raw_groups') }}

{% if is_incremental() %}
where timestamp_trunc(_airbyte_emitted_at, day) in ({{ partitions_to_replace | join(",") }})
{% endif %}
