version: 2
sources:
- name: partner_a_zoho_creator
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_applications
  - name: _airbyte_raw_fields
  - name: _airbyte_raw_forms
  - name: _airbyte_raw_pages
  - name: _airbyte_raw_reports
  - name: applications_base
  - name: fields_base
  - name: forms_base
  - name: pages_base
  - name: reports_base
