version: 2
sources:
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_applications' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_fields' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_forms' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_pages' }}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_raw__stream_reports' }}"
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: applications_base
  - name: fields_base
  - name: forms_base
  - name: pages_base
  - name: reports_base
