{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'facebook_post_analytics') }}

select
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta,
    customer_profile_id,
    created_time,
    perma_link,
    text,
    sent,
    json_extract_array(internal, '$.tags') as internal_tags,
    metrics,
    -- metrics fields unnested:
    {{ json_extract_scalar('metrics', ['lifetime.impressions'], ['lifetime.impressions']) }} as lifetime_impressions,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_viral'], ['lifetime.impressions_viral']) }} as lifetime_impressions_viral,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_nonviral'], ['lifetime.impressions_nonviral']) }} as lifetime_impressions_nonviral,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_paid'], ['lifetime.impressions_paid']) }} as lifetime_impressions_paid,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_follower'], ['lifetime.impressions_follower']) }} as lifetime_impressions_follower,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_follower_organic'], ['lifetime.impressions_follower_organic']) }} as lifetime_impressions_follower_organic,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_follower_paid'], ['lifetime.impressions_follower_paid']) }} as lifetime_impressions_follower_paid,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_nonfollower'], ['lifetime.impressions_nonfollower']) }} as lifetime_impressions_nonfollower,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_nonfollower_organic'], ['lifetime.impressions_nonfollower_organic']) }} as lifetime_impressions_nonfollower_organic,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_nonfollower_paid'], ['lifetime.impressions_nonfollower_paid']) }} as lifetime_impressions_nonfollower_paid,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_unique'], ['lifetime.impressions_unique']) }} as lifetime_impressions_unique,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_organic_unique'], ['lifetime.impressions_organic_unique']) }} as lifetime_impressions_organic_unique,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_viral_unique'], ['lifetime.impressions_viral_unique']) }} as lifetime_impressions_viral_unique,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_nonviral_unique'], ['lifetime.impressions_nonviral_unique']) }} as lifetime_impressions_nonviral_unique,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_paid_unique'], ['lifetime.impressions_paid_unique']) }} as lifetime_impressions_paid_unique,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_follower_unique'], ['lifetime.impressions_follower_unique']) }} as lifetime_impressions_follower_unique,
    {{ json_extract_scalar('metrics', ['lifetime.impressions_follower_paid_unique'], ['lifetime.impressions_follower_paid_unique']) }} as lifetime_impressions_follower_paid_unique,
    {{ json_extract_scalar('metrics', ['lifetime.likes'], ['lifetime.likes']) }} as lifetime_likes,
    {{ json_extract_scalar('metrics', ['lifetime.reactions_love'], ['lifetime.reactions_love']) }} as lifetime_reactions_love,
    {{ json_extract_scalar('metrics', ['lifetime.reactions_haha'], ['lifetime.reactions_haha']) }} as lifetime_reactions_haha,
    {{ json_extract_scalar('metrics', ['lifetime.reactions_wow'], ['lifetime.reactions_wow']) }} as lifetime_reactions_wow,
    {{ json_extract_scalar('metrics', ['lifetime.reactions_sad'], ['lifetime.reactions_sad']) }} as lifetime_reactions_sad,
    {{ json_extract_scalar('metrics', ['lifetime.reactions_angry'], ['lifetime.reactions_angry']) }} as lifetime_reactions_angry,
    {{ json_extract_scalar('metrics', ['lifetime.shares_count'], ['lifetime.shares_count']) }} as lifetime_shares_count,
    {{ json_extract_scalar('metrics', ['lifetime.question_answers'], ['lifetime.question_answers']) }} as lifetime_question_answers,
    {{ json_extract_scalar('metrics', ['lifetime.post_content_clicks'], ['lifetime.post_content_clicks']) }} as lifetime_post_content_clicks,
    {{ json_extract_scalar('metrics', ['lifetime.post_photo_view_clicks'], ['lifetime.post_photo_view_clicks']) }} as lifetime_post_photo_view_clicks,
    {{ json_extract_scalar('metrics', ['lifetime.post_video_play_clicks'], ['lifetime.post_video_play_clicks']) }} as lifetime_post_video_play_clicks,
    {{ json_extract_scalar('metrics', ['lifetime.post_content_clicks_other'], ['lifetime.post_content_clicks_other']) }} as lifetime_post_content_clicks_other,
    {{ json_extract_scalar('metrics', ['lifetime.negative_feedback'], ['lifetime.negative_feedback']) }} as lifetime_negative_feedback,
    {{ json_extract_scalar('metrics', ['lifetime.engagements_unique'], ['lifetime.engagements_unique']) }} as lifetime_engagements_unique,
    {{ json_extract_scalar('metrics', ['lifetime.engagements_follower_unique'], ['lifetime.engagements_follower_unique']) }} as lifetime_engagements_follower_unique,
    {{ json_extract_scalar('metrics', ['lifetime.reactions_unique'], ['lifetime.reactions_unique']) }} as lifetime_reactions_unique,
    {{ json_extract_scalar('metrics', ['lifetime.comments_count_unique'], ['lifetime.comments_count_unique']) }} as lifetime_comments_count_unique,
    {{ json_extract_scalar('metrics', ['lifetime.shares_count_unique'], ['lifetime.shares_count_unique']) }} as lifetime_shares_count_unique,
    {{ json_extract_scalar('metrics', ['lifetime.question_answers_unique'], ['lifetime.question_answers_unique']) }} as lifetime_question_answers_unique,
    {{ json_extract_scalar('metrics', ['lifetime.post_link_clicks_unique'], ['lifetime.post_link_clicks_unique']) }} as lifetime_post_link_clicks_unique,
    {{ json_extract_scalar('metrics', ['lifetime.post_content_clicks_unique'], ['lifetime.post_content_clicks_unique']) }} as lifetime_post_content_clicks_unique,
    {{ json_extract_scalar('metrics', ['lifetime.post_photo_view_clicks_unique'], ['lifetime.post_photo_view_clicks_unique']) }} as lifetime_post_photo_view_clicks_unique,
    {{ json_extract_scalar('metrics', ['lifetime.post_video_play_clicks_unique'], ['lifetime.post_video_play_clicks_unique']) }} as lifetime_post_video_play_clicks_unique,
    {{ json_extract_scalar('metrics', ['lifetime.post_other_clicks_unique'], ['lifetime.post_other_clicks_unique']) }} as lifetime_post_other_clicks_unique,
    {{ json_extract_scalar('metrics', ['lifetime.negative_feedback_unique'], ['lifetime.negative_feedback_unique']) }} as lifetime_negative_feedback_unique,
    {{ json_extract_scalar('metrics', ['video_length'], ['video_length']) }} as video_length,
    {{ json_extract_scalar('metrics', ['lifetime.video_views'], ['lifetime.video_views']) }} as lifetime_video_views,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_unique'], ['lifetime.video_views_unique']) }} as lifetime_video_views_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_organic'], ['lifetime.video_views_organic']) }} as lifetime_video_views_organic,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_organic_unique'], ['lifetime.video_views_organic_unique']) }} as lifetime_video_views_organic_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_paid'], ['lifetime.video_views_paid']) }} as lifetime_video_views_paid,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_paid_unique'], ['lifetime.video_views_paid_unique']) }} as lifetime_video_views_paid_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_autoplay'], ['lifetime.video_views_autoplay']) }} as lifetime_video_views_autoplay,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_click_to_play'], ['lifetime.video_views_click_to_play']) }} as lifetime_video_views_click_to_play,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_sound_on'], ['lifetime.video_views_sound_on']) }} as lifetime_video_views_sound_on,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_sound_off'], ['lifetime.video_views_sound_off']) }} as lifetime_video_views_sound_off,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s'], ['lifetime.video_views_10s']) }} as lifetime_video_views_10s,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_organic'], ['lifetime.video_views_10s_organic']) }} as lifetime_video_views_10s_organic,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_paid'], ['lifetime.video_views_10s_paid']) }} as lifetime_video_views_10s_paid,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_autoplay'], ['lifetime.video_views_10s_autoplay']) }} as lifetime_video_views_10s_autoplay,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_click_to_play'], ['lifetime.video_views_10s_click_to_play']) }} as lifetime_video_views_10s_click_to_play,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_sound_on'], ['lifetime.video_views_10s_sound_on']) }} as lifetime_video_views_10s_sound_on,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_sound_off'], ['lifetime.video_views_10s_sound_off']) }} as lifetime_video_views_10s_sound_off,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_partial'], ['lifetime.video_views_partial']) }} as lifetime_video_views_partial,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_partial_organic'], ['lifetime.video_views_partial_organic']) }} as lifetime_video_views_partial_organic,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_partial_paid'], ['lifetime.video_views_partial_paid']) }} as lifetime_video_views_partial_paid,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_partial_autoplay'], ['lifetime.video_views_partial_autoplay']) }} as lifetime_video_views_partial_autoplay,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_partial_click_to_play'], ['lifetime.video_views_partial_click_to_play']) }} as lifetime_video_views_partial_click_to_play,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_30s_complete'], ['lifetime.video_views_30s_complete']) }} as lifetime_video_views_30s_complete,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_30s_complete_organic'], ['lifetime.video_views_30s_complete_organic']) }} as lifetime_video_views_30s_complete_organic,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_30s_complete_paid'], ['lifetime.video_views_30s_complete_paid']) }} as lifetime_video_views_30s_complete_paid,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_30s_complete_autoplay'], ['lifetime.video_views_30s_complete_autoplay']) }} as lifetime_video_views_30s_complete_autoplay,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_30s_complete_click_to_play'], ['lifetime.video_views_30s_complete_click_to_play']) }} as lifetime_video_views_30s_complete_click_to_play,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_p95'], ['lifetime.video_views_p95']) }} as lifetime_video_views_p95,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_p95_organic'], ['lifetime.video_views_p95_organic']) }} as lifetime_video_views_p95_organic,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_p95_paid'], ['lifetime.video_views_p95_paid']) }} as lifetime_video_views_p95_paid,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_10s_unique'], ['lifetime.video_views_10s_unique']) }} as lifetime_video_views_10s_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_30s_complete_unique'], ['lifetime.video_views_30s_complete_unique']) }} as lifetime_video_views_30s_complete_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_p95_paid_unique'], ['lifetime.video_views_p95_paid_unique']) }} as lifetime_video_views_p95_paid_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_views_p95_organic_unique'], ['lifetime.video_views_p95_organic_unique']) }} as lifetime_video_views_p95_organic_unique,
    {{ json_extract_scalar('metrics', ['lifetime.video_view_time_per_view'], ['lifetime.video_view_time_per_view']) }} as lifetime_video_view_time_per_view,
    {{ json_extract_scalar('metrics', ['lifetime.video_view_time'], ['lifetime.video_view_time']) }} as lifetime_video_view_time,
    {{ json_extract_scalar('metrics', ['lifetime.video_view_time_organic'], ['lifetime.video_view_time_organic']) }} as lifetime_video_view_time_organic,
    {{ json_extract_scalar('metrics', ['lifetime.video_view_time_paid'], ['lifetime.video_view_time_paid']) }} as lifetime_video_view_time_paid,
    {{ json_extract_scalar('metrics', ['lifetime.video_ad_break_impressions'], ['lifetime.video_ad_break_impressions']) }} as lifetime_video_ad_break_impressions,
    {{ json_extract_scalar('metrics', ['lifetime.video_ad_break_earnings'], ['lifetime.video_ad_break_earnings']) }} as lifetime_video_ad_break_earnings,
    {{ json_extract_scalar('metrics', ['lifetime.video_ad_break_cost_per_impression'], ['lifetime.video_ad_break_cost_per_impression']) }} as lifetime_video_ad_break_cost_per_impression
from {{ source('cta', 'facebook_post_analytics') }}
