{{ config(
    cluster_by = "_airbyte_extracted_at",
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_raw_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('facebook_profile_analytics_ab1') }}

select
    *,
   {{ dbt_utils.surrogate_key([
    'customer_profile_id',
    'reporting_period_day',
    'lifetime_snapshot_followers_count',
    'net_follower_growth',
    'followers_gained',
    'followers_gained_organic',
    'followers_gained_paid',
    'followers_lost',
    'impressions',
    'impressions_organic',
    'impressions_viral',
    'impressions_nonviral',
    'impressions_paid',
    'tab_views',
    'tab_views_login',
    'tab_views_logout',
    'post_impressions',
    'post_impressions_organic',
    'post_impressions_viral',
    'post_impressions_nonviral',
    'post_impressions_paid',
    'impressions_unique',
    'impressions_organic_unique',
    'impressions_viral_unique',
    'impressions_nonviral_unique',
    'impressions_paid_unique',
    'profile_views',
    'profile_views_login',
    'profile_views_logout',
    'profile_views_login_unique',
    'reactions',
    'comments_count',
    'shares_count',
    'post_link_clicks',
    'post_content_clicks_other',
    'likes',
    'reactions_love',
    'reactions_haha',
    'reactions_wow',
    'reactions_sad',
    'reactions_angry',
    'post_photo_view_clicks',
    'post_video_play_clicks',
    'profile_actions',
    'post_engagements',
    'cta_clicks_login',
    'question_answers',
    'offer_claims',
    'positive_feedback_other',
    'event_rsvps',
    'place_checkins',
    'place_checkins_mobile',
    'profile_content_activity',
    'negative_feedback',
    'video_views',
    'video_views_organic',
    'video_views_paid',
    'video_views_autoplay',
    'video_views_click_to_play',
    'video_views_repeat',
    'video_view_time',
    'video_views_unique',
    'video_views_30s_complete',
    'video_views_30s_complete_organic',
    'video_views_30s_complete_paid',
    'video_views_30s_complete_autoplay',
    'video_views_30s_complete_click_to_play',
    'video_views_30s_complete_unique',
    'video_views_30s_complete_repeat',
    'video_views_partial',
    'video_views_partial_organic',
    'video_views_partial_paid',
    'video_views_partial_autoplay',
    'video_views_partial_click_to_play',
    'video_views_partial_repeat',
    'video_views_10s',
    'video_views_10s_organic',
    'video_views_10s_paid',
    'video_views_10s_autoplay',
    'video_views_10s_click_to_play',
    'video_views_10s_repeat',
    'video_views_10s_unique',
    'posts_sent_count',
    ]) }} as _airbyte_facebook_profile_analytics_hashid
from {{ ref('facebook_profile_analytics_ab1') }}
