version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables:
    - name: _airbyte_raw_users
    - name: _airbyte_raw_group_members
    - name: _airbyte_raw_groups
    - name: users