version: 2
sources:
- name: cta
  database: "{{ env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables:
    - name: _airbyte_raw_users
    - name: _airbyte_raw_group_members
    - name: _airbyte_raw_groups
    - name: users