version: 2
sources:
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_action_keywords'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_action_questions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_actions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_answers'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_call_campaigns'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_call_targets'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_calls'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_campaigns'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_catalist_syncs'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_child_permissions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_collections'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_collections_groups'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_comments'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_core_field_syndications'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_core_field_timezones'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_core_fields'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_core_fields_counties'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_core_fields_ocdids'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_counties'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_deliveries'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_delivery_targets'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_donation_payments'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_donation_recipients'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_donations'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_donations_recurring_donations'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_1'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_10'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_11'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_12'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_13'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_14'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_15'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_16'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_2'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_3'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_4'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_5'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_6'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_7'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_8'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_activities_9'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_campaign_members'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_campaigns'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_fields'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_stats'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_templates'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_email_tests'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_emails'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_event_campaign_invites'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_event_campaign_uploads'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_event_campaigns'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_events'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_field_names'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_field_names_groups'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_field_values'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_filter_actions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_filters'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_forms'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_fundraisings'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_group_growth_by_source_actions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_group_growth_by_source_codes'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_group_invites'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_groups'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_groups_syndications'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_groups_users'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_ladders'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_letter_templates'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_letters'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_lists'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_locations'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_message_actions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_mobile_message_fields'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_mobile_message_stats'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_mobile_messages'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_networks'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_networks_users'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_notification_settings'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_ocdids'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_page_actions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_page_wrappers'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_petitions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_phone_change_logs'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_phone_dedupe_logs'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_queries'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_questions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_recurring_donations'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_reports'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_rsvps'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_share_options'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_signatures'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_sms_message_activities'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_sms_messages'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_sms_status_logs'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_sms_statuses'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_sms_unsubscriptions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_source_codes'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_steps'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_subscription_statuses'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_subscriptions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_subscriptions_1'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_syndications'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_tag_syndications'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_tags'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_targets'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_ticket_receipts'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_ticketed_events'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_tickets'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_triggers'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_unsubscriptions'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_files'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_ladder_statuses'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_merge_logs'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_merge_logs_1'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_source_codes'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_tags'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_user_tickets'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_users'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_webhook_messages'}}"
  - name: "{{ env_var('CTA_DATASET_ID') ~ '_airbyte_raw_webhooks'}}"

- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: action_keywords_base
  - name: action_questions_base
  - name: actions_base
  - name: answers_base
  - name: call_campaigns_base
  - name: call_targets_base
  - name: calls_base
  - name: campaigns_base
  - name: catalist_syncs_base
  - name: child_permissions_base
  - name: collections_base
  - name: collections_groups_base
  - name: comments_base
  - name: core_field_syndications_base
  - name: core_field_timezones_base
  - name: core_fields_base
  - name: core_fields_counties_base
  - name: core_fields_ocdids_base
  - name: counties_base
  - name: deliveries_base
  - name: delivery_targets_base
  - name: donation_payments_base
  - name: donation_recipients_base
  - name: donations_base
  - name: donations_recurring_donations_base
  - name: email_activities_base
  - name: email_activities_1_base
  - name: email_activities_10_base
  - name: email_activities_11_base
  - name: email_activities_12_base
  - name: email_activities_13_base
  - name: email_activities_14_base
  - name: email_activities_15_base
  - name: email_activities_16_base
  - name: email_activities_2_base
  - name: email_activities_3_base
  - name: email_activities_4_base
  - name: email_activities_5_base
  - name: email_activities_6_base
  - name: email_activities_7_base
  - name: email_activities_8_base
  - name: email_activities_9_base
  - name: email_campaign_members_base
  - name: email_campaigns_base
  - name: email_fields_base
  - name: email_stats_base
  - name: email_templates_base
  - name: email_tests_base
  - name: emails_base
  - name: event_campaign_invites_base
  - name: event_campaign_uploads_base
  - name: event_campaigns_base
  - name: events_base
  - name: field_names_base
  - name: field_names_groups_base
  - name: field_values_base
  - name: filter_actions_base
  - name: filters_base
  - name: forms_base
  - name: fundraisings_base
  - name: group_growth_by_source_actions_base
  - name: group_growth_by_source_codes_base
  - name: group_invites_base
  - name: groups_base
  - name: groups_syndications_base
  - name: groups_users_base
  - name: ladders_base
  - name: letter_templates_base
  - name: letters_base
  - name: lists_base
  - name: locations_base
  - name: message_actions_base
  - name: mobile_message_fields_base
  - name: mobile_message_stats_base
  - name: mobile_messages_base
  - name: networks_base
  - name: networks_users_base
  - name: notification_settings_base
  - name: ocdids_base
  - name: page_actions_base
  - name: page_wrappers_base
  - name: petitions_base
  - name: phone_change_logs_base
  - name: phone_dedupe_logs_base
  - name: queries_base
  - name: questions_base
  - name: recurring_donations_base
  - name: reports_base
  - name: rsvps_base
  - name: share_options_base
  - name: signatures_base
  - name: sms_message_activities_base
  - name: sms_messages_base
  - name: sms_status_logs_base
  - name: sms_statuses_base
  - name: sms_unsubscriptions_base
  - name: source_codes_base
  - name: steps_base
  - name: subscription_statuses_base
  - name: subscriptions_base
  - name: subscriptions_1_base
  - name: syndications_base
  - name: tag_syndications_base
  - name: tags_base
  - name: targets_base
  - name: ticket_receipts_base
  - name: ticketed_events_base
  - name: tickets_base
  - name: triggers_base
  - name: unsubscriptions_base
  - name: user_files_base
  - name: user_ladder_statuses_base
  - name: user_merge_logs_base
  - name: user_merge_logs_1_base
  - name: user_source_codes_base
  - name: user_tags_base
  - name: user_tickets_base
  - name: users_base
  - name: webhook_messages_base
  - name: webhooks_base
