{% set partitions_to_replace = [
    "timestamp_trunc(current_timestamp, day)",
    "timestamp_trunc(timestamp_sub(current_timestamp, interval 1 day), day)"
] %}
{{ config(
    cluster_by = "_cta_loaded_at",
    partition_by = {"field": "_cta_loaded_at", "data_type": "timestamp", "granularity": "day"},
    partitions = partitions_to_replace,
    unique_key = "_knock_people_hashid"
) }}
-- Final base SQL model
-- depends_on: {{ ref('knock_people_cte1') }}
select
    id,
    created_date,
    state_file_id,
    county_file_id,
    action_network_id,
    of_voter_file_id,
    other_voter_file_id,
    alloy_uuid,
    vr_status,
    full_name,
    honorarium,
    first_name,
    middle_name,
    last_name,
    suffix,
    preferred_name,
    sex,
    age,
    dob,
    gender_identity,
    phone1,
    phone_opt_in1,
    phone2,
    phone_opt_in2,
    email1,
    email_opt_in1,
    email2,
    email_opt_in2,
    prov_full_address,
    prov_address1,
    prov_address2,
    prov_city,
    prov_state,
    prov_zip_5,
    p_raw_lat_long,
    p_raw_lat,
    p_raw_long,
    p_geom,
    contacted_full_address,
    lives_at_contacted,
    reg_full_address,
    reg_address1,
    reg_address2,
    reg_city,
    reg_county,
    reg_state,
    reg_zip_5,
    r_raw_lat_long,
    r_raw_lat,
    r_raw_long,
    r_geom,
    mail_full_address,
    mail_address1,
    mail_address2,
    mail_city,
    mail_state,
    mail_zip_5,
    m_raw_lat_long,
    m_raw_lat,
    m_raw_long,
    m_geom,
    early_voted,
    contacted_national_address_id_id,
    mailing_national_address_id_id,
    provided_national_address_id_id,
    registered_national_address_id_id,
    actionkit_id,
    mobilize_id,
    polling_location,
    precinct_id,
    precinct_name,
    van_id,
    mail_street_name,
    mail_street_number,
    mail_unit_number,
    prov_street_name,
    prov_street_number,
    prov_unit_number,
    reg_street_name,
    reg_street_number,
    reg_unit_number,
    political_party,
    my_campaign_id,
    member,
    mail_apt_type,
    mail_street_number_half,
    mail_street_part,
    mail_street_prefix,
    mail_street_suffix,
    mail_street_type,
    prov_apt_type,
    prov_street_number_half,
    prov_street_part,
    prov_street_prefix,
    prov_street_suffix,
    prov_street_type,
    reg_apt_type,
    reg_street_number_half,
    reg_street_part,
    reg_street_prefix,
    reg_street_suffix,
    reg_street_type,
    mail_county,
    prov_county,
    dwid,
    other_crm_id,
    phone3,
    phone4,
    phone_opt_in3,
    phone_opt_in4,
    voterbase_id,
    mail_zip_4,
    prov_zip_4,
    reg_zip_4,
    partition_schema_name,
    partition_name,
    _knock_people_hashid,
    _cta_loaded_at

from {{ ref('knock_people_cte1') }}

{% if is_incremental() %}
where timestamp_trunc(_cta_loaded_at, day) in ({{ partitions_to_replace | join(",") }})
{% endif %}
