version: 2
sources:
- name: cta
  database: "{{ env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables:
    - name: _airbyte_raw_categories
    - name: _airbyte_raw_customers
    - name: _airbyte_raw_discounts
    - name: _airbyte_raw_items
    - name: _airbyte_raw_locations
    - name: _airbyte_raw_modifier_list
    - name: _airbyte_raw_orders
    - name: _airbyte_raw_payments
    - name: _airbyte_raw_refunds
    - name: _airbyte_raw_shifts
    - name: _airbyte_raw_taxes
    - name: _airbyte_raw_team_member_wages
    - name: _airbyte_raw_team_members
    - name: customers_base
    - name: customers_address_base
    - name: customers_cards_base
    - name: customers_cards_billing_address_base
    - name: customers_preferences_base
    - name: locations_base
    - name: locations_address_base
    - name: orders_base
    - name: orders_discounts_base
    - name: orders_discounts_applied_money_base
    - name: orders_fulfillments_base
    - name: orders_fulfillments_pickup_details_base
    - name: orders_fulfillments_pickup_details_recipient_base
    - name: orders_fulfillments_shipment_details_base
    - name: orders_fulfillments_shipment_details_recipient_base
    - name: orders_fulfillments_shipment_details_recipient_address_base
    - name: orders_line_items_base
    - name: orders_line_items_applied_discounts_base
    - name: orders_line_items_applied_discounts_applied_money_base
    - name: orders_line_items_applied_taxes_base
    - name: orders_line_items_applied_taxes_applied_money_base
    - name: orders_line_items_base_price_money_base
    - name: orders_line_items_gross_sales_money_base
    - name: orders_line_items_modifiers_base
    - name: orders_line_items_modifiers_base_price_money_base
    - name: orders_line_items_modifiers_total_price_money_base
    - name: orders_line_items_total_discount_money_base
    - name: orders_line_items_total_money_base
    - name: orders_line_items_total_tax_money_base
    - name: orders_line_items_variation_total_price_money_base
    - name: orders_net_amounts_base
    - name: orders_net_amounts_discount_money_base
    - name: orders_net_amounts_service_charge_money_base
    - name: orders_net_amounts_tax_money_base
    - name: orders_net_amounts_tip_money_base
    - name: orders_net_amounts_total_money_base
    - name: orders_refunds_base
    - name: orders_refunds_amount_money_base
    - name: orders_return_amounts_base
    - name: orders_return_amounts_discount_money_base
    - name: orders_return_amounts_service_charge_money_base
    - name: orders_return_amounts_tax_money_base
    - name: orders_return_amounts_tip_money_base
    - name: orders_return_amounts_total_money_base
    - name: orders_returns_base
    - name: orders_returns_return_line_items_base
    - name: orders_returns_return_line_items_base_price_money_base
    - name: orders_returns_return_line_items_gross_return_money_base
    - name: orders_returns_return_line_items_total_discount_money_base
    - name: orders_returns_return_line_items_total_money_base
    - name: orders_returns_return_line_items_total_tax_money_base
    - name: orders_returns_return_line_items_variation_total_price_money_base
    - name: orders_service_charges_base
    - name: orders_service_charges_amount_money_base
    - name: orders_service_charges_applied_money_base
    - name: orders_service_charges_total_money_base
    - name: orders_service_charges_total_tax_money_base
    - name: orders_source_base
    - name: orders_taxes_base
    - name: orders_taxes_applied_money_base
    - name: orders_tenders_base
    - name: orders_tenders_amount_money_base
    - name: orders_tenders_card_details_base
    - name: orders_tenders_card_details_card_base
    - name: orders_tenders_cash_details_base
    - name: orders_tenders_cash_details_buyer_tendered_money_base
    - name: orders_tenders_cash_details_change_back_money_base
    - name: orders_total_discount_money_base
    - name: orders_total_money_base
    - name: orders_total_service_charge_money_base
    - name: orders_total_tax_money_base
    - name: orders_total_tip_money_base
    - name: shifts_base
    - name: shifts_breaks_base
    - name: shifts_wage_base
    - name: shifts_wage_hourly_rate_base
    - name: team_member_wages_base
    - name: team_member_wages_hourly_rate_base
    - name: team_members_base
    - name: team_members_assigned_locations_base
    - name: categories_base
    - name: categories_category_data_base
    - name: discounts_base
    - name: discounts_discount_data_base
    - name: discounts_discount_data_amount_money_base
    - name: items_base
    - name: items_item_data_base
    - name: items_item_data_item_options_base
    - name: items_item_data_modifier_list_info_base
    - name: items_item_data_variations_base
    - name: items_item_data_variations_item_variation_data_base
    - name: items_item_data_variations_item_variation_data_item_option_values_base
    - name: items_item_data_variations_item_variation_data_location_overrides_base
    - name: items_item_data_variations_item_variation_data_price_money_base
    - name: modifier_list_base
    - name: modifier_list_modifier_list_data_base
    - name: modifier_list_modifier_list_data_modifiers_base
    - name: modifier_list_modifier_list_data_modifiers_modifier_data_base
    - name: modifier_list_modifier_list_data_modifiers_modifier_data_price_money_base
    - name: payments_base
    - name: payments_amount_money_base
    - name: payments_approved_money_base
    - name: payments_card_details_base
    - name: payments_card_details_card_base
    - name: payments_card_details_card_payment_timeline_base
    - name: payments_processing_fee_base
    - name: payments_processing_fee_amount_money_base
    - name: payments_refunded_money_base
    - name: payments_risk_evaluation_base
    - name: payments_total_money_base
    - name: refunds_base
    - name: refunds_amount_money_base
    - name: refunds_processing_fee_base
    - name: refunds_processing_fee_amount_money_base
    - name: taxes_base
    - name: taxes_tax_data_base