version: 2
sources:
- name: cta
  database: "{{env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_agents
  - name: _airbyte_raw_business_hours
  - name: _airbyte_raw_canned_response_folders
  - name: _airbyte_raw_canned_responses
  - name: _airbyte_raw_companies
  - name: _airbyte_raw_contacts
  - name: _airbyte_raw_conversations
  - name: _airbyte_raw_discussion_categories
  - name: _airbyte_raw_discussion_comments
  - name: _airbyte_raw_discussion_forums
  - name: _airbyte_raw_discussion_topics
  - name: _airbyte_raw_email_configs
  - name: _airbyte_raw_email_mailboxes
  - name: _airbyte_raw_groups
  - name: _airbyte_raw_products
  - name: _airbyte_raw_roles
  - name: _airbyte_raw_satisfaction_ratings
  - name: _airbyte_raw_scenario_automations
  - name: _airbyte_raw_settings
  - name: _airbyte_raw_sla_policies
  - name: _airbyte_raw_solution_articles
  - name: _airbyte_raw_solution_categories
  - name: _airbyte_raw_solution_folders
  - name: _airbyte_raw_surveys
  - name: _airbyte_raw_ticket_fields
  - name: _airbyte_raw_tickets
  - name: _airbyte_raw_time_entries
  - name: agent_base
  - name: business_hour_base
  - name: canned_response_folder_base
  - name: canned_response_base
  - name: company_base
  - name: contact_base
  - name: conversation_base
  - name: discussion_category_base
  - name: discussion_comment_base
  - name: discussion_forum_base
  - name: discussion_topic_base
  - name: email_config_base
  - name: email_mailbox_base
  - name: group_base
  - name: product_base
  - name: role_base
  - name: satisfaction_rating_base
  - name: scenario_automation_base
  - name: settings_base
  - name: sla_policy_base
  - name: solution_article_base
  - name: solution_category_base
  - name: solution_folder_base
  - name: survey_base
  - name: survey_question_base
  - name: ticket_base
  - name: ticket_field_base
  - name: time_entries_base