version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables:
  - name: _raw_payroll
  - name: payroll_base

- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID') }}"
  tables:
    - name: payroll