version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_balance_transactions
  - name: _airbyte_raw_bank_accounts
  - name: _airbyte_raw_charges
  - name: _airbyte_raw_checkout_sessions
  - name: _airbyte_raw_checkout_sessions_line_items
  - name: _airbyte_raw_coupons
  - name: _airbyte_raw_customer_balance_transactions
  - name: _airbyte_raw_customers
  - name: _airbyte_raw_disputes
  - name: _airbyte_raw_events
  - name: _airbyte_raw_external_account_bank_accounts
  - name: _airbyte_raw_external_account_cards
  - name: _airbyte_raw_invoice_items
  - name: _airbyte_raw_invoice_line_items
  - name: _airbyte_raw_invoices
  - name: _airbyte_raw_payment_intents
  - name: _airbyte_raw_payouts
  - name: _airbyte_raw_plans
  - name: _airbyte_raw_products
  - name: _airbyte_raw_promotion_codes
  - name: _airbyte_raw_refunds
  - name: _airbyte_raw_subscription_items
  - name: _airbyte_raw_subscriptions
  - name: _airbyte_raw_transfers
  - name: balance_transactions_base
  - name: balance_transactions_fee_details_base
  - name: charges_base
  - name: charges_card_base
  - name: charges_fraud_details_base
  - name: charges_outcome_base
  - name: charges_payment_method_details_ach_credit_transfer_base
  - name: charges_payment_method_details_ach_debit_base
  - name: charges_payment_method_details_bancontact_base
  - name: charges_payment_method_details_base
  - name: charges_payment_method_details_card_base
  - name: charges_payment_method_details_card_card_present_base
  - name: charges_payment_method_details_card_card_present_receipt_base
  - name: charges_payment_method_details_card_checks_base
  - name: charges_payment_method_details_card_eps_base
  - name: charges_payment_method_details_card_giropay_base
  - name: charges_payment_method_details_card_ideal_base
  - name: charges_payment_method_details_card_installments_base
  - name: charges_payment_method_details_card_installments_plan_base
  - name: charges_payment_method_details_card_multibanco_base
  - name: charges_payment_method_details_card_p24_base
  - name: charges_payment_method_details_card_sepa_debit_base
  - name: charges_payment_method_details_card_sofort_base
  - name: charges_payment_method_details_card_three_d_secure_base
  - name: charges_payment_method_details_card_wallet_base
  - name: charges_payment_method_details_card_wallet_masterpass_base
  - name: charges_payment_method_details_card_wallet_masterpass_billing_address_base
  - name: charges_payment_method_details_card_wallet_masterpass_shipping_address_base
  - name: charges_payment_method_details_card_wallet_visa_checkout_base
  - name: charges_payment_method_details_card_wallet_visa_checkout_billing_address_base
  - name: charges_payment_method_details_card_wallet_visa_checkout_shipping_address_base
  - name: charges_refunds_base
  - name: charges_source_ach_credit_transfer_base
  - name: charges_source_base
  - name: charges_source_card_base
  - name: charges_source_owner_address_base
  - name: charges_source_owner_base
  - name: charges_source_receiver_base
  - name: charges_source_redirect_base
  - name: checkout_sessions_after_expiration_base
  - name: checkout_sessions_after_expiration_recovery_base
  - name: checkout_sessions_automatic_tax_base
  - name: checkout_sessions_base
  - name: checkout_sessions_consent_base
  - name: checkout_sessions_consent_collection_base
  - name: checkout_sessions_customer_details_base
  - name: checkout_sessions_customer_details_tax_ids_base
  - name: checkout_sessions_line_items_base
  - name: checkout_sessions_line_items_discounts_base
  - name: checkout_sessions_line_items_discounts_discount_base
  - name: checkout_sessions_line_items_discounts_discount_coupon_applies_to_base
  - name: checkout_sessions_line_items_discounts_discount_coupon_base
  - name: checkout_sessions_line_items_price_base
  - name: checkout_sessions_line_items_price_recurring_base
  - name: checkout_sessions_line_items_price_tiers_base
  - name: checkout_sessions_line_items_price_transform_quantity_base
  - name: checkout_sessions_line_items_taxes_base
  - name: checkout_sessions_line_items_taxes_rate_base
  - name: checkout_sessions_payment_method_options_acss_debit_base
  - name: checkout_sessions_payment_method_options_acss_debit_mandate_options_base
  - name: checkout_sessions_payment_method_options_base
  - name: checkout_sessions_payment_method_options_boleto_base
  - name: checkout_sessions_payment_method_options_oxxo_base
  - name: checkout_sessions_phone_number_collection_base
  - name: checkout_sessions_shipping_address_base
  - name: checkout_sessions_shipping_address_collection_base
  - name: checkout_sessions_shipping_base
  - name: checkout_sessions_tax_id_collection_base
  - name: checkout_sessions_total_details_base
  - name: checkout_sessions_total_details_breakdown_base
  - name: checkout_sessions_total_details_breakdown_discounts_base
  - name: checkout_sessions_total_details_breakdown_taxes_base
  - name: checkout_sessions_total_details_breakdown_taxes_rate_base
  - name: coupons_base
  - name: customers_address_base
  - name: customers_base
  - name: customers_cards_base
  - name: customers_discount_base
  - name: customers_discount_coupon_base
  - name: customers_invoice_settings_base
  - name: customers_shipping_address_base
  - name: customers_shipping_base
  - name: customers_subscriptions_base
  - name: disputes_balance_transactions_base
  - name: disputes_base
  - name: disputes_evidence_base
  - name: disputes_evidence_details_base
  - name: events_base
  - name: invoice_items_base
  - name: invoice_items_period_base
  - name: invoice_items_plan_base
  - name: invoice_items_plan_tiers_base
  - name: invoices_base
  - name: payment_intents_base
  - name: payment_intents_charges_base
  - name: payment_intents_last_payment_error_base
  - name: payment_intents_last_payment_error_payment_method_acss_debit_base
  - name: payment_intents_last_payment_error_payment_method_au_becs_debit_base
  - name: payment_intents_last_payment_error_payment_method_bacs_debit_base
  - name: payment_intents_last_payment_error_payment_method_base
  - name: payment_intents_last_payment_error_payment_method_billing_details_address_base
  - name: payment_intents_last_payment_error_payment_method_billing_details_base
  - name: payment_intents_last_payment_error_payment_method_boleto_base
  - name: payment_intents_last_payment_error_payment_method_card_base
  - name: payment_intents_last_payment_error_payment_method_card_checks_base
  - name: payment_intents_last_payment_error_payment_method_card_generated_from_base
  - name: payment_intents_last_payment_error_payment_method_card_generated_from_payment_method_details_base
  - name: payment_intents_last_payment_error_payment_method_card_generated_from_payment_method_details_card_present_base
  - name: payment_intents_last_payment_error_payment_method_card_generated_from_payment_method_details_card_present_receipt_bsql
  - name: payment_intents_last_payment_error_payment_method_card_networks_base
  - name: payment_intents_last_payment_error_payment_method_card_three_d_secure_usage_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_masterpass_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_masterpass_billing_address_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_masterpass_shipping_address_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_visa_checkout_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_visa_checkout_billing_address_base
  - name: payment_intents_last_payment_error_payment_method_card_wallet_visa_checkout_shipping_address_base
  - name: payment_intents_last_payment_error_payment_method_eps_base
  - name: payment_intents_last_payment_error_payment_method_fpx_base
  - name: payment_intents_last_payment_error_payment_method_ideal_base
  - name: payment_intents_last_payment_error_payment_method_p24_base
  - name: payment_intents_last_payment_error_payment_method_sepa_debit_base
  - name: payment_intents_last_payment_error_payment_method_sepa_debit_generated_from_base
  - name: payment_intents_last_payment_error_payment_method_sofort_base
  - name: payment_intents_next_action_alipay_handle_redirect_base
  - name: payment_intents_next_action_base
  - name: payment_intents_next_action_boleto_display_details_base
  - name: payment_intents_next_action_oxxo_display_details_base
  - name: payment_intents_next_action_redirect_to_url_base
  - name: payment_intents_next_action_verify_with_microdeposits_base
  - name: payment_intents_next_action_wechat_pay_display_qr_code_base
  - name: payment_intents_next_action_wechat_pay_redirect_to_android_app_base
  - name: payment_intents_next_action_wechat_pay_redirect_to_ios_app_base
  - name: payment_intents_shipping_address_base
  - name: payment_intents_shipping_base
  - name: payment_intents_transfer_data_base
  - name: payouts_bank_account_base
  - name: payouts_base
  - name: plans_base
  - name: plans_tiers_base
  - name: products_base
  - name: products_package_dimensions_base
  - name: promotion_codes_base
  - name: promotion_codes_coupon_applies_to_base
  - name: promotion_codes_coupon_base
  - name: promotion_codes_restrictions_base
  - name: refunds_base
  - name: subscriptions_base
  - name: subscriptions_discount_base
  - name: subscriptions_discount_coupon_base
  - name: subscriptions_items_base
  - name: subscriptions_plan_base
  - name: subscriptions_plan_tiers_base
  - name: transfers_base
  - name: transfers_reversals_base

- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID') }}"