version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
  - name: _airbyte_raw_managed_form_contributions_stream
  - name: _airbyte_raw_paid_contributions_stream
  - name: _airbyte_raw_refunded_contributions_stream
  - name: managed_form_contributions_base
  - name: paid_contributions_base
  - name: refunded_contributions_base
