{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    schema = "_airbyte_sv_blocks",
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ source('sv_blocks', '_airbyte_raw_registration_forms') }}
select
    {{ json_extract_scalar('_airbyte_data', ['distance_from_location'], ['distance_from_location']) }} as distance_from_location,
    {{ json_extract_scalar('_airbyte_data', ['metadata'], ['metadata']) }} as metadata,
    {{ json_extract_scalar('_airbyte_data', ['eligible_voting_age'], ['eligible_voting_age']) }} as eligible_voting_age,
    {{ json_extract_scalar('_airbyte_data', ['county'], ['county']) }} as county,
    {{ json_extract_scalar('_airbyte_data', ['social_security'], ['social_security']) }} as social_security,
    {{ json_extract_scalar('_airbyte_data', ['uuid'], ['uuid']) }} as uuid,
    {{ json_extract_scalar('_airbyte_data', ['pledge_card_data'], ['pledge_card_data']) }} as pledge_card_data,
    {{ json_extract_scalar('_airbyte_data', ['score'], ['score']) }} as score,
    {{ json_extract_scalar('_airbyte_data', ['identification'], ['identification']) }} as identification,
    {{ json_extract_scalar('_airbyte_data', ['voting_state'], ['voting_state']) }} as voting_state,
    {{ json_extract_scalar('_airbyte_data', ['id'], ['id']) }} as id,
    {{ json_extract_scalar('_airbyte_data', ['state_id'], ['state_id']) }} as state_id,
    {{ json_extract_scalar('_airbyte_data', ['longitude'], ['longitude']) }} as longitude,
    {{ json_extract_scalar('_airbyte_data', ['person_id'], ['person_id']) }} as person_id,
    {{ json_extract_scalar('_airbyte_data', ['ovr_status'], ['ovr_status']) }} as ovr_status,
    {{ json_extract_scalar('_airbyte_data', ['hard_copy_collected'], ['hard_copy_collected']) }} as hard_copy_collected,
    {{ json_extract_scalar('_airbyte_data', ['mailing_street_address_two'], ['mailing_street_address_two']) }} as mailing_street_address_two,
    {{ json_extract_scalar('_airbyte_data', ['completed'], ['completed']) }} as completed,
    {{ json_extract_scalar('_airbyte_data', ['created_by_user_id'], ['created_by_user_id']) }} as created_by_user_id,
    {{ json_extract_scalar('_airbyte_data', ['registration_date'], ['registration_date']) }} as registration_date,
    {{ json_extract_scalar('_airbyte_data', ['secondary_identification'], ['secondary_identification']) }} as secondary_identification,
    {{ json_extract_scalar('_airbyte_data', ['voting_city'], ['voting_city']) }} as voting_city,
    {{ json_extract_scalar('_airbyte_data', ['phone_number'], ['phone_number']) }} as phone_number,
    {{ json_extract_scalar('_airbyte_data', ['form_number'], ['form_number']) }} as form_number,
    {{ json_extract_scalar('_airbyte_data', ['party'], ['party']) }} as party,
    {{ json_extract_scalar('_airbyte_data', ['contacted_voter'], ['contacted_voter']) }} as contacted_voter,
    {{ json_extract_scalar('_airbyte_data', ['mailing_street_address_one'], ['mailing_street_address_one']) }} as mailing_street_address_one,
    {{ json_extract_scalar('_airbyte_data', ['gender'], ['gender']) }} as gender,
    {{ json_extract_scalar('_airbyte_data', ['ethnicity'], ['ethnicity']) }} as ethnicity,
    {{ json_extract_scalar('_airbyte_data', ['signature'], ['signature']) }} as signature,
    {{ json_extract_scalar('_airbyte_data', ['date_of_birth'], ['date_of_birth']) }} as date_of_birth,
    {{ json_extract_scalar('_airbyte_data', ['latitude'], ['latitude']) }} as latitude,
    {{ json_extract_scalar('_airbyte_data', ['delivery_id'], ['delivery_id']) }} as delivery_id,
    {{ json_extract_scalar('_airbyte_data', ['extras'], ['extras']) }} as extras,
    {{ json_extract_scalar('_airbyte_data', ['created_at'], ['created_at']) }} as created_at,
    {{ json_extract_scalar('_airbyte_data', ['voting_street_address_two'], ['voting_street_address_two']) }} as voting_street_address_two,
    {{ json_extract_scalar('_airbyte_data', ['voting_zipcode'], ['voting_zipcode']) }} as voting_zipcode,
    {{ json_extract_scalar('_airbyte_data', ['mailing_zipcode'], ['mailing_zipcode']) }} as mailing_zipcode,
    {{ json_extract_scalar('_airbyte_data', ['registration_type'], ['registration_type']) }} as registration_type,
    {{ json_extract_string_array('_airbyte_data', ['redacted_fields'], ['redacted_fields']) }} as redacted_fields,
    {{ json_extract_scalar('_airbyte_data', ['van_id'], ['van_id']) }} as van_id,
    {{ json_extract_scalar('_airbyte_data', ['name_prefix'], ['name_prefix']) }} as name_prefix,
    {{ json_extract_scalar('_airbyte_data', ['updated_at'], ['updated_at']) }} as updated_at,
    {{ json_extract_scalar('_airbyte_data', ['shift_id'], ['shift_id']) }} as shift_id,
    {{ json_extract_scalar('_airbyte_data', ['first_name'], ['first_name']) }} as first_name,
    {{ json_extract_scalar('_airbyte_data', ['online_registration'], ['online_registration']) }} as online_registration,
    {{ json_extract_scalar('_airbyte_data', ['por_data'], ['por_data']) }} as por_data,
    {{ json_extract_scalar('_airbyte_data', ['mailing_city'], ['mailing_city']) }} as mailing_city,
    {{ json_extract_scalar('_airbyte_data', ['mailing_state'], ['mailing_state']) }} as mailing_state,
    {{ json_extract_scalar('_airbyte_data', ['voting_street_address_one'], ['voting_street_address_one']) }} as voting_street_address_one,
    {{ json_extract_scalar('_airbyte_data', ['name_suffix'], ['name_suffix']) }} as name_suffix,
    {{ json_extract_scalar('_airbyte_data', ['twilio_match_data'], ['twilio_match_data']) }} as twilio_match_data,
    {{ json_extract_scalar('_airbyte_data', ['last_name'], ['last_name']) }} as last_name,
    {{ json_extract_scalar('_airbyte_data', ['middle_name'], ['middle_name']) }} as middle_name,
    {{ json_extract_scalar('_airbyte_data', ['us_citizen'], ['us_citizen']) }} as us_citizen,
    {{ json_extract_scalar('_airbyte_data', ['precinct'], ['precinct']) }} as precinct,
    {{ json_extract_scalar('_airbyte_data', ['email_address'], ['email_address']) }} as email_address,
    {{ json_extract_scalar('_airbyte_data', ['smarty_streets_match_data'], ['smarty_streets_match_data']) }} as smarty_streets_match_data,
    {{ json_extract_scalar('_airbyte_data', ['scan_id'], ['scan_id']) }} as scan_id,
    {{ json_extract_scalar('_airbyte_data', ['attempted'], ['attempted']) }} as attempted,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ source('sv_blocks', '_airbyte_raw_registration_forms') }} as table_alias
-- registration_forms
where 1 = 1

