version: 2

models:
  - name: airbyte_job
    config:
      elementary:
        timestamp_column: 'job_started_at'
    columns:
      - name: credits_billed
        data_tests:
          - elementary.column_anomalies:
              column_anomalies:
                - average
              anomaly_sensitivity: 2
              time_bucket:
                period: 'day'
                count: 1
              ignore_small_changes:  # Only alert if change is 50% or more of mean
                spike_failure_percent_threshold: 50
                drop_failure_percent_threshold: 50
              config:
                name: airbyte_credit_usage_monitor
