version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_admin_notes"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_ads_posts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_agencies"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_albums"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_best_page"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_blocked"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_canvas_elements"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_category_list"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_chat_plugin"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_claimed_urls"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_commerce_eligibility"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_commerce_orders"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_commerce_payouts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_commerce_transactions"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_connected_instagram_account"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_contact_address"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_copyright_whitelisted_partners"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_cover"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_crosspost_whitelisted_pages"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_custom_labels"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_custom_user_settings"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_engagement"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_events"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_global_brand_children"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_image_copyrights"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_indexed_videos"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_insights_8fc"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_instagram_accounts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_instagram_business_account"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_instant_articles_insights"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_leadgen_forms"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_leadgen_tos_accepting_user"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_live_videos"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_location"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_media_fingerprints"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_messaging_feature_review"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_messaging_feature_status"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_messenger_profile"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_mini_shop_storefront"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_nativeoffers"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_page_backed_instagram_accounts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_parking"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_payment_options"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_personas"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_picture"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_product_catalogs"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_published_posts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_ratings"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_restaurant_services"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_restaurant_specialties"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_roles"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_rtb_dynamic_posts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_scheduled_posts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_secondary_receivers"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_shop_setup_status"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_start_info"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_subscribed_apps"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_tabs"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_tagged"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_video_copyright_rules"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_video_lists"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_videos"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_visitor_posts"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page_voip_info"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_page"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_post_insights"
  - name: "{{ env_var('CTA_DATASET_ID') }}_raw__stream_post"