{{ config(
    partition_by = {"field": "_airbyte_extracted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = 'history_id'
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ source('cta', 'events_historicalevent') }}

select
   _airbyte_raw_id,
   _airbyte_extracted_at,
   _airbyte_meta,
   _airbyte_generation_id,
   id,
   zip,
   city,
   mode,
   notes,
   phone,
   plus4,
   state,
   title,
   venue,
   postal,
   region,
   status,
   country,
   ends_at,
   address1,
   address2,
   latitude,
   timezone,
   longitude,
   starts_at,
   us_county,
   created_at,
   creator_id,
   directions,
   history_id,
   is_private,
   updated_at,
   approved_at,
   campaign_id,
   ends_at_utc,
   is_approved,
   us_district,
   confirmed_at,
   history_date,
   history_type,
   merged_to_id,
   max_attendees,
   starts_at_utc,
   attendee_count,
   history_user_id,
   us_state_senate,
   host_is_confirmed,
   note_to_attendees,
   us_state_district,
   public_description,
   history_change_reason
from {{ source('cta', 'events_historicalevent') }}
