version: 2
sources:
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: airbyte_internal
  tables:
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_affiliations' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_event_co_hosts' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_event_tags' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_events' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_organizations' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_participations' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_sms_opt_ins' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_timeslots' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_users' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_van_events' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_van_locations' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_van_persons' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_van_shifts' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_van_signups' }}"
      columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null

- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables:
    - name: affiliations_base
    - name: event_co_hosts_base
    - name: event_tags_base
    - name: events_base
    - name: organizations_base
    - name: participations_base
    - name: sms_opt_ins_base
    - name: timeslots_base
    - name: users_base
    - name: van_events_base
    - name: van_locations_base
    - name: van_persons_base
    - name: van_shifts_base
    - name: van_signups_base


- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID', 'not-set') }}"
  tables:
    - name: affiliations
    - name: event_co_hosts
    - name: event_tags
    - name: events
    - name: organizations
    - name: participations
    - name: sms_opt_ins
    - name: timeslots
    - name: users
    - name: van_events
    - name: van_locations
    - name: van_persons
    - name: van_shifts
    - name: van_signups
