version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables:
    - name: _airbyte_raw_affiliations
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_event_co_hosts
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_event_tags
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_events
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_organizations
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_participations
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_sms_opt_ins
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_timeslots
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_users
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_van_events
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_van_locations
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_van_persons
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_van_shifts
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: _airbyte_raw_van_signups
      columns:
      - name: _airbyte_ab_id
        tests:
          - unique
          - not_null
      - name: _airbyte_emitted_at
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: _airbyte_data
        tests:
          - not_null
    - name: affiliations_base
    - name: event_co_hosts_base
    - name: event_tags_base
    - name: events_base
    - name: organizations_base
    - name: participations_base
    - name: sms_opt_ins_base
    - name: timeslots_base
    - name: users_base
    - name: van_events_base
    - name: van_locations_base
    - name: van_persons_base
    - name: van_shifts_base
    - name: van_signups_base


- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID') }}"
  tables:
    - name: affiliations
    - name: event_co_hosts
    - name: event_tags
    - name: events
    - name: organizations
    - name: participations
    - name: sms_opt_ins
    - name: timeslots
    - name: users
    - name: van_events
    - name: van_locations
    - name: van_persons
    - name: van_shifts
    - name: van_signups
