{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('refunded_contributions_stream_ab2') }}
select
    {{ dbt_utils.surrogate_key([
        'Fee',
        'Date',
        'Amount',
        'Mobile',
        'Approved',
        'Comments',
        'Donor_ID',
        'Apple_Pay',
        'Donor_ZIP',
        'Recipient',
        'Refund_ID',
        'Check_Date',
        'Donor_City',
        'Partner_ID',
        'Payment_ID',
        'Receipt_ID',
        'Donor_Addr1',
        'Donor_Addr2',
        'Donor_Email',
        'Donor_Phone',
        'Donor_State',
        'Double_Down',
        'Lineitem_ID',
        'Merchant_ID',
        'Recovery_ID',
        'Refund_Date',
        'AB_Test_Name',
        'AB_Variation',
        'Check_Number',
        'Employer_ZIP',
        'Payment_Date',
        'Recipient_ID',
        'Recur_Weekly',
        'Shipping_Zip',
        'Donor_Country',
        'Employer_City',
        'Fundraiser_ID',
        'Gift_Declined',
        'Recovery_Date',
        'Shipping_City',
        'Donor_Employer',
        'Employer_Addr1',
        'Employer_Addr2',
        'Employer_State',
        'Reference_Code',
        'Shipping_Addr1',
        'Shipping_State',
        'Disbursement_ID',
        'Donor_Last_Name',
        'Gift_Identifier',
        'Smart_Recurring',
        'Donor_First_Name',
        'Donor_Occupation',
        'Employer_Country',
        'Fundraising_Page',
        'Reference_Code_2',
        'Shipping_Country',
        'Disbursement_Date',
        'Recurrence_Number',
        'Smart_Boost_Shown',
        'New_Express_Signup',
        'Recipient_Election',
        'Smart_Boost_Amount',
        'Fundraising_Partner',
        'Recipient_Committee',
        'Text_Message_Opt_In',
        'ActBlue_Express_Lane',
        'Custom_Field_1_Label',
        'Custom_Field_1_Value',
        'ActBlue_Express_Donor',
        'Partner_Contact_Email',
        'Recurring_Total_Months',
        'Recurring_Upsell_Shown',
        'Fundraiser_Recipient_ID',
        'Weekly_Recurring_Amount',
        'Fundraiser_Contact_Email',
        'Monthly_Recurring_Amount',
        'Partner_Contact_Last_Name',
        'Partner_Contact_First_Name',
        'Recurring_Upsell_Succeeded',
        'Fundraiser_Contact_Last_Name',
        'Fundraiser_Contact_First_Name',
        'Card_Replaced_by_Account_Updater',
    ]) }} as _airbyte_refunded_contributions_stream_hashid,
    tmp.*
from {{ ref('refunded_contributions_stream_ab2') }} tmp
-- refunded_contributions_stream
where 1 = 1

