version: 2
sources:
- name: cta
  database: "{{env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables: "{{ var('cta_sources') }}"
- name: partner
  database: "{{env_var('PROJECT_ID') }}"
  schema: "{{ env_var('DATASET_ID') }}"
  tables: "{{ var('partner_sources') }}"