version: 2
sources:
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_campaigns' }}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null

- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables:          
  - name: campaigns_base
    columns:
      - name: _airbyte_campaigns_hashid
        tests:
          - unique
          - not_null
      - name: id
        tests:
          - unique
          - not_null
- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID', 'not-set') }}"
  tables:
  - name: campaigns