{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id'
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('ads_stats_daily_ab1') }}
select
    cast(id as {{ dbt_utils.type_string() }}) as id,
    cast(type as {{ dbt_utils.type_string() }}) as type,
    cast(saves as {{ dbt_utils.type_float() }}) as saves,
    cast(spend as {{ dbt_utils.type_float() }}) as spend,
    cast(shares as {{ dbt_utils.type_float() }}) as shares,
    cast(swipes as {{ dbt_utils.type_float() }}) as swipes,
    cast(uniques as {{ dbt_utils.type_float() }}) as uniques,
    cast({{ empty_string_to_null('end_time') }} as {{ type_timestamp_with_timezone() }}) as end_time,
    cast(frequency as {{ dbt_utils.type_float() }}) as frequency,
    cast(quartile_1 as {{ dbt_utils.type_float() }}) as quartile_1,
    cast(quartile_2 as {{ dbt_utils.type_float() }}) as quartile_2,
    cast(quartile_3 as {{ dbt_utils.type_float() }}) as quartile_3,
    cast({{ empty_string_to_null('start_time') }} as {{ type_timestamp_with_timezone() }}) as start_time,
    cast(granularity as {{ dbt_utils.type_string() }}) as granularity,
    cast(impressions as {{ dbt_utils.type_float() }}) as impressions,
    cast(total_reach as {{ dbt_utils.type_float() }}) as total_reach,
    cast(video_views as {{ dbt_utils.type_float() }}) as video_views,
    cast(earned_reach as {{ dbt_utils.type_float() }}) as earned_reach,
    cast(ios_installs as {{ dbt_utils.type_float() }}) as ios_installs,
    cast(native_leads as {{ dbt_utils.type_float() }}) as native_leads,
    cast(custom_event_1 as {{ dbt_utils.type_float() }}) as custom_event_1,
    cast(custom_event_2 as {{ dbt_utils.type_float() }}) as custom_event_2,
    cast(custom_event_3 as {{ dbt_utils.type_float() }}) as custom_event_3,
    cast(custom_event_4 as {{ dbt_utils.type_float() }}) as custom_event_4,
    cast(custom_event_5 as {{ dbt_utils.type_float() }}) as custom_event_5,
    cast(total_installs as {{ dbt_utils.type_float() }}) as total_installs,
    cast(conversion_rate as {{ dbt_utils.type_float() }}) as conversion_rate,
    cast(conversion_save as {{ dbt_utils.type_float() }}) as conversion_save,
    cast(video_views_15s as {{ dbt_utils.type_float() }}) as video_views_15s,
    cast(view_completion as {{ dbt_utils.type_float() }}) as view_completion,
    cast(android_installs as {{ dbt_utils.type_float() }}) as android_installs,
    cast(conversion_login as {{ dbt_utils.type_float() }}) as conversion_login,
    cast(conversion_share as {{ dbt_utils.type_float() }}) as conversion_share,
    cast(paid_impressions as {{ dbt_utils.type_float() }}) as paid_impressions,
    cast(play_time_millis as {{ dbt_utils.type_float() }}) as play_time_millis,
    cast(swipe_up_percent as {{ dbt_utils.type_float() }}) as swipe_up_percent,
    cast(view_time_millis as {{ dbt_utils.type_float() }}) as view_time_millis,
    cast(conversion_invite as {{ dbt_utils.type_float() }}) as conversion_invite,
    cast(total_impressions as {{ dbt_utils.type_float() }}) as total_impressions,
    cast(attachment_uniques as {{ dbt_utils.type_float() }}) as attachment_uniques,
    cast(conversion_ad_view as {{ dbt_utils.type_float() }}) as conversion_ad_view,
    cast(conversion_reserve as {{ dbt_utils.type_float() }}) as conversion_reserve,
    cast(earned_impressions as {{ dbt_utils.type_float() }}) as earned_impressions,
    cast(screen_time_millis as {{ dbt_utils.type_float() }}) as screen_time_millis,
    cast(conversion_ad_click as {{ dbt_utils.type_float() }}) as conversion_ad_click,
    cast(conversion_add_cart as {{ dbt_utils.type_float() }}) as conversion_add_cart,
    cast(conversion_searches as {{ dbt_utils.type_float() }}) as conversion_searches,
    cast(attachment_frequency as {{ dbt_utils.type_float() }}) as attachment_frequency,
    cast(avg_view_time_millis as {{ dbt_utils.type_float() }}) as avg_view_time_millis,
    cast(conversion_app_opens as {{ dbt_utils.type_float() }}) as conversion_app_opens,
    cast(conversion_list_view as {{ dbt_utils.type_float() }}) as conversion_list_view,
    cast(conversion_purchases as {{ dbt_utils.type_float() }}) as conversion_purchases,
    cast(conversion_subscribe as {{ dbt_utils.type_float() }}) as conversion_subscribe,
    cast(attachment_quartile_1 as {{ dbt_utils.type_float() }}) as attachment_quartile_1,
    cast(attachment_quartile_2 as {{ dbt_utils.type_float() }}) as attachment_quartile_2,
    cast(attachment_quartile_3 as {{ dbt_utils.type_float() }}) as attachment_quartile_3,
    cast(conversion_page_views as {{ dbt_utils.type_float() }}) as conversion_page_views,
    cast(attachment_impressions as {{ dbt_utils.type_float() }}) as attachment_impressions,
    cast(avg_screen_time_millis as {{ dbt_utils.type_float() }}) as avg_screen_time_millis,
    cast(conversion_add_billing as {{ dbt_utils.type_float() }}) as conversion_add_billing,
    cast(conversion_start_trial as {{ dbt_utils.type_float() }}) as conversion_start_trial,
    cast(video_views_time_based as {{ dbt_utils.type_float() }}) as video_views_time_based,
    cast(conversion_view_content as {{ dbt_utils.type_float() }}) as conversion_view_content,
    cast(conversion_spend_credits as {{ dbt_utils.type_float() }}) as conversion_spend_credits,
    cast(conversion_start_checkout as {{ dbt_utils.type_float() }}) as conversion_start_checkout,
    cast(attachment_view_completion as {{ dbt_utils.type_float() }}) as attachment_view_completion,
    cast(conversion_add_to_wishlist as {{ dbt_utils.type_float() }}) as conversion_add_to_wishlist,
    cast(conversion_level_completes as {{ dbt_utils.type_float() }}) as conversion_level_completes,
    cast(conversion_purchases_value as {{ dbt_utils.type_float() }}) as conversion_purchases_value,
    cast(conversion_complete_tutorial as {{ dbt_utils.type_float() }}) as conversion_complete_tutorial,
    cast(attachment_avg_view_time_millis as {{ dbt_utils.type_float() }}) as attachment_avg_view_time_millis,
    cast(conversion_achievement_unlocked as {{ dbt_utils.type_float() }}) as conversion_achievement_unlocked,
    cast(attachment_total_view_time_millis as {{ dbt_utils.type_float() }}) as attachment_total_view_time_millis,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ ref('ads_stats_daily_ab1') }}
where 1 = 1
