select
    CurrencyRef,
    ExchangeRate,
    TxnDate,
    airbyte_cursor,
    DepartmentRef,
    Line,
    SyncToken,
    DepositToAccountRef,
    sparse,
    TotalAmt,
    MetaData,
    domain,
    Id,
    CashBack,
    PrivateNote,
    _airbyte_extracted_at,
    _airbyte_deposits_hashid
from {{ source('cta','deposits_base') }}
