select
    CurrencyRef,
    ExchangeRate,
    TaxRateRef,
    Adjustment,
    TxnDate,
    airbyte_cursor,
    Line,
    SyncToken,
    sparse,
    MetaData,
    domain,
    DocNumber,
    Id,
    PrivateNote,
    TxnTaxDetail,
    _airbyte_extracted_at,
    _airbyte_journal_entries_hashid
from {{ source('cta','journal_entries_base') }}
