version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables: 
    - name: group_members
    - name: groups
    - name: users
  
    - name: group_members_base
    - name: groups_base
    - name: users_base