{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('landing_page_signups_ab2') }}
select
    {{ dbt_utils.generate_surrogate_key([
        'mailing_county',
        'state_api_submission_result',
        'language',
        'source',
        'voting_state',
        boolean_to_string('finish_with_state'),
        'id',
        'tracking_source',
        boolean_to_string('citizen'),
        'phone_type',
        'mailing_street_address_two',
        boolean_to_string('built_via_api'),
        'organization_name',
        'vr_app_status_datetime',
        boolean_to_string('opt_in_partner_sms'),
        'phone',
        'started_registration_at',
        'voting_city',
        'voting_county',
        'party',
        boolean_to_string('submitted_signature_to_state_api'),
        'status',
        boolean_to_string('has_state_license'),
        'mailing_street_address_one',
        'date_of_birth',
        'created_at',
        'voting_street_address_two',
        'voting_zipcode',
        'mailing_zipcode',
        'name_prefix',
        boolean_to_string('volunteer_for_rtv'),
        'updated_at',
        'vr_app_status',
        'vr_submission_mod',
        'vr_submission_error',
        'first_name',
        'email',
        'tracking_id',
        'mailing_city',
        boolean_to_string('submitted_via_vendor_api'),
        boolean_to_string('opt_in_sms'),
        'mailing_state',
        'voting_street_address_one',
        'race',
        'name_suffix',
        boolean_to_string('has_ssn'),
        boolean_to_string('opt_in_email'),
        'last_name',
        'middle_name',
        'ineligible_reason',
        boolean_to_string('volunteer_for_partner'),
        'source_id',
        'vr_app_status_details',
        boolean_to_string('pre_registered'),
        boolean_to_string('opt_in_partner_email'),
    ]) }} as _airbyte_landing_page_signups_hashid,
    tmp.*
from {{ ref('landing_page_signups_ab2') }} tmp
-- landing_page_signups
where 1 = 1
{{ incremental_clause('_airbyte_emitted_at') }}

