{{ config(
    cluster_by = "_airbyte_emitted_at",
    partition_by = {"field": "_airbyte_emitted_at", "data_type": "timestamp", "granularity": "day"},
    unique_key = '_airbyte_ab_id',
    tags = [ "top-level-intermediate" ]
) }}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ source('cta', '_airbyte_raw_scans_qc_overview') }}
select
    {{ json_extract_scalar('_airbyte_data', ['distance_from_location'], ['distance_from_location']) }} as distance_from_location,
    {{ json_extract_scalar('_airbyte_data', ['eligible_voting_age'], ['eligible_voting_age']) }} as eligible_voting_age,
    {{ json_extract_scalar('_airbyte_data', ['canvasser_id'], ['canvasser_id']) }} as canvasser_id,
    {{ json_extract_scalar('_airbyte_data', ['visual_qc_completed_by_user_id'], ['visual_qc_completed_by_user_id']) }} as visual_qc_completed_by_user_id,
    {{ json_extract_scalar('_airbyte_data', ['program_state'], ['program_state']) }} as program_state,
    {{ json_extract_scalar('_airbyte_data', ['data_entry_time'], ['data_entry_time']) }} as data_entry_time,
    {{ json_extract_scalar('_airbyte_data', ['bad_number'], ['bad_number']) }} as bad_number,
    {{ json_extract_scalar('_airbyte_data', ['field_start'], ['field_start']) }} as field_start,
    {{ json_extract_scalar('_airbyte_data', ['shift_type'], ['shift_type']) }} as shift_type,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_id'], ['collection_location_id']) }} as collection_location_id,
    {{ json_extract_scalar('_airbyte_data', ['identification'], ['identification']) }} as identification,
    {{ json_extract_scalar('_airbyte_data', ['voter_registration_scan_id'], ['voter_registration_scan_id']) }} as voter_registration_scan_id,
    {{ json_extract_scalar('_airbyte_data', ['voting_state'], ['voting_state']) }} as voting_state,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_zip'], ['collection_location_zip']) }} as collection_location_zip,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_city'], ['collection_location_city']) }} as collection_location_city,
    {{ json_extract_scalar('_airbyte_data', ['collective_name'], ['collective_name']) }} as collective_name,
    {{ json_extract_scalar('_airbyte_data', ['visual_qc_county'], ['visual_qc_county']) }} as visual_qc_county,
    {{ json_extract_scalar('_airbyte_data', ['address_validated'], ['address_validated']) }} as address_validated,
    {{ json_extract_scalar('_airbyte_data', ['qc_deadline'], ['qc_deadline']) }} as qc_deadline,
    {{ json_extract_scalar('_airbyte_data', ['mailing_street_address_two'], ['mailing_street_address_two']) }} as mailing_street_address_two,
    {{ json_extract_scalar('_airbyte_data', ['organization_name'], ['organization_name']) }} as organization_name,
    {{ json_extract_scalar('_airbyte_data', ['canvasser_last_name'], ['canvasser_last_name']) }} as canvasser_last_name,
    {{ json_extract_scalar('_airbyte_data', ['shift_start'], ['shift_start']) }} as shift_start,
    {{ json_extract_scalar('_airbyte_data', ['upload_time'], ['upload_time']) }} as upload_time,
    {{ json_extract_scalar('_airbyte_data', ['name'], ['name']) }} as name,
    {{ json_extract_scalar('_airbyte_data', ['voting_city'], ['voting_city']) }} as voting_city,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_name'], ['collection_location_name']) }} as collection_location_name,
    {{ json_extract_scalar('_airbyte_data', ['phone_number'], ['phone_number']) }} as phone_number,
    {{ json_extract_scalar('_airbyte_data', ['party'], ['party']) }} as party,
    {{ json_extract_scalar('_airbyte_data', ['voting_address_latitude'], ['voting_address_latitude']) }} as voting_address_latitude,
    {{ json_extract_scalar('_airbyte_data', ['qc_organization'], ['qc_organization']) }} as qc_organization,
    {{ json_extract_scalar('_airbyte_data', ['mailing_street_address_one'], ['mailing_street_address_one']) }} as mailing_street_address_one,
    {{ json_extract_scalar('_airbyte_data', ['gender'], ['gender']) }} as gender,
    {{ json_extract_scalar('_airbyte_data', ['ethnicity'], ['ethnicity']) }} as ethnicity,
    {{ json_extract_scalar('_airbyte_data', ['signature'], ['signature']) }} as signature,
    {{ json_extract_scalar('_airbyte_data', ['turf_parent_id'], ['turf_parent_id']) }} as turf_parent_id,
    {{ json_extract_scalar('_airbyte_data', ['date_of_birth'], ['date_of_birth']) }} as date_of_birth,
    {{ json_extract_scalar('_airbyte_data', ['extras'], ['extras']) }} as extras,
    {{ json_extract_scalar('_airbyte_data', ['voting_street_address_two'], ['voting_street_address_two']) }} as voting_street_address_two,
    {{ json_extract_scalar('_airbyte_data', ['voting_address_longitude'], ['voting_address_longitude']) }} as voting_address_longitude,
    {{ json_extract_scalar('_airbyte_data', ['phone_verification_completed_by_user_id'], ['phone_verification_completed_by_user_id']) }} as phone_verification_completed_by_user_id,
    {{ json_extract_scalar('_airbyte_data', ['voting_zipcode'], ['voting_zipcode']) }} as voting_zipcode,
    {{ json_extract_scalar('_airbyte_data', ['mailing_zipcode'], ['mailing_zipcode']) }} as mailing_zipcode,
    {{ json_extract_scalar('_airbyte_data', ['registration_type'], ['registration_type']) }} as registration_type,
    {{ json_extract_scalar('_airbyte_data', ['registration_form_id'], ['registration_form_id']) }} as registration_form_id,
    {{ json_extract_scalar('_airbyte_data', ['packet_filename'], ['packet_filename']) }} as packet_filename,
    {{ json_extract_scalar('_airbyte_data', ['name_prefix'], ['name_prefix']) }} as name_prefix,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_longitude'], ['collection_location_longitude']) }} as collection_location_longitude,
    {{ json_extract_scalar('_airbyte_data', ['through_visual_qc'], ['through_visual_qc']) }} as through_visual_qc,
    {{ json_extract_scalar('_airbyte_data', ['turf_id'], ['turf_id']) }} as turf_id,
    {{ json_extract_scalar('_airbyte_data', ['van_committee_id'], ['van_committee_id']) }} as van_committee_id,
    {{ json_extract_scalar('_airbyte_data', ['shift_id'], ['shift_id']) }} as shift_id,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_latitude'], ['collection_location_latitude']) }} as collection_location_latitude,
    {{ json_extract_scalar('_airbyte_data', ['shift_end'], ['shift_end']) }} as shift_end,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_county'], ['collection_location_county']) }} as collection_location_county,
    {{ json_extract_scalar('_airbyte_data', ['first_name'], ['first_name']) }} as first_name,
    {{ json_extract_scalar('_airbyte_data', ['data_entry_county'], ['data_entry_county']) }} as data_entry_county,
    {{ json_extract_scalar('_airbyte_data', ['voter_registration_scan_updated_at'], ['voter_registration_scan_updated_at']) }} as voter_registration_scan_updated_at,
    {{ json_extract_scalar('_airbyte_data', ['digital'], ['digital']) }} as digital,
    {{ json_extract_scalar('_airbyte_data', ['mailing_city'], ['mailing_city']) }} as mailing_city,
    {{ json_extract_scalar('_airbyte_data', ['is_registration_form'], ['is_registration_form']) }} as is_registration_form,
    {{ json_extract_scalar('_airbyte_data', ['voting_street_address_one'], ['voting_street_address_one']) }} as voting_street_address_one,
    {{ json_extract_scalar('_airbyte_data', ['name_suffix'], ['name_suffix']) }} as name_suffix,
    {{ json_extract_scalar('_airbyte_data', ['data_entry_updated_at'], ['data_entry_updated_at']) }} as data_entry_updated_at,
    {{ json_extract_scalar('_airbyte_data', ['last_name'], ['last_name']) }} as last_name,
    {{ json_extract_scalar('_airbyte_data', ['middle_name'], ['middle_name']) }} as middle_name,
    {{ json_extract_scalar('_airbyte_data', ['voter_registration_scan_batches_id'], ['voter_registration_scan_batches_id']) }} as voter_registration_scan_batches_id,
    {{ json_extract_scalar('_airbyte_data', ['phone_validated'], ['phone_validated']) }} as phone_validated,
    {{ json_extract_scalar('_airbyte_data', ['email_address'], ['email_address']) }} as email_address,
    {{ json_extract_scalar('_airbyte_data', ['phone_verified'], ['phone_verified']) }} as phone_verified,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_street_address'], ['collection_location_street_address']) }} as collection_location_street_address,
    {{ json_extract_scalar('_airbyte_data', ['field_end'], ['field_end']) }} as field_end,
    {{ json_extract_scalar('_airbyte_data', ['canvasser_first_name'], ['canvasser_first_name']) }} as canvasser_first_name,
    {{ json_extract_scalar('_airbyte_data', ['complete'], ['complete']) }} as complete,
    {{ json_extract_scalar('_airbyte_data', ['has_phone_number_visual_qc'], ['has_phone_number_visual_qc']) }} as has_phone_number_visual_qc,
    {{ json_extract_scalar('_airbyte_data', ['collection_location_state'], ['collection_location_state']) }} as collection_location_state,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    {{ current_timestamp() }} as _airbyte_normalized_at
from {{ source('cta', '_airbyte_raw_scans_qc_overview') }} as table_alias
-- scans_qc_overview
where 1 = 1

