version: 2
sources:
- name: cta_raw
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: airbyte_internal
  tables:
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ad_account'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ad_creatives'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ad_sets'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ads'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ads_insights'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_ads_insights_platform_and_device'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null
  - name: "{{ env_var('CTA_DATASET_ID', 'not-set') ~ '_raw__stream_campaigns'}}"
    columns:
      - name: _airbyte_raw_id
        tests:
          - unique
          - not_null
      - name: _airbyte_extracted_at
      - name: _airbyte_data
        tests:
          - not_null

- name: cta
  database: "{{ env_var('CTA_PROJECT_ID', 'not-set') }}"
  schema: "{{ env_var('CTA_DATASET_ID', 'not-set') }}"
  tables:
  - name: ads_insights_overall_base
  - name: ads_insights_platform_and_device_base
  - name: ads_base
  - name: ad_creatives_base
  - name: ad_sets_base
  - name: ad_account_base
  - name: campaigns_base
  - name: account_report_base
  - name: campaign_report_base
  - name: ad_set_report_base

- name: partner
  database: "{{ env_var('PARTNER_PROJECT_ID') }}"
  schema: "{{ env_var('PARTNER_DATASET_ID') }}"
  tables:
  - name: ads_insights_overall
  - name: ads_insights_platform_and_device
  - name: ads
  - name: ad_creatives
  - name: ad_sets
  - name: ad_account
  - name: campaigns
  - name: account_report
  - name: campaign_report
  - name: ad_set_report