{{ config(
    unique_key = 'id',
    materialized = "incremental",
    incremental_strategy = "merge",
    on_schema_change = "sync_all_columns",
) }}

select
    id,
    email_config_id,
    group_id,
    responder_id,
    product_id,
    company_id,
    JSON_EXTRACT_SCALAR(stats, '$.resolved_at') as stats_resolved_at,
    JSON_EXTRACT_SCALAR(stats, '$.first_responded_at') as stats_first_responded_at,
    JSON_EXTRACT_SCALAR(stats, '$.closed_at') as stats_closed_at,
    fr_escalated,
    spam,
    priority,
    requester_id,
    source,
    status,
    subject,
    type,
    SAFE_CAST(created_at as timestamp) as created_at,
    SAFE_CAST(updated_at as timestamp) as updated_at,
    SAFE_CAST(due_by as timestamp) as due_by,
    SAFE_CAST(fr_due_by as timestamp) as fr_due_by,
    is_escalated,
    description_text,
    description,
    association_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_affiliate_name') as custom_cf_affiliate_name,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_pipeline_state') as custom_cf_pipeline_state,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_status') as custom_cf_status,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_van_state') as custom_cf_van_state,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_due_date') as custom_cf_due_date,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_internal_type') as custom_cf_internal_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_tool') as custom_cf_tool,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_other_comments') as custom_cf_other_comments,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_tmc_tool') as custom_cf_tmc_tool,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_information_requested') as custom_cf_information_requested,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_engineering_ticket_type') as custom_cf_engineering_ticket_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_van_committee_type') as custom_cf_van_committee_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_github_branch_url') as custom_cf_github_branch_url,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_sync_type') as custom_cf_sync_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_member_request') as custom_cf_member_request,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_sprint_type') as custom_cf_sprint_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_urgency') as custom_cf_urgency,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_van_committee_name') as custom_cf_van_committee_name,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_organizing_strategy') as custom_cf_organizing_strategy,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_data_sync') as custom_cf_data_sync,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_labelonly_working_group_interest') as custom_cf_labelonly_working_group_interest,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_sprint_points') as custom_cf_sprint_points,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_labelonly_area_of_expertise') as custom_cf_labelonly_area_of_expertise,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_communication') as custom_cf_communication,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_digital_strategy') as custom_cf_digital_strategy,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_working_group_interest') as custom_cf_working_group_interest,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_electoral_strategy') as custom_cf_electoral_strategy,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_organizational_development') as custom_cf_organizational_development,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_sync_tool') as custom_cf_sync_tool,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_kind_of_resource_do_you_need_ie_zoom_training_1_pager_slide_deck_etc') as custom_cf_what_kind_of_resource_do_you_need_ie_zoom_training_1_pager_slide_deck_etc,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_topic_skill_or_question_do_you_want_the_materials_to_cover') as custom_cf_what_topic_skill_or_question_do_you_want_the_materials_to_cover,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_tool_995966') as custom_cf_tool_995966,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_are_there_any_accessibilityrequirements_for_us_to_be_mindful_ofie_do_the_materials_needto_be_in_spanish') as custom_cf_are_there_any_accessibilityrequirements_for_us_to_be_mindful_ofie_do_the_materials_needto_be_in_spanish,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_github_url') as custom_cf_github_url,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_if_load_score_to_tool_what_tool') as custom_cf_if_load_score_to_tool_what_tool,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_if_documentation_what_is_your_need') as custom_cf_if_documentation_what_is_your_need,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_request_type') as custom_cf_request_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_if_documentation_what_documentation') as custom_cf_if_documentation_what_documentation,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_documentation_link') as custom_cf_documentation_link,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_documentation_section') as custom_cf_documentation_section,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_pod') as custom_cf_pod,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_type_of_professional_development_request_is_this') as custom_cf_what_type_of_professional_development_request_is_this,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_how_do_you_want_tmc_to_pay_for_the_course_587712') as custom_cf_how_do_you_want_tmc_to_pay_for_the_course_587712,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_delivery_name_and_address_if_needed') as custom_cf_delivery_name_and_address_if_needed,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_is_this_request_mandatory_by_tmc_or_voluntary_762026') as custom_cf_is_this_request_mandatory_by_tmc_or_voluntary_762026,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_is_the_total_cost_of_the_request') as custom_cf_what_is_the_total_cost_of_the_request,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_delivery_name_and_address_if_needed_771907') as custom_cf_delivery_name_and_address_if_needed_771907,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_type_of_expense_request_is_this') as custom_cf_what_type_of_expense_request_is_this,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_is_the_link_for_purchase_if_multiple_items_please_number_each_item_in_the_description_box_and_include_each_link') as custom_cf_what_is_the_link_for_purchase_if_multiple_items_please_number_each_item_in_the_description_box_and_include_each_link,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_is_the_total_cost_of_this_request') as custom_cf_what_is_the_total_cost_of_this_request,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_dt_primary_automated_do_not_fill_out') as custom_cf_dt_primary_automated_do_not_fill_out,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_if_this_is_a_new_staff_member_what_is_their_personal_email') as custom_cf_if_this_is_a_new_staff_member_what_is_their_personal_email,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_is_a_staff_member_being_offboarded_or_onboarded') as custom_cf_is_a_staff_member_being_offboarded_or_onboarded,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_please_leave_any_special_notes_about_the_onoff_boarding_in_the_description_field_below_if_there_are_any') as custom_cf_please_leave_any_special_notes_about_the_onoff_boarding_in_the_description_field_below_if_there_are_any,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_is_the_full_name_of_the_staff_member') as custom_cf_what_is_the_full_name_of_the_staff_member,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_is_the_position_of_the_staff_member') as custom_cf_what_is_the_position_of_the_staff_member,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_state') as custom_cf_state,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_which_tools') as custom_cf_which_tools,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_test') as custom_cf_test,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_tools_or_tool_types_are_you_looking_for_information_on') as custom_cf_what_tools_or_tool_types_are_you_looking_for_information_on,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_which_of_the_following_are_you_requesting') as custom_cf_which_of_the_following_are_you_requesting,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_questions_do_you_want_answered_please_be_specific') as custom_cf_what_questions_do_you_want_answered_please_be_specific,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_what_is_the_billing_concern_or_request_please_also_note_any_time_sensitivity') as custom_cf_what_is_the_billing_concern_or_request_please_also_note_any_time_sensitivity,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_tool_800367') as custom_cf_tool_800367,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_please_list_any_relevant_support_request_numbers') as custom_cf_please_list_any_relevant_support_request_numbers,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_feedback_type') as custom_cf_feedback_type,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_minipod_automated_do_not_fill_out') as custom_cf_minipod_automated_do_not_fill_out,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_commitment_level') as custom_cf_commitment_level,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_vendor_name') as custom_cf_vendor_name,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_contact_name_email') as custom_cf_contact_name_email,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_donation_if_different') as custom_cf_donation_if_different,
    JSON_EXTRACT_SCALAR(custom_fields, '$.cf_tool_498589') as custom_cf_tool_498589,
    cc_emails,
    fwd_emails,
    reply_cc_emails,
    tags,
    to_emails
from {{ ref("tickets_ab2") }}
-- ticket from {{ source('cta', '_airbyte_raw_tickets') }}
where 1 = 1