normalize:
  outputs:

# ===== DEV ENVIRONMENTS =====
    dev-partner:
      #Project id for the partner we are sending the data to.
      project: dev-partner-a-25693fa5
      #Dataset in the partner project we are sending data to.
      dataset: facebook_marketing
      location: US
      method: oauth
      priority: interactive
      retries: 1
      threads: 8
      type: bigquery
    dev-cta:
      project: dev3869c056
      #dataset name must match the one in the destination connection!
      #Dt is where the _airbyte_raw tables get delivered, and where the CTEs will look
      dataset: dev_fb_marketing_latest_conn
      location: US
      method: oauth
      priority: interactive
      retries: 1
      threads: 8
      type: bigquery

# ===== PROD ENVIRONMENTS =====
    prod-vfp:
      #Project id for the partner we are sending the data to.
      project: prod-vfp-176bffe6
      #Dt is where the _airbyte_raw tables get delivered, and where the CTEs will look
      dataset: facebook_marketing
      location: US
      method: oauth
      priority: interactive
      retries: 1
      threads: 8
      type: bigquery
    prod-partner-a:
      #Project id for the partner we are sending the data to.
      project: prod-partner-a-176bffe6
      #Dt is where the _airbyte_raw tables get delivered, and where the CTEs will look
      dataset: facebook_marketing
      location: US
      method: oauth
      priority: interactive
      retries: 1
      threads: 8
      type: bigquery
    prod-cta:
      project: prod8b61f23e
      #Dataset in the partner project we are sending data to.
      dataset: vfp_facebook_marketing_cta
      location: US
      method: oauth
      priority: interactive
      retries: 1
      threads: 8
      type: bigquery

  target: default