version: 2
sources:
- name: cta
  database: "{{ env_var('CTA_PROJECT_ID') }}"
  schema: "{{ env_var('CTA_DATASET_ID') }}"
  tables: 
    - name: absentee_ballot_request_forms
    - name: activism_options_configs
    - name: activist_code_counts
    - name: activist_codes
    - name: activities
    - name: address_districts
    - name: addresses
    - name: admin_users
    - name: age_to_bin
    - name: announcements
    - name: announcements_views
    - name: ar_internal_metadata
    - name: blocked_tokens
    - name: campaigns
    - name: campaigns_people
    - name: campaigns_teams
    - name: canvassers
    - name: captricity_batches
    - name: catalist_uploads
    - name: catalist_uploads_registration_forms
    - name: check_in_answers
    - name: check_in_questions
    - name: check_ins
    - name: collections
    - name: collections_roles
    - name: contact_methods
    - name: coorganizations
    - name: counties
    - name: dashboard_layouts
    - name: dashboard_widgets
    - name: delayed_jobs
    - name: deliveries
    - name: delivery_forms_exclusions
    - name: denominations
    - name: denominations_organizations
    - name: denominations_people
    - name: district_types
    - name: districts
    - name: documents
    - name: elections
    - name: email_templates
    - name: email_templates_events
    - name: event_attendees
    - name: event_documents
    - name: event_shifts
    - name: event_types
    - name: events
    - name: events_teams
    - name: field_management_goals
    - name: field_management_projections
    - name: filter_rules
    - name: filter_views
    - name: folders
    - name: friendly_id_slugs
    - name: groupings
    - name: import_files
    - name: imports
    - name: imports_error_rows
    - name: landing_page_signups
    - name: list_folders
    - name: list_folders_users
    - name: lists
    - name: lists_people
    - name: locations
    - name: locations_organizations
    - name: meetings
    - name: metrics
    - name: missing_fks
    - name: notes
    - name: organization_memberships
    - name: organizations
    - name: organizations_teams
    - name: parties
    - name: people
    - name: petition_packets
    - name: petitions_books
    - name: petitions_canvasser_pages
    - name: petitions_pages
    - name: petitions_signatures
    - name: phone_banking_answer_options
    - name: phone_banking_calls
    - name: phone_banking_phone_banks
    - name: phone_banking_questions
    - name: phone_banking_responses
    - name: phone_banking_script_objects
    - name: phone_banking_script_texts
    - name: phone_banking_scripts
    - name: phone_banking_sessions
    - name: phone_verification_questions
    - name: phone_verification_responses
    - name: projections
    - name: public_event_links
    - name: quality_control_comments
    - name: quality_control_comments_users
    - name: quality_control_flag_triggers
    - name: quality_control_flags
    - name: quality_control_flags_views
    - name: quality_control_flags_voter_registration_scans
    - name: quality_control_phone_verification_calls
    - name: quality_control_phone_verification_question_translations
    - name: quality_control_phone_verification_scripts
    - name: quality_control_schedules
    - name: quick_links
    - name: registrant_matches
    - name: registration_forms
    - name: relationship_types
    - name: relationships
    - name: reports
    - name: responsibilities
    - name: roles
    - name: scans_qc_overview
    - name: scheduled_exports
    - name: scheduled_exports_turfs
    - name: schedules
    - name: schema_migrations
    - name: searches
    - name: sent_emails
    - name: shifts
    - name: states
    - name: taggings
    - name: tags
    - name: tasks
    - name: teachers
    - name: team_memberships
    - name: teams
    - name: tenant_quick_links
    - name: tenants
    - name: turf_levels
    - name: turfs
    - name: twilio_calls
    - name: user_profiles
    - name: users
    - name: venues
    - name: versions
    - name: visual_review_responses
    - name: visual_review_triggers
    - name: volunteerships
    - name: voted_labels
    - name: voter_histories
    - name: voter_registration_reports_form_lookback_by_canvasser
    - name: voter_registration_reports_form_lookback_by_turf
    - name: voter_registration_scan_batch_cover_sheets
    - name: voter_registration_scan_batches
    - name: voter_registration_scan_visual_review_responses
    - name: voter_registration_scans
    - name: voter_sources
    - name: votes
    - name: vr_zips_lookup
  
    - name: absentee_ballot_request_forms_base
    - name: activism_options_configs_base
    - name: activist_code_counts_base
    - name: activist_codes_base
    - name: activities_base
    - name: address_districts_base
    - name: addresses_base
    - name: admin_users_base
    - name: age_to_bin_base
    - name: announcements_base
    - name: announcements_views_base
    - name: ar_internal_metadata_base
    - name: blocked_tokens_base
    - name: campaigns_base
    - name: campaigns_people_base
    - name: campaigns_teams_base
    - name: canvassers_base
    - name: captricity_batches_base
    - name: catalist_uploads_base
    - name: catalist_uploads_registration_forms_base
    - name: check_in_answers_base
    - name: check_in_questions_base
    - name: check_ins_base
    - name: collections_base
    - name: collections_roles_base
    - name: contact_methods_base
    - name: coorganizations_base
    - name: counties_base
    - name: dashboard_layouts_base
    - name: dashboard_widgets_base
    - name: delayed_jobs_base
    - name: deliveries_base
    - name: delivery_forms_exclusions_base
    - name: denominations_base
    - name: denominations_organizations_base
    - name: denominations_people_base
    - name: district_types_base
    - name: districts_base
    - name: documents_base
    - name: elections_base
    - name: email_templates_base
    - name: email_templates_events_base
    - name: event_attendees_base
    - name: event_documents_base
    - name: event_shifts_base
    - name: event_types_base
    - name: events_base
    - name: events_teams_base
    - name: field_management_goals_base
    - name: field_management_projections_base
    - name: filter_rules_base
    - name: filter_views_base
    - name: folders_base
    - name: friendly_id_slugs_base
    - name: groupings_base
    - name: import_files_base
    - name: imports_base
    - name: imports_error_rows_base
    - name: landing_page_signups_base
    - name: list_folders_base
    - name: list_folders_users_base
    - name: lists_base
    - name: lists_people_base
    - name: locations_base
    - name: locations_organizations_base
    - name: meetings_base
    - name: metrics_base
    - name: missing_fks_base
    - name: notes_base
    - name: organization_memberships_base
    - name: organizations_base
    - name: organizations_teams_base
    - name: parties_base
    - name: people_base
    - name: petition_packets_base
    - name: petitions_books_base
    - name: petitions_canvasser_pages_base
    - name: petitions_pages_base
    - name: petitions_signatures_base
    - name: phone_banking_answer_options_base
    - name: phone_banking_calls_base
    - name: phone_banking_phone_banks_base
    - name: phone_banking_questions_base
    - name: phone_banking_responses_base
    - name: phone_banking_script_objects_base
    - name: phone_banking_script_texts_base
    - name: phone_banking_scripts_base
    - name: phone_banking_sessions_base
    - name: phone_verification_questions_base
    - name: phone_verification_responses_base
    - name: projections_base
    - name: public_event_links_base
    - name: quality_control_comments_base
    - name: quality_control_comments_users_base
    - name: quality_control_flag_triggers_base
    - name: quality_control_flags_base
    - name: quality_control_flags_views_base
    - name: quality_control_flags_voter_registration_scans_base
    - name: quality_control_phone_verification_calls_base
    - name: quality_control_phone_verification_question_translations_base
    - name: quality_control_phone_verification_scripts_base
    - name: quality_control_schedules_base
    - name: quick_links_base
    - name: registrant_matches_base
    - name: registration_forms_base
    - name: relationship_types_base
    - name: relationships_base
    - name: reports_base
    - name: responsibilities_base
    - name: roles_base
    - name: scans_qc_overview_base
    - name: scheduled_exports_base
    - name: scheduled_exports_turfs_base
    - name: schedules_base
    - name: schema_migrations_base
    - name: searches_base
    - name: sent_emails_base
    - name: shifts_base
    - name: states_base
    - name: taggings_base
    - name: tags_base
    - name: tasks_base
    - name: teachers_base
    - name: team_memberships_base
    - name: teams_base
    - name: tenant_quick_links_base
    - name: tenants_base
    - name: turf_levels_base
    - name: turfs_base
    - name: twilio_calls_base
    - name: user_profiles_base
    - name: users_base
    - name: venues_base
    - name: versions_base
    - name: visual_review_responses_base
    - name: visual_review_triggers_base
    - name: volunteerships_base
    - name: voted_labels_base
    - name: voter_histories_base
    - name: voter_registration_reports_form_lookback_by_canvasser_base
    - name: voter_registration_reports_form_lookback_by_turf_base
    - name: voter_registration_scan_batch_cover_sheets_base
    - name: voter_registration_scan_batches_base
    - name: voter_registration_scan_visual_review_responses_base
    - name: voter_registration_scans_base
    - name: voter_sources_base
    - name: votes_base
    - name: vr_zips_lookup_base